// Code generated by ent, DO NOT EDIT.

package agentrecovery

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentrecovery type in the database.
	Label = "agent_recovery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBrokerID holds the string denoting the broker_id field in the database.
	FieldBrokerID = "broker_id"
	// FieldObservedState holds the string denoting the observed_state field in the database.
	FieldObservedState = "observed_state"
	// FieldObservedTarget holds the string denoting the observed_target field in the database.
	FieldObservedTarget = "observed_target"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldFirstAbsentAt holds the string denoting the first_absent_at field in the database.
	FieldFirstAbsentAt = "first_absent_at"
	// FieldObservedInFlight holds the string denoting the observed_in_flight field in the database.
	FieldObservedInFlight = "observed_in_flight"
	// Table holds the table name of the agentrecovery in the database.
	Table = "agent_recoveries"
)

// Columns holds all SQL columns for agentrecovery fields.
var Columns = []string{
	FieldID,
	FieldBrokerID,
	FieldObservedState,
	FieldObservedTarget,
	FieldObservedAt,
	FieldFirstAbsentAt,
	FieldObservedInFlight,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBrokerID holds the default value on creation for the "broker_id" field.
	DefaultBrokerID string
	// DefaultObservedState holds the default value on creation for the "observed_state" field.
	DefaultObservedState string
	// DefaultObservedTarget holds the default value on creation for the "observed_target" field.
	DefaultObservedTarget string
	// DefaultObservedInFlight holds the default value on creation for the "observed_in_flight" field.
	DefaultObservedInFlight bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AgentRecovery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBrokerID orders the results by the broker_id field.
func ByBrokerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrokerID, opts...).ToFunc()
}

// ByObservedState orders the results by the observed_state field.
func ByObservedState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedState, opts...).ToFunc()
}

// ByObservedTarget orders the results by the observed_target field.
func ByObservedTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedTarget, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByFirstAbsentAt orders the results by the first_absent_at field.
func ByFirstAbsentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstAbsentAt, opts...).ToFunc()
}

// ByObservedInFlight orders the results by the observed_in_flight field.
func ByObservedInFlight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedInFlight, opts...).ToFunc()
}
