// Code generated by ent, DO NOT EDIT.

package delegationedge

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the delegationedge type in the database.
	Label = "delegation_edge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvenanceVersion holds the string denoting the provenance_version field in the database.
	FieldProvenanceVersion = "provenance_version"
	// FieldSourcePrincipalKind holds the string denoting the source_principal_kind field in the database.
	FieldSourcePrincipalKind = "source_principal_kind"
	// FieldSourcePrincipalID holds the string denoting the source_principal_id field in the database.
	FieldSourcePrincipalID = "source_principal_id"
	// FieldSourceCredentialKind holds the string denoting the source_credential_kind field in the database.
	FieldSourceCredentialKind = "source_credential_kind"
	// FieldSourceCredentialID holds the string denoting the source_credential_id field in the database.
	FieldSourceCredentialID = "source_credential_id"
	// FieldSourceEventID holds the string denoting the source_event_id field in the database.
	FieldSourceEventID = "source_event_id"
	// FieldSourceScheduleID holds the string denoting the source_schedule_id field in the database.
	FieldSourceScheduleID = "source_schedule_id"
	// FieldSourceAuthorizationRevision holds the string denoting the source_authorization_revision field in the database.
	FieldSourceAuthorizationRevision = "source_authorization_revision"
	// FieldInitiatorPrincipalKind holds the string denoting the initiator_principal_kind field in the database.
	FieldInitiatorPrincipalKind = "initiator_principal_kind"
	// FieldInitiatorPrincipalID holds the string denoting the initiator_principal_id field in the database.
	FieldInitiatorPrincipalID = "initiator_principal_id"
	// FieldInitiatorCredentialKind holds the string denoting the initiator_credential_kind field in the database.
	FieldInitiatorCredentialKind = "initiator_credential_kind"
	// FieldInitiatorCredentialID holds the string denoting the initiator_credential_id field in the database.
	FieldInitiatorCredentialID = "initiator_credential_id"
	// FieldCeilingKind holds the string denoting the ceiling_kind field in the database.
	FieldCeilingKind = "ceiling_kind"
	// FieldCeilingVersion holds the string denoting the ceiling_version field in the database.
	FieldCeilingVersion = "ceiling_version"
	// FieldCeilingPermissionIds holds the string denoting the ceiling_permission_ids field in the database.
	FieldCeilingPermissionIds = "ceiling_permission_ids"
	// FieldCeilingBoundaryKind holds the string denoting the ceiling_boundary_kind field in the database.
	FieldCeilingBoundaryKind = "ceiling_boundary_kind"
	// FieldCeilingBoundaryProjectID holds the string denoting the ceiling_boundary_project_id field in the database.
	FieldCeilingBoundaryProjectID = "ceiling_boundary_project_id"
	// FieldCeilingSourceExpiresAt holds the string denoting the ceiling_source_expires_at field in the database.
	FieldCeilingSourceExpiresAt = "ceiling_source_expires_at"
	// FieldDeactivationCause holds the string denoting the deactivation_cause field in the database.
	FieldDeactivationCause = "deactivation_cause"
	// FieldDeactivatedAt holds the string denoting the deactivated_at field in the database.
	FieldDeactivatedAt = "deactivated_at"
	// FieldDeactivationOpID holds the string denoting the deactivation_op_id field in the database.
	FieldDeactivationOpID = "deactivation_op_id"
	// FieldDelegatorType holds the string denoting the delegator_type field in the database.
	FieldDelegatorType = "delegator_type"
	// FieldDelegatorID holds the string denoting the delegator_id field in the database.
	FieldDelegatorID = "delegator_id"
	// FieldDelegateType holds the string denoting the delegate_type field in the database.
	FieldDelegateType = "delegate_type"
	// FieldDelegateID holds the string denoting the delegate_id field in the database.
	FieldDelegateID = "delegate_id"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldGrandfathered holds the string denoting the grandfathered field in the database.
	FieldGrandfathered = "grandfathered"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// Table holds the table name of the delegationedge in the database.
	Table = "delegation_edges"
)

// Columns holds all SQL columns for delegationedge fields.
var Columns = []string{
	FieldID,
	FieldProvenanceVersion,
	FieldSourcePrincipalKind,
	FieldSourcePrincipalID,
	FieldSourceCredentialKind,
	FieldSourceCredentialID,
	FieldSourceEventID,
	FieldSourceScheduleID,
	FieldSourceAuthorizationRevision,
	FieldInitiatorPrincipalKind,
	FieldInitiatorPrincipalID,
	FieldInitiatorCredentialKind,
	FieldInitiatorCredentialID,
	FieldCeilingKind,
	FieldCeilingVersion,
	FieldCeilingPermissionIds,
	FieldCeilingBoundaryKind,
	FieldCeilingBoundaryProjectID,
	FieldCeilingSourceExpiresAt,
	FieldDeactivationCause,
	FieldDeactivatedAt,
	FieldDeactivationOpID,
	FieldDelegatorType,
	FieldDelegatorID,
	FieldDelegateType,
	FieldDelegateID,
	FieldScopeType,
	FieldScopeID,
	FieldRole,
	FieldActive,
	FieldGrandfathered,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProvenanceVersion holds the default value on creation for the "provenance_version" field.
	DefaultProvenanceVersion int
	// DefaultSourcePrincipalKind holds the default value on creation for the "source_principal_kind" field.
	DefaultSourcePrincipalKind string
	// DefaultSourcePrincipalID holds the default value on creation for the "source_principal_id" field.
	DefaultSourcePrincipalID string
	// DefaultSourceCredentialKind holds the default value on creation for the "source_credential_kind" field.
	DefaultSourceCredentialKind string
	// DefaultSourceCredentialID holds the default value on creation for the "source_credential_id" field.
	DefaultSourceCredentialID string
	// DefaultSourceEventID holds the default value on creation for the "source_event_id" field.
	DefaultSourceEventID string
	// DefaultSourceAuthorizationRevision holds the default value on creation for the "source_authorization_revision" field.
	DefaultSourceAuthorizationRevision int
	// DefaultInitiatorPrincipalKind holds the default value on creation for the "initiator_principal_kind" field.
	DefaultInitiatorPrincipalKind string
	// DefaultInitiatorPrincipalID holds the default value on creation for the "initiator_principal_id" field.
	DefaultInitiatorPrincipalID string
	// DefaultInitiatorCredentialKind holds the default value on creation for the "initiator_credential_kind" field.
	DefaultInitiatorCredentialKind string
	// DefaultInitiatorCredentialID holds the default value on creation for the "initiator_credential_id" field.
	DefaultInitiatorCredentialID string
	// DefaultCeilingKind holds the default value on creation for the "ceiling_kind" field.
	DefaultCeilingKind string
	// DefaultCeilingVersion holds the default value on creation for the "ceiling_version" field.
	DefaultCeilingVersion int32
	// DefaultCeilingBoundaryKind holds the default value on creation for the "ceiling_boundary_kind" field.
	DefaultCeilingBoundaryKind string
	// DefaultCeilingBoundaryProjectID holds the default value on creation for the "ceiling_boundary_project_id" field.
	DefaultCeilingBoundaryProjectID string
	// DefaultDeactivationCause holds the default value on creation for the "deactivation_cause" field.
	DefaultDeactivationCause string
	// DefaultDeactivationOpID holds the default value on creation for the "deactivation_op_id" field.
	DefaultDeactivationOpID string
	// DelegatorIDValidator is a validator for the "delegator_id" field. It is called by the builders before save.
	DelegatorIDValidator func(string) error
	// DelegateIDValidator is a validator for the "delegate_id" field. It is called by the builders before save.
	DelegateIDValidator func(string) error
	// DefaultScopeID holds the default value on creation for the "scope_id" field.
	DefaultScopeID string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultGrandfathered holds the default value on creation for the "grandfathered" field.
	DefaultGrandfathered bool
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// DelegatorType defines the type for the "delegator_type" enum field.
type DelegatorType string

// DelegatorType values.
const (
	DelegatorTypeUser  DelegatorType = "user"
	DelegatorTypeAgent DelegatorType = "agent"
)

func (dt DelegatorType) String() string {
	return string(dt)
}

// DelegatorTypeValidator is a validator for the "delegator_type" field enum values. It is called by the builders before save.
func DelegatorTypeValidator(dt DelegatorType) error {
	switch dt {
	case DelegatorTypeUser, DelegatorTypeAgent:
		return nil
	default:
		return fmt.Errorf("delegationedge: invalid enum value for delegator_type field: %q", dt)
	}
}

// DelegateType defines the type for the "delegate_type" enum field.
type DelegateType string

// DelegateType values.
const (
	DelegateTypeUser  DelegateType = "user"
	DelegateTypeAgent DelegateType = "agent"
)

func (dt DelegateType) String() string {
	return string(dt)
}

// DelegateTypeValidator is a validator for the "delegate_type" field enum values. It is called by the builders before save.
func DelegateTypeValidator(dt DelegateType) error {
	switch dt {
	case DelegateTypeUser, DelegateTypeAgent:
		return nil
	default:
		return fmt.Errorf("delegationedge: invalid enum value for delegate_type field: %q", dt)
	}
}

// ScopeType defines the type for the "scope_type" enum field.
type ScopeType string

// ScopeType values.
const (
	ScopeTypeSystem  ScopeType = "system"
	ScopeTypeProject ScopeType = "project"
)

func (st ScopeType) String() string {
	return string(st)
}

// ScopeTypeValidator is a validator for the "scope_type" field enum values. It is called by the builders before save.
func ScopeTypeValidator(st ScopeType) error {
	switch st {
	case ScopeTypeSystem, ScopeTypeProject:
		return nil
	default:
		return fmt.Errorf("delegationedge: invalid enum value for scope_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the DelegationEdge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvenanceVersion orders the results by the provenance_version field.
func ByProvenanceVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvenanceVersion, opts...).ToFunc()
}

// BySourcePrincipalKind orders the results by the source_principal_kind field.
func BySourcePrincipalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePrincipalKind, opts...).ToFunc()
}

// BySourcePrincipalID orders the results by the source_principal_id field.
func BySourcePrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePrincipalID, opts...).ToFunc()
}

// BySourceCredentialKind orders the results by the source_credential_kind field.
func BySourceCredentialKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCredentialKind, opts...).ToFunc()
}

// BySourceCredentialID orders the results by the source_credential_id field.
func BySourceCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCredentialID, opts...).ToFunc()
}

// BySourceEventID orders the results by the source_event_id field.
func BySourceEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceEventID, opts...).ToFunc()
}

// BySourceScheduleID orders the results by the source_schedule_id field.
func BySourceScheduleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceScheduleID, opts...).ToFunc()
}

// BySourceAuthorizationRevision orders the results by the source_authorization_revision field.
func BySourceAuthorizationRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceAuthorizationRevision, opts...).ToFunc()
}

// ByInitiatorPrincipalKind orders the results by the initiator_principal_kind field.
func ByInitiatorPrincipalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorPrincipalKind, opts...).ToFunc()
}

// ByInitiatorPrincipalID orders the results by the initiator_principal_id field.
func ByInitiatorPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorPrincipalID, opts...).ToFunc()
}

// ByInitiatorCredentialKind orders the results by the initiator_credential_kind field.
func ByInitiatorCredentialKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorCredentialKind, opts...).ToFunc()
}

// ByInitiatorCredentialID orders the results by the initiator_credential_id field.
func ByInitiatorCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorCredentialID, opts...).ToFunc()
}

// ByCeilingKind orders the results by the ceiling_kind field.
func ByCeilingKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingKind, opts...).ToFunc()
}

// ByCeilingVersion orders the results by the ceiling_version field.
func ByCeilingVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingVersion, opts...).ToFunc()
}

// ByCeilingPermissionIds orders the results by the ceiling_permission_ids field.
func ByCeilingPermissionIds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingPermissionIds, opts...).ToFunc()
}

// ByCeilingBoundaryKind orders the results by the ceiling_boundary_kind field.
func ByCeilingBoundaryKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingBoundaryKind, opts...).ToFunc()
}

// ByCeilingBoundaryProjectID orders the results by the ceiling_boundary_project_id field.
func ByCeilingBoundaryProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingBoundaryProjectID, opts...).ToFunc()
}

// ByCeilingSourceExpiresAt orders the results by the ceiling_source_expires_at field.
func ByCeilingSourceExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCeilingSourceExpiresAt, opts...).ToFunc()
}

// ByDeactivationCause orders the results by the deactivation_cause field.
func ByDeactivationCause(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeactivationCause, opts...).ToFunc()
}

// ByDeactivatedAt orders the results by the deactivated_at field.
func ByDeactivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeactivatedAt, opts...).ToFunc()
}

// ByDeactivationOpID orders the results by the deactivation_op_id field.
func ByDeactivationOpID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeactivationOpID, opts...).ToFunc()
}

// ByDelegatorType orders the results by the delegator_type field.
func ByDelegatorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegatorType, opts...).ToFunc()
}

// ByDelegatorID orders the results by the delegator_id field.
func ByDelegatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegatorID, opts...).ToFunc()
}

// ByDelegateType orders the results by the delegate_type field.
func ByDelegateType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegateType, opts...).ToFunc()
}

// ByDelegateID orders the results by the delegate_id field.
func ByDelegateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelegateID, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByGrandfathered orders the results by the grandfathered field.
func ByGrandfathered(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrandfathered, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}
