// Code generated by ent, DO NOT EDIT.

package agentreincarnation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentreincarnation type in the database.
	Label = "agent_reincarnation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldFromGeneration holds the string denoting the from_generation field in the database.
	FieldFromGeneration = "from_generation"
	// FieldToGeneration holds the string denoting the to_generation field in the database.
	FieldToGeneration = "to_generation"
	// FieldRequestedBy holds the string denoting the requested_by field in the database.
	FieldRequestedBy = "requested_by"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldPreviousAppliedConfig holds the string denoting the previous_applied_config field in the database.
	FieldPreviousAppliedConfig = "previous_applied_config"
	// FieldNewAppliedConfig holds the string denoting the new_applied_config field in the database.
	FieldNewAppliedConfig = "new_applied_config"
	// FieldHandoff holds the string denoting the handoff field in the database.
	FieldHandoff = "handoff"
	// FieldSourceBrokerID holds the string denoting the source_broker_id field in the database.
	FieldSourceBrokerID = "source_broker_id"
	// FieldTargetBrokerID holds the string denoting the target_broker_id field in the database.
	FieldTargetBrokerID = "target_broker_id"
	// FieldSourceCleanup holds the string denoting the source_cleanup field in the database.
	FieldSourceCleanup = "source_cleanup"
	// Table holds the table name of the agentreincarnation in the database.
	Table = "agent_reincarnations"
)

// Columns holds all SQL columns for agentreincarnation fields.
var Columns = []string{
	FieldID,
	FieldAgentID,
	FieldFromGeneration,
	FieldToGeneration,
	FieldRequestedBy,
	FieldRequestedAt,
	FieldUpdatedAt,
	FieldCompletedAt,
	FieldState,
	FieldError,
	FieldPreviousAppliedConfig,
	FieldNewAppliedConfig,
	FieldHandoff,
	FieldSourceBrokerID,
	FieldTargetBrokerID,
	FieldSourceCleanup,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	AgentIDValidator func(string) error
	// DefaultRequestedAt holds the default value on creation for the "requested_at" field.
	DefaultRequestedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StatePending is the default value of the State enum.
const DefaultState = StatePending

// State values.
const (
	StatePending      State = "pending"
	StateStopping     State = "stopping"
	StateProvisioning State = "provisioning"
	StateStarting     State = "starting"
	StateCompleted    State = "completed"
	StateFailed       State = "failed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePending, StateStopping, StateProvisioning, StateStarting, StateCompleted, StateFailed:
		return nil
	default:
		return fmt.Errorf("agentreincarnation: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the AgentReincarnation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByFromGeneration orders the results by the from_generation field.
func ByFromGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromGeneration, opts...).ToFunc()
}

// ByToGeneration orders the results by the to_generation field.
func ByToGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToGeneration, opts...).ToFunc()
}

// ByRequestedBy orders the results by the requested_by field.
func ByRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedBy, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByPreviousAppliedConfig orders the results by the previous_applied_config field.
func ByPreviousAppliedConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousAppliedConfig, opts...).ToFunc()
}

// ByNewAppliedConfig orders the results by the new_applied_config field.
func ByNewAppliedConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewAppliedConfig, opts...).ToFunc()
}

// ByHandoff orders the results by the handoff field.
func ByHandoff(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandoff, opts...).ToFunc()
}

// BySourceBrokerID orders the results by the source_broker_id field.
func BySourceBrokerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceBrokerID, opts...).ToFunc()
}

// ByTargetBrokerID orders the results by the target_broker_id field.
func ByTargetBrokerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetBrokerID, opts...).ToFunc()
}

// BySourceCleanup orders the results by the source_cleanup field.
func BySourceCleanup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCleanup, opts...).ToFunc()
}
