// Code generated by ent, DO NOT EDIT.

package hubinstance

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the hubinstance type in the database.
	Label = "hub_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "instance_id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldStoppedAt holds the string denoting the stopped_at field in the database.
	FieldStoppedAt = "stopped_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldChecks holds the string denoting the checks field in the database.
	FieldChecks = "checks"
	// FieldStats holds the string denoting the stats field in the database.
	FieldStats = "stats"
	// Table holds the table name of the hubinstance in the database.
	Table = "hub_instances"
)

// Columns holds all SQL columns for hubinstance fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldVersion,
	FieldStartedAt,
	FieldLastSeen,
	FieldStoppedAt,
	FieldStatus,
	FieldChecks,
	FieldStats,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the HubInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByStoppedAt orders the results by the stopped_at field.
func ByStoppedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoppedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
