// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package conduit

import (
	"sync"
	"sync/atomic"

	conduitv1 "github.com/GoogleCloudPlatform/scion/proto/conduit/v1"
)

// Stats are the scheduler and buffer counters of a session (test seam and
// operator metric). Byte counts are encoded-frame estimates.
type Stats struct {
	// Budget is the aggregate outbound buffer budget.
	Budget int64
	// QueuedControlBytes / QueuedDataBytes are currently buffered for
	// sending; QueuedBytes is their sum and PeakQueuedBytes its high-water
	// mark over the session.
	QueuedControlBytes int64
	QueuedDataBytes    int64
	QueuedBytes        int64
	PeakQueuedBytes    int64
	// ControlFramesSent / DataFramesSent count frames written.
	ControlFramesSent int64
	DataFramesSent    int64
	// RecvBufferedBytes is stream data received but not yet read by the
	// application, summed over streams; PeakRecvBufferedBytes is its
	// high-water mark.
	RecvBufferedBytes     int64
	PeakRecvBufferedBytes int64
	// OpenStreams is the number of streams in the session's table.
	OpenStreams int
}

// frameClass selects the scheduler queue.
type frameClass int

const (
	// classControl frames (Rpc*, StreamOpen/Accept/Close, StreamWindow,
	// StreamResize, Ping/Pong, GoAway, AuthRefresh) go to the reserved
	// queue that is always served first.
	classControl frameClass = iota
	// classData frames (StreamData, and a graceful StreamClose that must
	// follow the stream's data) go to the stream's FIFO; streams are
	// served round-robin.
	classData
)

// dataFrameOverhead approximates the encoding overhead of a StreamData
// frame beyond its payload.
const dataFrameOverhead = 16

// controlReserve is extra budget that protocol-internal control frames
// (window updates, pongs, closes generated by the read loop) may use above
// the aggregate budget, so that the read loop never blocks on budget.
const controlReserve = 256 * 1024

type outFrame struct {
	f        *conduitv1.Frame
	class    frameClass
	streamID uint32
	size     int64
	// sent runs on the writer goroutine after the frame was written.
	sent func()
}

// scheduler orders outbound frames: control first, then data round-robin
// across streams, under an aggregate byte budget.
type scheduler struct {
	mu      sync.Mutex
	budget  int64
	control []*outFrame
	data    map[uint32][]*outFrame
	rr      []uint32 // streams with queued data, in service order
	closed  bool
	// wake is closed (and replaced) whenever state changes, to wake
	// blocked enqueuers and the writer.
	wake chan struct{}

	queuedControl int64
	queuedData    int64
	peak          int64

	controlSent atomic.Int64
	dataSent    atomic.Int64
}

func newScheduler(budget int64) *scheduler {
	return &scheduler{budget: budget, data: map[uint32][]*outFrame{}, wake: make(chan struct{})}
}

func (s *scheduler) signalLocked() {
	close(s.wake)
	s.wake = make(chan struct{})
}

func (s *scheduler) queuedLocked() int64 { return s.queuedControl + s.queuedData }

func (s *scheduler) pushLocked(of *outFrame) {
	if of.class == classControl {
		s.control = append(s.control, of)
		s.queuedControl += of.size
	} else {
		q := s.data[of.streamID]
		if len(q) == 0 {
			s.rr = append(s.rr, of.streamID)
		}
		s.data[of.streamID] = append(q, of)
		s.queuedData += of.size
	}
	if q := s.queuedLocked(); q > s.peak {
		s.peak = q
	}
	s.signalLocked()
}

// enqueue blocks until the frame fits within the budget, then queues it.
// It fails with ErrSessionClosed after close, or with the error returned
// by abort when abort's channel fires (stream closed, ctx cancelled).
// A frame larger than the whole budget is admitted once the queue is
// empty, so it cannot deadlock.
func (s *scheduler) enqueue(of *outFrame, abort <-chan struct{}, abortErr func() error) error {
	for {
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			return ErrSessionClosed
		}
		q := s.queuedLocked()
		if q+of.size <= s.budget || q == 0 {
			s.pushLocked(of)
			s.mu.Unlock()
			return nil
		}
		wake := s.wake
		s.mu.Unlock()
		select {
		case <-wake:
		case <-abort:
			return abortErr()
		}
	}
}

// enqueueInternal queues a protocol-internal frame without blocking. It
// may use controlReserve above the budget; beyond that it fails with
// ErrBufferBudget (the writer is stuck and the session must end).
func (s *scheduler) enqueueInternal(of *outFrame) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrSessionClosed
	}
	if s.queuedLocked()+of.size > s.budget+controlReserve {
		return ErrBufferBudget
	}
	s.pushLocked(of)
	return nil
}

// next blocks until a frame is available or the scheduler is closed.
func (s *scheduler) next() (*outFrame, bool) {
	for {
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			return nil, false
		}
		if len(s.control) > 0 {
			of := s.control[0]
			s.control[0] = nil
			s.control = s.control[1:]
			s.queuedControl -= of.size
			s.signalLocked()
			s.mu.Unlock()
			return of, true
		}
		if len(s.rr) > 0 {
			id := s.rr[0]
			s.rr = s.rr[1:]
			q := s.data[id]
			of := q[0]
			q[0] = nil
			q = q[1:]
			if len(q) == 0 {
				delete(s.data, id)
			} else {
				s.data[id] = q
				s.rr = append(s.rr, id) // back of the round-robin line
			}
			s.queuedData -= of.size
			s.signalLocked()
			s.mu.Unlock()
			return of, true
		}
		wake := s.wake
		s.mu.Unlock()
		<-wake
	}
}

// purge drops a stream's queued data frames (abortive close) and returns
// the number of payload bytes dropped, so their send credit can be
// restored: the peer never saw them.
func (s *scheduler) purge(streamID uint32) (payload int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	q, ok := s.data[streamID]
	if !ok {
		return 0
	}
	for _, of := range q {
		s.queuedData -= of.size
		if d := of.f.GetStreamData(); d != nil {
			payload += int64(len(d.GetData()))
		}
	}
	delete(s.data, streamID)
	for i, id := range s.rr {
		if id == streamID {
			s.rr = append(s.rr[:i], s.rr[i+1:]...)
			break
		}
	}
	s.signalLocked()
	return payload
}

func (s *scheduler) close() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if !s.closed {
		s.closed = true
		s.signalLocked()
	}
}

func (s *scheduler) stats(st *Stats) {
	s.mu.Lock()
	defer s.mu.Unlock()
	st.Budget = s.budget
	st.QueuedControlBytes = s.queuedControl
	st.QueuedDataBytes = s.queuedData
	st.QueuedBytes = s.queuedLocked()
	st.PeakQueuedBytes = s.peak
	st.ControlFramesSent = s.controlSent.Load()
	st.DataFramesSent = s.dataSent.Load()
}
