// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentidentitykey"
	"github.com/google/uuid"
)

// AgentIdentityKeyCreate is the builder for creating a AgentIdentityKey entity.
type AgentIdentityKeyCreate struct {
	config
	mutation *AgentIdentityKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectID sets the "project_id" field.
func (_c *AgentIdentityKeyCreate) SetProjectID(v uuid.UUID) *AgentIdentityKeyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *AgentIdentityKeyCreate) SetKey(v string) *AgentIdentityKeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *AgentIdentityKeyCreate) SetAgentID(v uuid.UUID) *AgentIdentityKeyCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AgentIdentityKeyCreate) SetID(v uuid.UUID) *AgentIdentityKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentIdentityKeyCreate) SetNillableID(v *uuid.UUID) *AgentIdentityKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AgentIdentityKeyMutation object of the builder.
func (_c *AgentIdentityKeyCreate) Mutation() *AgentIdentityKeyMutation {
	return _c.mutation
}

// Save creates the AgentIdentityKey in the database.
func (_c *AgentIdentityKeyCreate) Save(ctx context.Context) (*AgentIdentityKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentIdentityKeyCreate) SaveX(ctx context.Context) *AgentIdentityKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentIdentityKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentIdentityKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentIdentityKeyCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := agentidentitykey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentIdentityKeyCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "AgentIdentityKey.project_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AgentIdentityKey.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := agentidentitykey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AgentIdentityKey.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "AgentIdentityKey.agent_id"`)}
	}
	return nil
}

func (_c *AgentIdentityKeyCreate) sqlSave(ctx context.Context) (*AgentIdentityKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentIdentityKeyCreate) createSpec() (*AgentIdentityKey, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentIdentityKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentidentitykey.Table, sqlgraph.NewFieldSpec(agentidentitykey.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(agentidentitykey.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(agentidentitykey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(agentidentitykey.FieldAgentID, field.TypeUUID, value)
		_node.AgentID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentIdentityKey.Create().
//		SetProjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentIdentityKeyUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentIdentityKeyCreate) OnConflict(opts ...sql.ConflictOption) *AgentIdentityKeyUpsertOne {
	_c.conflict = opts
	return &AgentIdentityKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentIdentityKeyCreate) OnConflictColumns(columns ...string) *AgentIdentityKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentIdentityKeyUpsertOne{
		create: _c,
	}
}

type (
	// AgentIdentityKeyUpsertOne is the builder for "upsert"-ing
	//  one AgentIdentityKey node.
	AgentIdentityKeyUpsertOne struct {
		create *AgentIdentityKeyCreate
	}

	// AgentIdentityKeyUpsert is the "OnConflict" setter.
	AgentIdentityKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectID sets the "project_id" field.
func (u *AgentIdentityKeyUpsert) SetProjectID(v uuid.UUID) *AgentIdentityKeyUpsert {
	u.Set(agentidentitykey.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsert) UpdateProjectID() *AgentIdentityKeyUpsert {
	u.SetExcluded(agentidentitykey.FieldProjectID)
	return u
}

// SetKey sets the "key" field.
func (u *AgentIdentityKeyUpsert) SetKey(v string) *AgentIdentityKeyUpsert {
	u.Set(agentidentitykey.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsert) UpdateKey() *AgentIdentityKeyUpsert {
	u.SetExcluded(agentidentitykey.FieldKey)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *AgentIdentityKeyUpsert) SetAgentID(v uuid.UUID) *AgentIdentityKeyUpsert {
	u.Set(agentidentitykey.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsert) UpdateAgentID() *AgentIdentityKeyUpsert {
	u.SetExcluded(agentidentitykey.FieldAgentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentidentitykey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentIdentityKeyUpsertOne) UpdateNewValues() *AgentIdentityKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(agentidentitykey.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentIdentityKeyUpsertOne) Ignore() *AgentIdentityKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentIdentityKeyUpsertOne) DoNothing() *AgentIdentityKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentIdentityKeyCreate.OnConflict
// documentation for more info.
func (u *AgentIdentityKeyUpsertOne) Update(set func(*AgentIdentityKeyUpsert)) *AgentIdentityKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentIdentityKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *AgentIdentityKeyUpsertOne) SetProjectID(v uuid.UUID) *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertOne) UpdateProjectID() *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateProjectID()
	})
}

// SetKey sets the "key" field.
func (u *AgentIdentityKeyUpsertOne) SetKey(v string) *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertOne) UpdateKey() *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateKey()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *AgentIdentityKeyUpsertOne) SetAgentID(v uuid.UUID) *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertOne) UpdateAgentID() *AgentIdentityKeyUpsertOne {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateAgentID()
	})
}

// Exec executes the query.
func (u *AgentIdentityKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentIdentityKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentIdentityKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentIdentityKeyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AgentIdentityKeyUpsertOne.ID is not supported by MySQL driver. Use AgentIdentityKeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentIdentityKeyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentIdentityKeyCreateBulk is the builder for creating many AgentIdentityKey entities in bulk.
type AgentIdentityKeyCreateBulk struct {
	config
	err      error
	builders []*AgentIdentityKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentIdentityKey entities in the database.
func (_c *AgentIdentityKeyCreateBulk) Save(ctx context.Context) ([]*AgentIdentityKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentIdentityKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentIdentityKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentIdentityKeyCreateBulk) SaveX(ctx context.Context) []*AgentIdentityKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentIdentityKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentIdentityKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentIdentityKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentIdentityKeyUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentIdentityKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentIdentityKeyUpsertBulk {
	_c.conflict = opts
	return &AgentIdentityKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentIdentityKeyCreateBulk) OnConflictColumns(columns ...string) *AgentIdentityKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentIdentityKeyUpsertBulk{
		create: _c,
	}
}

// AgentIdentityKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentIdentityKey nodes.
type AgentIdentityKeyUpsertBulk struct {
	create *AgentIdentityKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentidentitykey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentIdentityKeyUpsertBulk) UpdateNewValues() *AgentIdentityKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(agentidentitykey.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentIdentityKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentIdentityKeyUpsertBulk) Ignore() *AgentIdentityKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentIdentityKeyUpsertBulk) DoNothing() *AgentIdentityKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentIdentityKeyCreateBulk.OnConflict
// documentation for more info.
func (u *AgentIdentityKeyUpsertBulk) Update(set func(*AgentIdentityKeyUpsert)) *AgentIdentityKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentIdentityKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *AgentIdentityKeyUpsertBulk) SetProjectID(v uuid.UUID) *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertBulk) UpdateProjectID() *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateProjectID()
	})
}

// SetKey sets the "key" field.
func (u *AgentIdentityKeyUpsertBulk) SetKey(v string) *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertBulk) UpdateKey() *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateKey()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *AgentIdentityKeyUpsertBulk) SetAgentID(v uuid.UUID) *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentIdentityKeyUpsertBulk) UpdateAgentID() *AgentIdentityKeyUpsertBulk {
	return u.Update(func(s *AgentIdentityKeyUpsert) {
		s.UpdateAgentID()
	})
}

// Exec executes the query.
func (u *AgentIdentityKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentIdentityKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentIdentityKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentIdentityKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
