// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentdelegationgrant"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AgentDelegationGrantDelete is the builder for deleting a AgentDelegationGrant entity.
type AgentDelegationGrantDelete struct {
	config
	hooks    []Hook
	mutation *AgentDelegationGrantMutation
}

// Where appends a list predicates to the AgentDelegationGrantDelete builder.
func (_d *AgentDelegationGrantDelete) Where(ps ...predicate.AgentDelegationGrant) *AgentDelegationGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentDelegationGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentDelegationGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentDelegationGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentdelegationgrant.Table, sqlgraph.NewFieldSpec(agentdelegationgrant.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentDelegationGrantDeleteOne is the builder for deleting a single AgentDelegationGrant entity.
type AgentDelegationGrantDeleteOne struct {
	_d *AgentDelegationGrantDelete
}

// Where appends a list predicates to the AgentDelegationGrantDelete builder.
func (_d *AgentDelegationGrantDeleteOne) Where(ps ...predicate.AgentDelegationGrant) *AgentDelegationGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentDelegationGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentdelegationgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentDelegationGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
