// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentidentitykey"
	"github.com/google/uuid"
)

// AgentIdentityKey is the model entity for the AgentIdentityKey schema.
type AgentIdentityKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID      uuid.UUID `json:"agent_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentIdentityKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentidentitykey.FieldKey:
			values[i] = new(sql.NullString)
		case agentidentitykey.FieldID, agentidentitykey.FieldProjectID, agentidentitykey.FieldAgentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentIdentityKey fields.
func (_m *AgentIdentityKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentidentitykey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agentidentitykey.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case agentidentitykey.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case agentidentitykey.FieldAgentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value != nil {
				_m.AgentID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentIdentityKey.
// This includes values selected through modifiers, order, etc.
func (_m *AgentIdentityKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AgentIdentityKey.
// Note that you need to call AgentIdentityKey.Unwrap() before calling this method if this AgentIdentityKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentIdentityKey) Update() *AgentIdentityKeyUpdateOne {
	return NewAgentIdentityKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentIdentityKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentIdentityKey) Unwrap() *AgentIdentityKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentIdentityKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentIdentityKey) String() string {
	var builder strings.Builder
	builder.WriteString("AgentIdentityKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentID))
	builder.WriteByte(')')
	return builder.String()
}

// AgentIdentityKeys is a parsable slice of AgentIdentityKey.
type AgentIdentityKeys []*AgentIdentityKey
