// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/brokersetting"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// BrokerSettingUpdate is the builder for updating BrokerSetting entities.
type BrokerSettingUpdate struct {
	config
	hooks    []Hook
	mutation *BrokerSettingMutation
}

// Where appends a list predicates to the BrokerSettingUpdate builder.
func (_u *BrokerSettingUpdate) Where(ps ...predicate.BrokerSetting) *BrokerSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *BrokerSettingUpdate) SetBrokerID(v string) *BrokerSettingUpdate {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *BrokerSettingUpdate) SetNillableBrokerID(v *string) *BrokerSettingUpdate {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *BrokerSettingUpdate) SetValue(v json.RawMessage) *BrokerSettingUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *BrokerSettingUpdate) AppendValue(v json.RawMessage) *BrokerSettingUpdate {
	_u.mutation.AppendValue(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *BrokerSettingUpdate) SetRevision(v int64) *BrokerSettingUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *BrokerSettingUpdate) SetNillableRevision(v *int64) *BrokerSettingUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *BrokerSettingUpdate) AddRevision(v int64) *BrokerSettingUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BrokerSettingUpdate) SetUpdatedBy(v string) *BrokerSettingUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BrokerSettingUpdate) SetNillableUpdatedBy(v *string) *BrokerSettingUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BrokerSettingUpdate) ClearUpdatedBy() *BrokerSettingUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *BrokerSettingUpdate) SetUpdateTime(v time.Time) *BrokerSettingUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the BrokerSettingMutation object of the builder.
func (_u *BrokerSettingUpdate) Mutation() *BrokerSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BrokerSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrokerSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BrokerSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrokerSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BrokerSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := brokersetting.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrokerSettingUpdate) check() error {
	if v, ok := _u.mutation.BrokerID(); ok {
		if err := brokersetting.BrokerIDValidator(v); err != nil {
			return &ValidationError{Name: "broker_id", err: fmt.Errorf(`ent: validator failed for field "BrokerSetting.broker_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BrokerSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(brokersetting.Table, brokersetting.Columns, sqlgraph.NewFieldSpec(brokersetting.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(brokersetting.FieldBrokerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(brokersetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, brokersetting.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(brokersetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(brokersetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(brokersetting.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(brokersetting.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(brokersetting.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brokersetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BrokerSettingUpdateOne is the builder for updating a single BrokerSetting entity.
type BrokerSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BrokerSettingMutation
}

// SetBrokerID sets the "broker_id" field.
func (_u *BrokerSettingUpdateOne) SetBrokerID(v string) *BrokerSettingUpdateOne {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *BrokerSettingUpdateOne) SetNillableBrokerID(v *string) *BrokerSettingUpdateOne {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *BrokerSettingUpdateOne) SetValue(v json.RawMessage) *BrokerSettingUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *BrokerSettingUpdateOne) AppendValue(v json.RawMessage) *BrokerSettingUpdateOne {
	_u.mutation.AppendValue(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *BrokerSettingUpdateOne) SetRevision(v int64) *BrokerSettingUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *BrokerSettingUpdateOne) SetNillableRevision(v *int64) *BrokerSettingUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *BrokerSettingUpdateOne) AddRevision(v int64) *BrokerSettingUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BrokerSettingUpdateOne) SetUpdatedBy(v string) *BrokerSettingUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BrokerSettingUpdateOne) SetNillableUpdatedBy(v *string) *BrokerSettingUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BrokerSettingUpdateOne) ClearUpdatedBy() *BrokerSettingUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *BrokerSettingUpdateOne) SetUpdateTime(v time.Time) *BrokerSettingUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the BrokerSettingMutation object of the builder.
func (_u *BrokerSettingUpdateOne) Mutation() *BrokerSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the BrokerSettingUpdate builder.
func (_u *BrokerSettingUpdateOne) Where(ps ...predicate.BrokerSetting) *BrokerSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BrokerSettingUpdateOne) Select(field string, fields ...string) *BrokerSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BrokerSetting entity.
func (_u *BrokerSettingUpdateOne) Save(ctx context.Context) (*BrokerSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrokerSettingUpdateOne) SaveX(ctx context.Context) *BrokerSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BrokerSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrokerSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BrokerSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := brokersetting.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrokerSettingUpdateOne) check() error {
	if v, ok := _u.mutation.BrokerID(); ok {
		if err := brokersetting.BrokerIDValidator(v); err != nil {
			return &ValidationError{Name: "broker_id", err: fmt.Errorf(`ent: validator failed for field "BrokerSetting.broker_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BrokerSettingUpdateOne) sqlSave(ctx context.Context) (_node *BrokerSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(brokersetting.Table, brokersetting.Columns, sqlgraph.NewFieldSpec(brokersetting.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BrokerSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, brokersetting.FieldID)
		for _, f := range fields {
			if !brokersetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != brokersetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(brokersetting.FieldBrokerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(brokersetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, brokersetting.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(brokersetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(brokersetting.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(brokersetting.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(brokersetting.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(brokersetting.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &BrokerSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brokersetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
