// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/conduitsession"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/relayinstance"
)

// ConduitSessionCreate is the builder for creating a ConduitSession entity.
type ConduitSessionCreate struct {
	config
	mutation *ConduitSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPrincipalKind sets the "principal_kind" field.
func (_c *ConduitSessionCreate) SetPrincipalKind(v string) *ConduitSessionCreate {
	_c.mutation.SetPrincipalKind(v)
	return _c
}

// SetPrincipalID sets the "principal_id" field.
func (_c *ConduitSessionCreate) SetPrincipalID(v string) *ConduitSessionCreate {
	_c.mutation.SetPrincipalID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *ConduitSessionCreate) SetProjectID(v string) *ConduitSessionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *ConduitSessionCreate) SetNillableProjectID(v *string) *ConduitSessionCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetRelayInstanceID sets the "relay_instance_id" field.
func (_c *ConduitSessionCreate) SetRelayInstanceID(v string) *ConduitSessionCreate {
	_c.mutation.SetRelayInstanceID(v)
	return _c
}

// SetRelayGeneration sets the "relay_generation" field.
func (_c *ConduitSessionCreate) SetRelayGeneration(v int64) *ConduitSessionCreate {
	_c.mutation.SetRelayGeneration(v)
	return _c
}

// SetTransport sets the "transport" field.
func (_c *ConduitSessionCreate) SetTransport(v string) *ConduitSessionCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetEndpointIncarnation sets the "endpoint_incarnation" field.
func (_c *ConduitSessionCreate) SetEndpointIncarnation(v string) *ConduitSessionCreate {
	_c.mutation.SetEndpointIncarnation(v)
	return _c
}

// SetExecScope sets the "exec_scope" field.
func (_c *ConduitSessionCreate) SetExecScope(v string) *ConduitSessionCreate {
	_c.mutation.SetExecScope(v)
	return _c
}

// SetNillableExecScope sets the "exec_scope" field if the given value is not nil.
func (_c *ConduitSessionCreate) SetNillableExecScope(v *string) *ConduitSessionCreate {
	if v != nil {
		_c.SetExecScope(*v)
	}
	return _c
}

// SetConnectionEpoch sets the "connection_epoch" field.
func (_c *ConduitSessionCreate) SetConnectionEpoch(v int64) *ConduitSessionCreate {
	_c.mutation.SetConnectionEpoch(v)
	return _c
}

// SetDraining sets the "draining" field.
func (_c *ConduitSessionCreate) SetDraining(v bool) *ConduitSessionCreate {
	_c.mutation.SetDraining(v)
	return _c
}

// SetNillableDraining sets the "draining" field if the given value is not nil.
func (_c *ConduitSessionCreate) SetNillableDraining(v *bool) *ConduitSessionCreate {
	if v != nil {
		_c.SetDraining(*v)
	}
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *ConduitSessionCreate) SetCapabilities(v json.RawMessage) *ConduitSessionCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetConnectedAt sets the "connected_at" field.
func (_c *ConduitSessionCreate) SetConnectedAt(v time.Time) *ConduitSessionCreate {
	_c.mutation.SetConnectedAt(v)
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *ConduitSessionCreate) SetLastSeen(v time.Time) *ConduitSessionCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ConduitSessionCreate) SetID(v string) *ConduitSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRelayID sets the "relay" edge to the RelayInstance entity by ID.
func (_c *ConduitSessionCreate) SetRelayID(id string) *ConduitSessionCreate {
	_c.mutation.SetRelayID(id)
	return _c
}

// SetRelay sets the "relay" edge to the RelayInstance entity.
func (_c *ConduitSessionCreate) SetRelay(v *RelayInstance) *ConduitSessionCreate {
	return _c.SetRelayID(v.ID)
}

// Mutation returns the ConduitSessionMutation object of the builder.
func (_c *ConduitSessionCreate) Mutation() *ConduitSessionMutation {
	return _c.mutation
}

// Save creates the ConduitSession in the database.
func (_c *ConduitSessionCreate) Save(ctx context.Context) (*ConduitSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConduitSessionCreate) SaveX(ctx context.Context) *ConduitSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConduitSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConduitSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConduitSessionCreate) defaults() {
	if _, ok := _c.mutation.Draining(); !ok {
		v := conduitsession.DefaultDraining
		_c.mutation.SetDraining(v)
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		v := conduitsession.DefaultCapabilities
		_c.mutation.SetCapabilities(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConduitSessionCreate) check() error {
	if _, ok := _c.mutation.PrincipalKind(); !ok {
		return &ValidationError{Name: "principal_kind", err: errors.New(`ent: missing required field "ConduitSession.principal_kind"`)}
	}
	if v, ok := _c.mutation.PrincipalKind(); ok {
		if err := conduitsession.PrincipalKindValidator(v); err != nil {
			return &ValidationError{Name: "principal_kind", err: fmt.Errorf(`ent: validator failed for field "ConduitSession.principal_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrincipalID(); !ok {
		return &ValidationError{Name: "principal_id", err: errors.New(`ent: missing required field "ConduitSession.principal_id"`)}
	}
	if v, ok := _c.mutation.PrincipalID(); ok {
		if err := conduitsession.PrincipalIDValidator(v); err != nil {
			return &ValidationError{Name: "principal_id", err: fmt.Errorf(`ent: validator failed for field "ConduitSession.principal_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RelayInstanceID(); !ok {
		return &ValidationError{Name: "relay_instance_id", err: errors.New(`ent: missing required field "ConduitSession.relay_instance_id"`)}
	}
	if v, ok := _c.mutation.RelayInstanceID(); ok {
		if err := conduitsession.RelayInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "relay_instance_id", err: fmt.Errorf(`ent: validator failed for field "ConduitSession.relay_instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RelayGeneration(); !ok {
		return &ValidationError{Name: "relay_generation", err: errors.New(`ent: missing required field "ConduitSession.relay_generation"`)}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "ConduitSession.transport"`)}
	}
	if v, ok := _c.mutation.Transport(); ok {
		if err := conduitsession.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "ConduitSession.transport": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndpointIncarnation(); !ok {
		return &ValidationError{Name: "endpoint_incarnation", err: errors.New(`ent: missing required field "ConduitSession.endpoint_incarnation"`)}
	}
	if _, ok := _c.mutation.ConnectionEpoch(); !ok {
		return &ValidationError{Name: "connection_epoch", err: errors.New(`ent: missing required field "ConduitSession.connection_epoch"`)}
	}
	if _, ok := _c.mutation.Draining(); !ok {
		return &ValidationError{Name: "draining", err: errors.New(`ent: missing required field "ConduitSession.draining"`)}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "ConduitSession.capabilities"`)}
	}
	if _, ok := _c.mutation.ConnectedAt(); !ok {
		return &ValidationError{Name: "connected_at", err: errors.New(`ent: missing required field "ConduitSession.connected_at"`)}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "ConduitSession.last_seen"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := conduitsession.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ConduitSession.id": %w`, err)}
		}
	}
	if len(_c.mutation.RelayIDs()) == 0 {
		return &ValidationError{Name: "relay", err: errors.New(`ent: missing required edge "ConduitSession.relay"`)}
	}
	return nil
}

func (_c *ConduitSessionCreate) sqlSave(ctx context.Context) (*ConduitSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ConduitSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConduitSessionCreate) createSpec() (*ConduitSession, *sqlgraph.CreateSpec) {
	var (
		_node = &ConduitSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conduitsession.Table, sqlgraph.NewFieldSpec(conduitsession.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PrincipalKind(); ok {
		_spec.SetField(conduitsession.FieldPrincipalKind, field.TypeString, value)
		_node.PrincipalKind = value
	}
	if value, ok := _c.mutation.PrincipalID(); ok {
		_spec.SetField(conduitsession.FieldPrincipalID, field.TypeString, value)
		_node.PrincipalID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(conduitsession.FieldProjectID, field.TypeString, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.RelayGeneration(); ok {
		_spec.SetField(conduitsession.FieldRelayGeneration, field.TypeInt64, value)
		_node.RelayGeneration = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(conduitsession.FieldTransport, field.TypeString, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.EndpointIncarnation(); ok {
		_spec.SetField(conduitsession.FieldEndpointIncarnation, field.TypeString, value)
		_node.EndpointIncarnation = value
	}
	if value, ok := _c.mutation.ExecScope(); ok {
		_spec.SetField(conduitsession.FieldExecScope, field.TypeString, value)
		_node.ExecScope = &value
	}
	if value, ok := _c.mutation.ConnectionEpoch(); ok {
		_spec.SetField(conduitsession.FieldConnectionEpoch, field.TypeInt64, value)
		_node.ConnectionEpoch = value
	}
	if value, ok := _c.mutation.Draining(); ok {
		_spec.SetField(conduitsession.FieldDraining, field.TypeBool, value)
		_node.Draining = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(conduitsession.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.ConnectedAt(); ok {
		_spec.SetField(conduitsession.FieldConnectedAt, field.TypeTime, value)
		_node.ConnectedAt = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(conduitsession.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if nodes := _c.mutation.RelayIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conduitsession.RelayTable,
			Columns: []string{conduitsession.RelayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayinstance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelayInstanceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConduitSession.Create().
//		SetPrincipalKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConduitSessionUpsert) {
//			SetPrincipalKind(v+v).
//		}).
//		Exec(ctx)
func (_c *ConduitSessionCreate) OnConflict(opts ...sql.ConflictOption) *ConduitSessionUpsertOne {
	_c.conflict = opts
	return &ConduitSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConduitSessionCreate) OnConflictColumns(columns ...string) *ConduitSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConduitSessionUpsertOne{
		create: _c,
	}
}

type (
	// ConduitSessionUpsertOne is the builder for "upsert"-ing
	//  one ConduitSession node.
	ConduitSessionUpsertOne struct {
		create *ConduitSessionCreate
	}

	// ConduitSessionUpsert is the "OnConflict" setter.
	ConduitSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetDraining sets the "draining" field.
func (u *ConduitSessionUpsert) SetDraining(v bool) *ConduitSessionUpsert {
	u.Set(conduitsession.FieldDraining, v)
	return u
}

// UpdateDraining sets the "draining" field to the value that was provided on create.
func (u *ConduitSessionUpsert) UpdateDraining() *ConduitSessionUpsert {
	u.SetExcluded(conduitsession.FieldDraining)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *ConduitSessionUpsert) SetCapabilities(v json.RawMessage) *ConduitSessionUpsert {
	u.Set(conduitsession.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ConduitSessionUpsert) UpdateCapabilities() *ConduitSessionUpsert {
	u.SetExcluded(conduitsession.FieldCapabilities)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *ConduitSessionUpsert) SetLastSeen(v time.Time) *ConduitSessionUpsert {
	u.Set(conduitsession.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *ConduitSessionUpsert) UpdateLastSeen() *ConduitSessionUpsert {
	u.SetExcluded(conduitsession.FieldLastSeen)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(conduitsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConduitSessionUpsertOne) UpdateNewValues() *ConduitSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(conduitsession.FieldID)
		}
		if _, exists := u.create.mutation.PrincipalKind(); exists {
			s.SetIgnore(conduitsession.FieldPrincipalKind)
		}
		if _, exists := u.create.mutation.PrincipalID(); exists {
			s.SetIgnore(conduitsession.FieldPrincipalID)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(conduitsession.FieldProjectID)
		}
		if _, exists := u.create.mutation.RelayInstanceID(); exists {
			s.SetIgnore(conduitsession.FieldRelayInstanceID)
		}
		if _, exists := u.create.mutation.RelayGeneration(); exists {
			s.SetIgnore(conduitsession.FieldRelayGeneration)
		}
		if _, exists := u.create.mutation.Transport(); exists {
			s.SetIgnore(conduitsession.FieldTransport)
		}
		if _, exists := u.create.mutation.EndpointIncarnation(); exists {
			s.SetIgnore(conduitsession.FieldEndpointIncarnation)
		}
		if _, exists := u.create.mutation.ExecScope(); exists {
			s.SetIgnore(conduitsession.FieldExecScope)
		}
		if _, exists := u.create.mutation.ConnectionEpoch(); exists {
			s.SetIgnore(conduitsession.FieldConnectionEpoch)
		}
		if _, exists := u.create.mutation.ConnectedAt(); exists {
			s.SetIgnore(conduitsession.FieldConnectedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConduitSessionUpsertOne) Ignore() *ConduitSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConduitSessionUpsertOne) DoNothing() *ConduitSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConduitSessionCreate.OnConflict
// documentation for more info.
func (u *ConduitSessionUpsertOne) Update(set func(*ConduitSessionUpsert)) *ConduitSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConduitSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDraining sets the "draining" field.
func (u *ConduitSessionUpsertOne) SetDraining(v bool) *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetDraining(v)
	})
}

// UpdateDraining sets the "draining" field to the value that was provided on create.
func (u *ConduitSessionUpsertOne) UpdateDraining() *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateDraining()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ConduitSessionUpsertOne) SetCapabilities(v json.RawMessage) *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ConduitSessionUpsertOne) UpdateCapabilities() *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateCapabilities()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *ConduitSessionUpsertOne) SetLastSeen(v time.Time) *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *ConduitSessionUpsertOne) UpdateLastSeen() *ConduitSessionUpsertOne {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateLastSeen()
	})
}

// Exec executes the query.
func (u *ConduitSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConduitSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConduitSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConduitSessionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ConduitSessionUpsertOne.ID is not supported by MySQL driver. Use ConduitSessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConduitSessionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConduitSessionCreateBulk is the builder for creating many ConduitSession entities in bulk.
type ConduitSessionCreateBulk struct {
	config
	err      error
	builders []*ConduitSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the ConduitSession entities in the database.
func (_c *ConduitSessionCreateBulk) Save(ctx context.Context) ([]*ConduitSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConduitSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConduitSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConduitSessionCreateBulk) SaveX(ctx context.Context) []*ConduitSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConduitSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConduitSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConduitSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConduitSessionUpsert) {
//			SetPrincipalKind(v+v).
//		}).
//		Exec(ctx)
func (_c *ConduitSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConduitSessionUpsertBulk {
	_c.conflict = opts
	return &ConduitSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConduitSessionCreateBulk) OnConflictColumns(columns ...string) *ConduitSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConduitSessionUpsertBulk{
		create: _c,
	}
}

// ConduitSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of ConduitSession nodes.
type ConduitSessionUpsertBulk struct {
	create *ConduitSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(conduitsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConduitSessionUpsertBulk) UpdateNewValues() *ConduitSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(conduitsession.FieldID)
			}
			if _, exists := b.mutation.PrincipalKind(); exists {
				s.SetIgnore(conduitsession.FieldPrincipalKind)
			}
			if _, exists := b.mutation.PrincipalID(); exists {
				s.SetIgnore(conduitsession.FieldPrincipalID)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(conduitsession.FieldProjectID)
			}
			if _, exists := b.mutation.RelayInstanceID(); exists {
				s.SetIgnore(conduitsession.FieldRelayInstanceID)
			}
			if _, exists := b.mutation.RelayGeneration(); exists {
				s.SetIgnore(conduitsession.FieldRelayGeneration)
			}
			if _, exists := b.mutation.Transport(); exists {
				s.SetIgnore(conduitsession.FieldTransport)
			}
			if _, exists := b.mutation.EndpointIncarnation(); exists {
				s.SetIgnore(conduitsession.FieldEndpointIncarnation)
			}
			if _, exists := b.mutation.ExecScope(); exists {
				s.SetIgnore(conduitsession.FieldExecScope)
			}
			if _, exists := b.mutation.ConnectionEpoch(); exists {
				s.SetIgnore(conduitsession.FieldConnectionEpoch)
			}
			if _, exists := b.mutation.ConnectedAt(); exists {
				s.SetIgnore(conduitsession.FieldConnectedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConduitSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConduitSessionUpsertBulk) Ignore() *ConduitSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConduitSessionUpsertBulk) DoNothing() *ConduitSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConduitSessionCreateBulk.OnConflict
// documentation for more info.
func (u *ConduitSessionUpsertBulk) Update(set func(*ConduitSessionUpsert)) *ConduitSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConduitSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDraining sets the "draining" field.
func (u *ConduitSessionUpsertBulk) SetDraining(v bool) *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetDraining(v)
	})
}

// UpdateDraining sets the "draining" field to the value that was provided on create.
func (u *ConduitSessionUpsertBulk) UpdateDraining() *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateDraining()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ConduitSessionUpsertBulk) SetCapabilities(v json.RawMessage) *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ConduitSessionUpsertBulk) UpdateCapabilities() *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateCapabilities()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *ConduitSessionUpsertBulk) SetLastSeen(v time.Time) *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *ConduitSessionUpsertBulk) UpdateLastSeen() *ConduitSessionUpsertBulk {
	return u.Update(func(s *ConduitSessionUpsert) {
		s.UpdateLastSeen()
	})
}

// Exec executes the query.
func (u *ConduitSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConduitSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConduitSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConduitSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
