// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/delegationadoption"
	"github.com/google/uuid"
)

// DelegationAdoptionCreate is the builder for creating a DelegationAdoption entity.
type DelegationAdoptionCreate struct {
	config
	mutation *DelegationAdoptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCohortID sets the "cohort_id" field.
func (_c *DelegationAdoptionCreate) SetCohortID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetCohortID(v)
	return _c
}

// SetOrigin sets the "origin" field.
func (_c *DelegationAdoptionCreate) SetOrigin(v string) *DelegationAdoptionCreate {
	_c.mutation.SetOrigin(v)
	return _c
}

// SetPolicyVersion sets the "policy_version" field.
func (_c *DelegationAdoptionCreate) SetPolicyVersion(v int) *DelegationAdoptionCreate {
	_c.mutation.SetPolicyVersion(v)
	return _c
}

// SetNillablePolicyVersion sets the "policy_version" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillablePolicyVersion(v *int) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetPolicyVersion(*v)
	}
	return _c
}

// SetOriginalEdgeID sets the "original_edge_id" field.
func (_c *DelegationAdoptionCreate) SetOriginalEdgeID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetOriginalEdgeID(v)
	return _c
}

// SetNillableOriginalEdgeID sets the "original_edge_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableOriginalEdgeID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetOriginalEdgeID(*v)
	}
	return _c
}

// SetAdoptedEdgeID sets the "adopted_edge_id" field.
func (_c *DelegationAdoptionCreate) SetAdoptedEdgeID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetAdoptedEdgeID(v)
	return _c
}

// SetNillableAdoptedEdgeID sets the "adopted_edge_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableAdoptedEdgeID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetAdoptedEdgeID(*v)
	}
	return _c
}

// SetDelegateID sets the "delegate_id" field.
func (_c *DelegationAdoptionCreate) SetDelegateID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetDelegateID(v)
	return _c
}

// SetNillableDelegateID sets the "delegate_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableDelegateID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetDelegateID(*v)
	}
	return _c
}

// SetDelegatorType sets the "delegator_type" field.
func (_c *DelegationAdoptionCreate) SetDelegatorType(v string) *DelegationAdoptionCreate {
	_c.mutation.SetDelegatorType(v)
	return _c
}

// SetNillableDelegatorType sets the "delegator_type" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableDelegatorType(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetDelegatorType(*v)
	}
	return _c
}

// SetDelegatorID sets the "delegator_id" field.
func (_c *DelegationAdoptionCreate) SetDelegatorID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetDelegatorID(v)
	return _c
}

// SetNillableDelegatorID sets the "delegator_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableDelegatorID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetDelegatorID(*v)
	}
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *DelegationAdoptionCreate) SetScopeID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableScopeID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *DelegationAdoptionCreate) SetRole(v string) *DelegationAdoptionCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableRole(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetDepth sets the "depth" field.
func (_c *DelegationAdoptionCreate) SetDepth(v int) *DelegationAdoptionCreate {
	_c.mutation.SetDepth(v)
	return _c
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableDepth(v *int) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetDepth(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DelegationAdoptionCreate) SetStatus(v string) *DelegationAdoptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *DelegationAdoptionCreate) SetReason(v string) *DelegationAdoptionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableReason(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetBeforeFingerprint sets the "before_fingerprint" field.
func (_c *DelegationAdoptionCreate) SetBeforeFingerprint(v string) *DelegationAdoptionCreate {
	_c.mutation.SetBeforeFingerprint(v)
	return _c
}

// SetNillableBeforeFingerprint sets the "before_fingerprint" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableBeforeFingerprint(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetBeforeFingerprint(*v)
	}
	return _c
}

// SetAfterSummary sets the "after_summary" field.
func (_c *DelegationAdoptionCreate) SetAfterSummary(v string) *DelegationAdoptionCreate {
	_c.mutation.SetAfterSummary(v)
	return _c
}

// SetNillableAfterSummary sets the "after_summary" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableAfterSummary(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetAfterSummary(*v)
	}
	return _c
}

// SetActorKind sets the "actor_kind" field.
func (_c *DelegationAdoptionCreate) SetActorKind(v string) *DelegationAdoptionCreate {
	_c.mutation.SetActorKind(v)
	return _c
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableActorKind(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetActorKind(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *DelegationAdoptionCreate) SetActorID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableActorID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetRevertedByKind sets the "reverted_by_kind" field.
func (_c *DelegationAdoptionCreate) SetRevertedByKind(v string) *DelegationAdoptionCreate {
	_c.mutation.SetRevertedByKind(v)
	return _c
}

// SetNillableRevertedByKind sets the "reverted_by_kind" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableRevertedByKind(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetRevertedByKind(*v)
	}
	return _c
}

// SetRevertedByID sets the "reverted_by_id" field.
func (_c *DelegationAdoptionCreate) SetRevertedByID(v string) *DelegationAdoptionCreate {
	_c.mutation.SetRevertedByID(v)
	return _c
}

// SetNillableRevertedByID sets the "reverted_by_id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableRevertedByID(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetRevertedByID(*v)
	}
	return _c
}

// SetRevertSummary sets the "revert_summary" field.
func (_c *DelegationAdoptionCreate) SetRevertSummary(v string) *DelegationAdoptionCreate {
	_c.mutation.SetRevertSummary(v)
	return _c
}

// SetNillableRevertSummary sets the "revert_summary" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableRevertSummary(v *string) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetRevertSummary(*v)
	}
	return _c
}

// SetRevertedAt sets the "reverted_at" field.
func (_c *DelegationAdoptionCreate) SetRevertedAt(v time.Time) *DelegationAdoptionCreate {
	_c.mutation.SetRevertedAt(v)
	return _c
}

// SetNillableRevertedAt sets the "reverted_at" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableRevertedAt(v *time.Time) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetRevertedAt(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *DelegationAdoptionCreate) SetCreated(v time.Time) *DelegationAdoptionCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableCreated(v *time.Time) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *DelegationAdoptionCreate) SetUpdated(v time.Time) *DelegationAdoptionCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableUpdated(v *time.Time) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DelegationAdoptionCreate) SetID(v uuid.UUID) *DelegationAdoptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DelegationAdoptionCreate) SetNillableID(v *uuid.UUID) *DelegationAdoptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DelegationAdoptionMutation object of the builder.
func (_c *DelegationAdoptionCreate) Mutation() *DelegationAdoptionMutation {
	return _c.mutation
}

// Save creates the DelegationAdoption in the database.
func (_c *DelegationAdoptionCreate) Save(ctx context.Context) (*DelegationAdoption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DelegationAdoptionCreate) SaveX(ctx context.Context) *DelegationAdoption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationAdoptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationAdoptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DelegationAdoptionCreate) defaults() {
	if _, ok := _c.mutation.PolicyVersion(); !ok {
		v := delegationadoption.DefaultPolicyVersion
		_c.mutation.SetPolicyVersion(v)
	}
	if _, ok := _c.mutation.DelegateID(); !ok {
		v := delegationadoption.DefaultDelegateID
		_c.mutation.SetDelegateID(v)
	}
	if _, ok := _c.mutation.DelegatorType(); !ok {
		v := delegationadoption.DefaultDelegatorType
		_c.mutation.SetDelegatorType(v)
	}
	if _, ok := _c.mutation.DelegatorID(); !ok {
		v := delegationadoption.DefaultDelegatorID
		_c.mutation.SetDelegatorID(v)
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		v := delegationadoption.DefaultScopeID
		_c.mutation.SetScopeID(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := delegationadoption.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Depth(); !ok {
		v := delegationadoption.DefaultDepth
		_c.mutation.SetDepth(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := delegationadoption.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.BeforeFingerprint(); !ok {
		v := delegationadoption.DefaultBeforeFingerprint
		_c.mutation.SetBeforeFingerprint(v)
	}
	if _, ok := _c.mutation.AfterSummary(); !ok {
		v := delegationadoption.DefaultAfterSummary
		_c.mutation.SetAfterSummary(v)
	}
	if _, ok := _c.mutation.ActorKind(); !ok {
		v := delegationadoption.DefaultActorKind
		_c.mutation.SetActorKind(v)
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		v := delegationadoption.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.RevertedByKind(); !ok {
		v := delegationadoption.DefaultRevertedByKind
		_c.mutation.SetRevertedByKind(v)
	}
	if _, ok := _c.mutation.RevertedByID(); !ok {
		v := delegationadoption.DefaultRevertedByID
		_c.mutation.SetRevertedByID(v)
	}
	if _, ok := _c.mutation.RevertSummary(); !ok {
		v := delegationadoption.DefaultRevertSummary
		_c.mutation.SetRevertSummary(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := delegationadoption.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := delegationadoption.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := delegationadoption.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DelegationAdoptionCreate) check() error {
	if _, ok := _c.mutation.CohortID(); !ok {
		return &ValidationError{Name: "cohort_id", err: errors.New(`ent: missing required field "DelegationAdoption.cohort_id"`)}
	}
	if v, ok := _c.mutation.CohortID(); ok {
		if err := delegationadoption.CohortIDValidator(v); err != nil {
			return &ValidationError{Name: "cohort_id", err: fmt.Errorf(`ent: validator failed for field "DelegationAdoption.cohort_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Origin(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required field "DelegationAdoption.origin"`)}
	}
	if v, ok := _c.mutation.Origin(); ok {
		if err := delegationadoption.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "DelegationAdoption.origin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PolicyVersion(); !ok {
		return &ValidationError{Name: "policy_version", err: errors.New(`ent: missing required field "DelegationAdoption.policy_version"`)}
	}
	if _, ok := _c.mutation.DelegateID(); !ok {
		return &ValidationError{Name: "delegate_id", err: errors.New(`ent: missing required field "DelegationAdoption.delegate_id"`)}
	}
	if _, ok := _c.mutation.DelegatorType(); !ok {
		return &ValidationError{Name: "delegator_type", err: errors.New(`ent: missing required field "DelegationAdoption.delegator_type"`)}
	}
	if _, ok := _c.mutation.DelegatorID(); !ok {
		return &ValidationError{Name: "delegator_id", err: errors.New(`ent: missing required field "DelegationAdoption.delegator_id"`)}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "DelegationAdoption.scope_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "DelegationAdoption.role"`)}
	}
	if _, ok := _c.mutation.Depth(); !ok {
		return &ValidationError{Name: "depth", err: errors.New(`ent: missing required field "DelegationAdoption.depth"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DelegationAdoption.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := delegationadoption.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DelegationAdoption.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "DelegationAdoption.reason"`)}
	}
	if _, ok := _c.mutation.BeforeFingerprint(); !ok {
		return &ValidationError{Name: "before_fingerprint", err: errors.New(`ent: missing required field "DelegationAdoption.before_fingerprint"`)}
	}
	if _, ok := _c.mutation.AfterSummary(); !ok {
		return &ValidationError{Name: "after_summary", err: errors.New(`ent: missing required field "DelegationAdoption.after_summary"`)}
	}
	if _, ok := _c.mutation.ActorKind(); !ok {
		return &ValidationError{Name: "actor_kind", err: errors.New(`ent: missing required field "DelegationAdoption.actor_kind"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "DelegationAdoption.actor_id"`)}
	}
	if _, ok := _c.mutation.RevertedByKind(); !ok {
		return &ValidationError{Name: "reverted_by_kind", err: errors.New(`ent: missing required field "DelegationAdoption.reverted_by_kind"`)}
	}
	if _, ok := _c.mutation.RevertedByID(); !ok {
		return &ValidationError{Name: "reverted_by_id", err: errors.New(`ent: missing required field "DelegationAdoption.reverted_by_id"`)}
	}
	if _, ok := _c.mutation.RevertSummary(); !ok {
		return &ValidationError{Name: "revert_summary", err: errors.New(`ent: missing required field "DelegationAdoption.revert_summary"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "DelegationAdoption.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "DelegationAdoption.updated"`)}
	}
	return nil
}

func (_c *DelegationAdoptionCreate) sqlSave(ctx context.Context) (*DelegationAdoption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DelegationAdoptionCreate) createSpec() (*DelegationAdoption, *sqlgraph.CreateSpec) {
	var (
		_node = &DelegationAdoption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(delegationadoption.Table, sqlgraph.NewFieldSpec(delegationadoption.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CohortID(); ok {
		_spec.SetField(delegationadoption.FieldCohortID, field.TypeString, value)
		_node.CohortID = value
	}
	if value, ok := _c.mutation.Origin(); ok {
		_spec.SetField(delegationadoption.FieldOrigin, field.TypeString, value)
		_node.Origin = value
	}
	if value, ok := _c.mutation.PolicyVersion(); ok {
		_spec.SetField(delegationadoption.FieldPolicyVersion, field.TypeInt, value)
		_node.PolicyVersion = value
	}
	if value, ok := _c.mutation.OriginalEdgeID(); ok {
		_spec.SetField(delegationadoption.FieldOriginalEdgeID, field.TypeString, value)
		_node.OriginalEdgeID = &value
	}
	if value, ok := _c.mutation.AdoptedEdgeID(); ok {
		_spec.SetField(delegationadoption.FieldAdoptedEdgeID, field.TypeString, value)
		_node.AdoptedEdgeID = &value
	}
	if value, ok := _c.mutation.DelegateID(); ok {
		_spec.SetField(delegationadoption.FieldDelegateID, field.TypeString, value)
		_node.DelegateID = value
	}
	if value, ok := _c.mutation.DelegatorType(); ok {
		_spec.SetField(delegationadoption.FieldDelegatorType, field.TypeString, value)
		_node.DelegatorType = value
	}
	if value, ok := _c.mutation.DelegatorID(); ok {
		_spec.SetField(delegationadoption.FieldDelegatorID, field.TypeString, value)
		_node.DelegatorID = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(delegationadoption.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(delegationadoption.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Depth(); ok {
		_spec.SetField(delegationadoption.FieldDepth, field.TypeInt, value)
		_node.Depth = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(delegationadoption.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(delegationadoption.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.BeforeFingerprint(); ok {
		_spec.SetField(delegationadoption.FieldBeforeFingerprint, field.TypeString, value)
		_node.BeforeFingerprint = value
	}
	if value, ok := _c.mutation.AfterSummary(); ok {
		_spec.SetField(delegationadoption.FieldAfterSummary, field.TypeString, value)
		_node.AfterSummary = value
	}
	if value, ok := _c.mutation.ActorKind(); ok {
		_spec.SetField(delegationadoption.FieldActorKind, field.TypeString, value)
		_node.ActorKind = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(delegationadoption.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.RevertedByKind(); ok {
		_spec.SetField(delegationadoption.FieldRevertedByKind, field.TypeString, value)
		_node.RevertedByKind = value
	}
	if value, ok := _c.mutation.RevertedByID(); ok {
		_spec.SetField(delegationadoption.FieldRevertedByID, field.TypeString, value)
		_node.RevertedByID = value
	}
	if value, ok := _c.mutation.RevertSummary(); ok {
		_spec.SetField(delegationadoption.FieldRevertSummary, field.TypeString, value)
		_node.RevertSummary = value
	}
	if value, ok := _c.mutation.RevertedAt(); ok {
		_spec.SetField(delegationadoption.FieldRevertedAt, field.TypeTime, value)
		_node.RevertedAt = &value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(delegationadoption.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(delegationadoption.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DelegationAdoption.Create().
//		SetCohortID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DelegationAdoptionUpsert) {
//			SetCohortID(v+v).
//		}).
//		Exec(ctx)
func (_c *DelegationAdoptionCreate) OnConflict(opts ...sql.ConflictOption) *DelegationAdoptionUpsertOne {
	_c.conflict = opts
	return &DelegationAdoptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DelegationAdoptionCreate) OnConflictColumns(columns ...string) *DelegationAdoptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DelegationAdoptionUpsertOne{
		create: _c,
	}
}

type (
	// DelegationAdoptionUpsertOne is the builder for "upsert"-ing
	//  one DelegationAdoption node.
	DelegationAdoptionUpsertOne struct {
		create *DelegationAdoptionCreate
	}

	// DelegationAdoptionUpsert is the "OnConflict" setter.
	DelegationAdoptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCohortID sets the "cohort_id" field.
func (u *DelegationAdoptionUpsert) SetCohortID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldCohortID, v)
	return u
}

// UpdateCohortID sets the "cohort_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateCohortID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldCohortID)
	return u
}

// SetOrigin sets the "origin" field.
func (u *DelegationAdoptionUpsert) SetOrigin(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldOrigin, v)
	return u
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateOrigin() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldOrigin)
	return u
}

// SetPolicyVersion sets the "policy_version" field.
func (u *DelegationAdoptionUpsert) SetPolicyVersion(v int) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldPolicyVersion, v)
	return u
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdatePolicyVersion() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldPolicyVersion)
	return u
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *DelegationAdoptionUpsert) AddPolicyVersion(v int) *DelegationAdoptionUpsert {
	u.Add(delegationadoption.FieldPolicyVersion, v)
	return u
}

// SetOriginalEdgeID sets the "original_edge_id" field.
func (u *DelegationAdoptionUpsert) SetOriginalEdgeID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldOriginalEdgeID, v)
	return u
}

// UpdateOriginalEdgeID sets the "original_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateOriginalEdgeID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldOriginalEdgeID)
	return u
}

// ClearOriginalEdgeID clears the value of the "original_edge_id" field.
func (u *DelegationAdoptionUpsert) ClearOriginalEdgeID() *DelegationAdoptionUpsert {
	u.SetNull(delegationadoption.FieldOriginalEdgeID)
	return u
}

// SetAdoptedEdgeID sets the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsert) SetAdoptedEdgeID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldAdoptedEdgeID, v)
	return u
}

// UpdateAdoptedEdgeID sets the "adopted_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateAdoptedEdgeID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldAdoptedEdgeID)
	return u
}

// ClearAdoptedEdgeID clears the value of the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsert) ClearAdoptedEdgeID() *DelegationAdoptionUpsert {
	u.SetNull(delegationadoption.FieldAdoptedEdgeID)
	return u
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationAdoptionUpsert) SetDelegateID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldDelegateID, v)
	return u
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateDelegateID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldDelegateID)
	return u
}

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationAdoptionUpsert) SetDelegatorType(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldDelegatorType, v)
	return u
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateDelegatorType() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldDelegatorType)
	return u
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationAdoptionUpsert) SetDelegatorID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldDelegatorID, v)
	return u
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateDelegatorID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldDelegatorID)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationAdoptionUpsert) SetScopeID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateScopeID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldScopeID)
	return u
}

// SetRole sets the "role" field.
func (u *DelegationAdoptionUpsert) SetRole(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateRole() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldRole)
	return u
}

// SetDepth sets the "depth" field.
func (u *DelegationAdoptionUpsert) SetDepth(v int) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldDepth, v)
	return u
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateDepth() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldDepth)
	return u
}

// AddDepth adds v to the "depth" field.
func (u *DelegationAdoptionUpsert) AddDepth(v int) *DelegationAdoptionUpsert {
	u.Add(delegationadoption.FieldDepth, v)
	return u
}

// SetStatus sets the "status" field.
func (u *DelegationAdoptionUpsert) SetStatus(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateStatus() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *DelegationAdoptionUpsert) SetReason(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateReason() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldReason)
	return u
}

// SetBeforeFingerprint sets the "before_fingerprint" field.
func (u *DelegationAdoptionUpsert) SetBeforeFingerprint(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldBeforeFingerprint, v)
	return u
}

// UpdateBeforeFingerprint sets the "before_fingerprint" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateBeforeFingerprint() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldBeforeFingerprint)
	return u
}

// SetAfterSummary sets the "after_summary" field.
func (u *DelegationAdoptionUpsert) SetAfterSummary(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldAfterSummary, v)
	return u
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateAfterSummary() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldAfterSummary)
	return u
}

// SetActorKind sets the "actor_kind" field.
func (u *DelegationAdoptionUpsert) SetActorKind(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldActorKind, v)
	return u
}

// UpdateActorKind sets the "actor_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateActorKind() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldActorKind)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *DelegationAdoptionUpsert) SetActorID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateActorID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldActorID)
	return u
}

// SetRevertedByKind sets the "reverted_by_kind" field.
func (u *DelegationAdoptionUpsert) SetRevertedByKind(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldRevertedByKind, v)
	return u
}

// UpdateRevertedByKind sets the "reverted_by_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateRevertedByKind() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldRevertedByKind)
	return u
}

// SetRevertedByID sets the "reverted_by_id" field.
func (u *DelegationAdoptionUpsert) SetRevertedByID(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldRevertedByID, v)
	return u
}

// UpdateRevertedByID sets the "reverted_by_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateRevertedByID() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldRevertedByID)
	return u
}

// SetRevertSummary sets the "revert_summary" field.
func (u *DelegationAdoptionUpsert) SetRevertSummary(v string) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldRevertSummary, v)
	return u
}

// UpdateRevertSummary sets the "revert_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateRevertSummary() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldRevertSummary)
	return u
}

// SetRevertedAt sets the "reverted_at" field.
func (u *DelegationAdoptionUpsert) SetRevertedAt(v time.Time) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldRevertedAt, v)
	return u
}

// UpdateRevertedAt sets the "reverted_at" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateRevertedAt() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldRevertedAt)
	return u
}

// ClearRevertedAt clears the value of the "reverted_at" field.
func (u *DelegationAdoptionUpsert) ClearRevertedAt() *DelegationAdoptionUpsert {
	u.SetNull(delegationadoption.FieldRevertedAt)
	return u
}

// SetUpdated sets the "updated" field.
func (u *DelegationAdoptionUpsert) SetUpdated(v time.Time) *DelegationAdoptionUpsert {
	u.Set(delegationadoption.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationAdoptionUpsert) UpdateUpdated() *DelegationAdoptionUpsert {
	u.SetExcluded(delegationadoption.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(delegationadoption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DelegationAdoptionUpsertOne) UpdateNewValues() *DelegationAdoptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(delegationadoption.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(delegationadoption.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DelegationAdoptionUpsertOne) Ignore() *DelegationAdoptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DelegationAdoptionUpsertOne) DoNothing() *DelegationAdoptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DelegationAdoptionCreate.OnConflict
// documentation for more info.
func (u *DelegationAdoptionUpsertOne) Update(set func(*DelegationAdoptionUpsert)) *DelegationAdoptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DelegationAdoptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCohortID sets the "cohort_id" field.
func (u *DelegationAdoptionUpsertOne) SetCohortID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetCohortID(v)
	})
}

// UpdateCohortID sets the "cohort_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateCohortID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateCohortID()
	})
}

// SetOrigin sets the "origin" field.
func (u *DelegationAdoptionUpsertOne) SetOrigin(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateOrigin() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateOrigin()
	})
}

// SetPolicyVersion sets the "policy_version" field.
func (u *DelegationAdoptionUpsertOne) SetPolicyVersion(v int) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetPolicyVersion(v)
	})
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *DelegationAdoptionUpsertOne) AddPolicyVersion(v int) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.AddPolicyVersion(v)
	})
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdatePolicyVersion() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdatePolicyVersion()
	})
}

// SetOriginalEdgeID sets the "original_edge_id" field.
func (u *DelegationAdoptionUpsertOne) SetOriginalEdgeID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetOriginalEdgeID(v)
	})
}

// UpdateOriginalEdgeID sets the "original_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateOriginalEdgeID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateOriginalEdgeID()
	})
}

// ClearOriginalEdgeID clears the value of the "original_edge_id" field.
func (u *DelegationAdoptionUpsertOne) ClearOriginalEdgeID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearOriginalEdgeID()
	})
}

// SetAdoptedEdgeID sets the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsertOne) SetAdoptedEdgeID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetAdoptedEdgeID(v)
	})
}

// UpdateAdoptedEdgeID sets the "adopted_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateAdoptedEdgeID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateAdoptedEdgeID()
	})
}

// ClearAdoptedEdgeID clears the value of the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsertOne) ClearAdoptedEdgeID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearAdoptedEdgeID()
	})
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationAdoptionUpsertOne) SetDelegateID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegateID(v)
	})
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateDelegateID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegateID()
	})
}

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationAdoptionUpsertOne) SetDelegatorType(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegatorType(v)
	})
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateDelegatorType() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegatorType()
	})
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationAdoptionUpsertOne) SetDelegatorID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegatorID(v)
	})
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateDelegatorID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegatorID()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationAdoptionUpsertOne) SetScopeID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateScopeID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateScopeID()
	})
}

// SetRole sets the "role" field.
func (u *DelegationAdoptionUpsertOne) SetRole(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateRole() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRole()
	})
}

// SetDepth sets the "depth" field.
func (u *DelegationAdoptionUpsertOne) SetDepth(v int) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *DelegationAdoptionUpsertOne) AddDepth(v int) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateDepth() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDepth()
	})
}

// SetStatus sets the "status" field.
func (u *DelegationAdoptionUpsertOne) SetStatus(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateStatus() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *DelegationAdoptionUpsertOne) SetReason(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateReason() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateReason()
	})
}

// SetBeforeFingerprint sets the "before_fingerprint" field.
func (u *DelegationAdoptionUpsertOne) SetBeforeFingerprint(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetBeforeFingerprint(v)
	})
}

// UpdateBeforeFingerprint sets the "before_fingerprint" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateBeforeFingerprint() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateBeforeFingerprint()
	})
}

// SetAfterSummary sets the "after_summary" field.
func (u *DelegationAdoptionUpsertOne) SetAfterSummary(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetAfterSummary(v)
	})
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateAfterSummary() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateAfterSummary()
	})
}

// SetActorKind sets the "actor_kind" field.
func (u *DelegationAdoptionUpsertOne) SetActorKind(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetActorKind(v)
	})
}

// UpdateActorKind sets the "actor_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateActorKind() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateActorKind()
	})
}

// SetActorID sets the "actor_id" field.
func (u *DelegationAdoptionUpsertOne) SetActorID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateActorID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateActorID()
	})
}

// SetRevertedByKind sets the "reverted_by_kind" field.
func (u *DelegationAdoptionUpsertOne) SetRevertedByKind(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedByKind(v)
	})
}

// UpdateRevertedByKind sets the "reverted_by_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateRevertedByKind() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedByKind()
	})
}

// SetRevertedByID sets the "reverted_by_id" field.
func (u *DelegationAdoptionUpsertOne) SetRevertedByID(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedByID(v)
	})
}

// UpdateRevertedByID sets the "reverted_by_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateRevertedByID() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedByID()
	})
}

// SetRevertSummary sets the "revert_summary" field.
func (u *DelegationAdoptionUpsertOne) SetRevertSummary(v string) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertSummary(v)
	})
}

// UpdateRevertSummary sets the "revert_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateRevertSummary() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertSummary()
	})
}

// SetRevertedAt sets the "reverted_at" field.
func (u *DelegationAdoptionUpsertOne) SetRevertedAt(v time.Time) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedAt(v)
	})
}

// UpdateRevertedAt sets the "reverted_at" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateRevertedAt() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedAt()
	})
}

// ClearRevertedAt clears the value of the "reverted_at" field.
func (u *DelegationAdoptionUpsertOne) ClearRevertedAt() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearRevertedAt()
	})
}

// SetUpdated sets the "updated" field.
func (u *DelegationAdoptionUpsertOne) SetUpdated(v time.Time) *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertOne) UpdateUpdated() *DelegationAdoptionUpsertOne {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *DelegationAdoptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DelegationAdoptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DelegationAdoptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DelegationAdoptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DelegationAdoptionUpsertOne.ID is not supported by MySQL driver. Use DelegationAdoptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DelegationAdoptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DelegationAdoptionCreateBulk is the builder for creating many DelegationAdoption entities in bulk.
type DelegationAdoptionCreateBulk struct {
	config
	err      error
	builders []*DelegationAdoptionCreate
	conflict []sql.ConflictOption
}

// Save creates the DelegationAdoption entities in the database.
func (_c *DelegationAdoptionCreateBulk) Save(ctx context.Context) ([]*DelegationAdoption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DelegationAdoption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DelegationAdoptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DelegationAdoptionCreateBulk) SaveX(ctx context.Context) []*DelegationAdoption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationAdoptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationAdoptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DelegationAdoption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DelegationAdoptionUpsert) {
//			SetCohortID(v+v).
//		}).
//		Exec(ctx)
func (_c *DelegationAdoptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *DelegationAdoptionUpsertBulk {
	_c.conflict = opts
	return &DelegationAdoptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DelegationAdoptionCreateBulk) OnConflictColumns(columns ...string) *DelegationAdoptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DelegationAdoptionUpsertBulk{
		create: _c,
	}
}

// DelegationAdoptionUpsertBulk is the builder for "upsert"-ing
// a bulk of DelegationAdoption nodes.
type DelegationAdoptionUpsertBulk struct {
	create *DelegationAdoptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(delegationadoption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DelegationAdoptionUpsertBulk) UpdateNewValues() *DelegationAdoptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(delegationadoption.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(delegationadoption.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DelegationAdoption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DelegationAdoptionUpsertBulk) Ignore() *DelegationAdoptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DelegationAdoptionUpsertBulk) DoNothing() *DelegationAdoptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DelegationAdoptionCreateBulk.OnConflict
// documentation for more info.
func (u *DelegationAdoptionUpsertBulk) Update(set func(*DelegationAdoptionUpsert)) *DelegationAdoptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DelegationAdoptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCohortID sets the "cohort_id" field.
func (u *DelegationAdoptionUpsertBulk) SetCohortID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetCohortID(v)
	})
}

// UpdateCohortID sets the "cohort_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateCohortID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateCohortID()
	})
}

// SetOrigin sets the "origin" field.
func (u *DelegationAdoptionUpsertBulk) SetOrigin(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateOrigin() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateOrigin()
	})
}

// SetPolicyVersion sets the "policy_version" field.
func (u *DelegationAdoptionUpsertBulk) SetPolicyVersion(v int) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetPolicyVersion(v)
	})
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *DelegationAdoptionUpsertBulk) AddPolicyVersion(v int) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.AddPolicyVersion(v)
	})
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdatePolicyVersion() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdatePolicyVersion()
	})
}

// SetOriginalEdgeID sets the "original_edge_id" field.
func (u *DelegationAdoptionUpsertBulk) SetOriginalEdgeID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetOriginalEdgeID(v)
	})
}

// UpdateOriginalEdgeID sets the "original_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateOriginalEdgeID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateOriginalEdgeID()
	})
}

// ClearOriginalEdgeID clears the value of the "original_edge_id" field.
func (u *DelegationAdoptionUpsertBulk) ClearOriginalEdgeID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearOriginalEdgeID()
	})
}

// SetAdoptedEdgeID sets the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsertBulk) SetAdoptedEdgeID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetAdoptedEdgeID(v)
	})
}

// UpdateAdoptedEdgeID sets the "adopted_edge_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateAdoptedEdgeID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateAdoptedEdgeID()
	})
}

// ClearAdoptedEdgeID clears the value of the "adopted_edge_id" field.
func (u *DelegationAdoptionUpsertBulk) ClearAdoptedEdgeID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearAdoptedEdgeID()
	})
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationAdoptionUpsertBulk) SetDelegateID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegateID(v)
	})
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateDelegateID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegateID()
	})
}

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationAdoptionUpsertBulk) SetDelegatorType(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegatorType(v)
	})
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateDelegatorType() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegatorType()
	})
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationAdoptionUpsertBulk) SetDelegatorID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDelegatorID(v)
	})
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateDelegatorID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDelegatorID()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationAdoptionUpsertBulk) SetScopeID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateScopeID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateScopeID()
	})
}

// SetRole sets the "role" field.
func (u *DelegationAdoptionUpsertBulk) SetRole(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateRole() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRole()
	})
}

// SetDepth sets the "depth" field.
func (u *DelegationAdoptionUpsertBulk) SetDepth(v int) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *DelegationAdoptionUpsertBulk) AddDepth(v int) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateDepth() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateDepth()
	})
}

// SetStatus sets the "status" field.
func (u *DelegationAdoptionUpsertBulk) SetStatus(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateStatus() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *DelegationAdoptionUpsertBulk) SetReason(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateReason() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateReason()
	})
}

// SetBeforeFingerprint sets the "before_fingerprint" field.
func (u *DelegationAdoptionUpsertBulk) SetBeforeFingerprint(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetBeforeFingerprint(v)
	})
}

// UpdateBeforeFingerprint sets the "before_fingerprint" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateBeforeFingerprint() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateBeforeFingerprint()
	})
}

// SetAfterSummary sets the "after_summary" field.
func (u *DelegationAdoptionUpsertBulk) SetAfterSummary(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetAfterSummary(v)
	})
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateAfterSummary() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateAfterSummary()
	})
}

// SetActorKind sets the "actor_kind" field.
func (u *DelegationAdoptionUpsertBulk) SetActorKind(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetActorKind(v)
	})
}

// UpdateActorKind sets the "actor_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateActorKind() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateActorKind()
	})
}

// SetActorID sets the "actor_id" field.
func (u *DelegationAdoptionUpsertBulk) SetActorID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateActorID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateActorID()
	})
}

// SetRevertedByKind sets the "reverted_by_kind" field.
func (u *DelegationAdoptionUpsertBulk) SetRevertedByKind(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedByKind(v)
	})
}

// UpdateRevertedByKind sets the "reverted_by_kind" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateRevertedByKind() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedByKind()
	})
}

// SetRevertedByID sets the "reverted_by_id" field.
func (u *DelegationAdoptionUpsertBulk) SetRevertedByID(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedByID(v)
	})
}

// UpdateRevertedByID sets the "reverted_by_id" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateRevertedByID() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedByID()
	})
}

// SetRevertSummary sets the "revert_summary" field.
func (u *DelegationAdoptionUpsertBulk) SetRevertSummary(v string) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertSummary(v)
	})
}

// UpdateRevertSummary sets the "revert_summary" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateRevertSummary() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertSummary()
	})
}

// SetRevertedAt sets the "reverted_at" field.
func (u *DelegationAdoptionUpsertBulk) SetRevertedAt(v time.Time) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetRevertedAt(v)
	})
}

// UpdateRevertedAt sets the "reverted_at" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateRevertedAt() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateRevertedAt()
	})
}

// ClearRevertedAt clears the value of the "reverted_at" field.
func (u *DelegationAdoptionUpsertBulk) ClearRevertedAt() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.ClearRevertedAt()
	})
}

// SetUpdated sets the "updated" field.
func (u *DelegationAdoptionUpsertBulk) SetUpdated(v time.Time) *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationAdoptionUpsertBulk) UpdateUpdated() *DelegationAdoptionUpsertBulk {
	return u.Update(func(s *DelegationAdoptionUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *DelegationAdoptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DelegationAdoptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DelegationAdoptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DelegationAdoptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
