// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/delegationadoption"
	"github.com/google/uuid"
)

// DelegationAdoption is the model entity for the DelegationAdoption schema.
type DelegationAdoption struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CohortID holds the value of the "cohort_id" field.
	CohortID string `json:"cohort_id,omitempty"`
	// Origin holds the value of the "origin" field.
	Origin string `json:"origin,omitempty"`
	// PolicyVersion holds the value of the "policy_version" field.
	PolicyVersion int `json:"policy_version,omitempty"`
	// OriginalEdgeID holds the value of the "original_edge_id" field.
	OriginalEdgeID *string `json:"original_edge_id,omitempty"`
	// AdoptedEdgeID holds the value of the "adopted_edge_id" field.
	AdoptedEdgeID *string `json:"adopted_edge_id,omitempty"`
	// DelegateID holds the value of the "delegate_id" field.
	DelegateID string `json:"delegate_id,omitempty"`
	// DelegatorType holds the value of the "delegator_type" field.
	DelegatorType string `json:"delegator_type,omitempty"`
	// DelegatorID holds the value of the "delegator_id" field.
	DelegatorID string `json:"delegator_id,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Depth holds the value of the "depth" field.
	Depth int `json:"depth,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// BeforeFingerprint holds the value of the "before_fingerprint" field.
	BeforeFingerprint string `json:"before_fingerprint,omitempty"`
	// AfterSummary holds the value of the "after_summary" field.
	AfterSummary string `json:"after_summary,omitempty"`
	// ActorKind holds the value of the "actor_kind" field.
	ActorKind string `json:"actor_kind,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID string `json:"actor_id,omitempty"`
	// RevertedByKind holds the value of the "reverted_by_kind" field.
	RevertedByKind string `json:"reverted_by_kind,omitempty"`
	// RevertedByID holds the value of the "reverted_by_id" field.
	RevertedByID string `json:"reverted_by_id,omitempty"`
	// RevertSummary holds the value of the "revert_summary" field.
	RevertSummary string `json:"revert_summary,omitempty"`
	// RevertedAt holds the value of the "reverted_at" field.
	RevertedAt *time.Time `json:"reverted_at,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Updated holds the value of the "updated" field.
	Updated      time.Time `json:"updated,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DelegationAdoption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case delegationadoption.FieldPolicyVersion, delegationadoption.FieldDepth:
			values[i] = new(sql.NullInt64)
		case delegationadoption.FieldCohortID, delegationadoption.FieldOrigin, delegationadoption.FieldOriginalEdgeID, delegationadoption.FieldAdoptedEdgeID, delegationadoption.FieldDelegateID, delegationadoption.FieldDelegatorType, delegationadoption.FieldDelegatorID, delegationadoption.FieldScopeID, delegationadoption.FieldRole, delegationadoption.FieldStatus, delegationadoption.FieldReason, delegationadoption.FieldBeforeFingerprint, delegationadoption.FieldAfterSummary, delegationadoption.FieldActorKind, delegationadoption.FieldActorID, delegationadoption.FieldRevertedByKind, delegationadoption.FieldRevertedByID, delegationadoption.FieldRevertSummary:
			values[i] = new(sql.NullString)
		case delegationadoption.FieldRevertedAt, delegationadoption.FieldCreated, delegationadoption.FieldUpdated:
			values[i] = new(sql.NullTime)
		case delegationadoption.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DelegationAdoption fields.
func (_m *DelegationAdoption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case delegationadoption.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case delegationadoption.FieldCohortID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cohort_id", values[i])
			} else if value.Valid {
				_m.CohortID = value.String
			}
		case delegationadoption.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				_m.Origin = value.String
			}
		case delegationadoption.FieldPolicyVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_version", values[i])
			} else if value.Valid {
				_m.PolicyVersion = int(value.Int64)
			}
		case delegationadoption.FieldOriginalEdgeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_edge_id", values[i])
			} else if value.Valid {
				_m.OriginalEdgeID = new(string)
				*_m.OriginalEdgeID = value.String
			}
		case delegationadoption.FieldAdoptedEdgeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adopted_edge_id", values[i])
			} else if value.Valid {
				_m.AdoptedEdgeID = new(string)
				*_m.AdoptedEdgeID = value.String
			}
		case delegationadoption.FieldDelegateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delegate_id", values[i])
			} else if value.Valid {
				_m.DelegateID = value.String
			}
		case delegationadoption.FieldDelegatorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delegator_type", values[i])
			} else if value.Valid {
				_m.DelegatorType = value.String
			}
		case delegationadoption.FieldDelegatorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delegator_id", values[i])
			} else if value.Valid {
				_m.DelegatorID = value.String
			}
		case delegationadoption.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case delegationadoption.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case delegationadoption.FieldDepth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field depth", values[i])
			} else if value.Valid {
				_m.Depth = int(value.Int64)
			}
		case delegationadoption.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case delegationadoption.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case delegationadoption.FieldBeforeFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field before_fingerprint", values[i])
			} else if value.Valid {
				_m.BeforeFingerprint = value.String
			}
		case delegationadoption.FieldAfterSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field after_summary", values[i])
			} else if value.Valid {
				_m.AfterSummary = value.String
			}
		case delegationadoption.FieldActorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_kind", values[i])
			} else if value.Valid {
				_m.ActorKind = value.String
			}
		case delegationadoption.FieldActorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.String
			}
		case delegationadoption.FieldRevertedByKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reverted_by_kind", values[i])
			} else if value.Valid {
				_m.RevertedByKind = value.String
			}
		case delegationadoption.FieldRevertedByID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reverted_by_id", values[i])
			} else if value.Valid {
				_m.RevertedByID = value.String
			}
		case delegationadoption.FieldRevertSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revert_summary", values[i])
			} else if value.Valid {
				_m.RevertSummary = value.String
			}
		case delegationadoption.FieldRevertedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reverted_at", values[i])
			} else if value.Valid {
				_m.RevertedAt = new(time.Time)
				*_m.RevertedAt = value.Time
			}
		case delegationadoption.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case delegationadoption.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				_m.Updated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DelegationAdoption.
// This includes values selected through modifiers, order, etc.
func (_m *DelegationAdoption) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DelegationAdoption.
// Note that you need to call DelegationAdoption.Unwrap() before calling this method if this DelegationAdoption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DelegationAdoption) Update() *DelegationAdoptionUpdateOne {
	return NewDelegationAdoptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DelegationAdoption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DelegationAdoption) Unwrap() *DelegationAdoption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DelegationAdoption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DelegationAdoption) String() string {
	var builder strings.Builder
	builder.WriteString("DelegationAdoption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cohort_id=")
	builder.WriteString(_m.CohortID)
	builder.WriteString(", ")
	builder.WriteString("origin=")
	builder.WriteString(_m.Origin)
	builder.WriteString(", ")
	builder.WriteString("policy_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyVersion))
	builder.WriteString(", ")
	if v := _m.OriginalEdgeID; v != nil {
		builder.WriteString("original_edge_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AdoptedEdgeID; v != nil {
		builder.WriteString("adopted_edge_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("delegate_id=")
	builder.WriteString(_m.DelegateID)
	builder.WriteString(", ")
	builder.WriteString("delegator_type=")
	builder.WriteString(_m.DelegatorType)
	builder.WriteString(", ")
	builder.WriteString("delegator_id=")
	builder.WriteString(_m.DelegatorID)
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("depth=")
	builder.WriteString(fmt.Sprintf("%v", _m.Depth))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("before_fingerprint=")
	builder.WriteString(_m.BeforeFingerprint)
	builder.WriteString(", ")
	builder.WriteString("after_summary=")
	builder.WriteString(_m.AfterSummary)
	builder.WriteString(", ")
	builder.WriteString("actor_kind=")
	builder.WriteString(_m.ActorKind)
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(_m.ActorID)
	builder.WriteString(", ")
	builder.WriteString("reverted_by_kind=")
	builder.WriteString(_m.RevertedByKind)
	builder.WriteString(", ")
	builder.WriteString("reverted_by_id=")
	builder.WriteString(_m.RevertedByID)
	builder.WriteString(", ")
	builder.WriteString("revert_summary=")
	builder.WriteString(_m.RevertSummary)
	builder.WriteString(", ")
	if v := _m.RevertedAt; v != nil {
		builder.WriteString("reverted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(_m.Updated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DelegationAdoptions is a parsable slice of DelegationAdoption.
type DelegationAdoptions []*DelegationAdoption
