// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/delegationedge"
	"github.com/google/uuid"
)

// DelegationEdgeCreate is the builder for creating a DelegationEdge entity.
type DelegationEdgeCreate struct {
	config
	mutation *DelegationEdgeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDelegatorType sets the "delegator_type" field.
func (_c *DelegationEdgeCreate) SetDelegatorType(v delegationedge.DelegatorType) *DelegationEdgeCreate {
	_c.mutation.SetDelegatorType(v)
	return _c
}

// SetDelegatorID sets the "delegator_id" field.
func (_c *DelegationEdgeCreate) SetDelegatorID(v string) *DelegationEdgeCreate {
	_c.mutation.SetDelegatorID(v)
	return _c
}

// SetDelegateType sets the "delegate_type" field.
func (_c *DelegationEdgeCreate) SetDelegateType(v delegationedge.DelegateType) *DelegationEdgeCreate {
	_c.mutation.SetDelegateType(v)
	return _c
}

// SetDelegateID sets the "delegate_id" field.
func (_c *DelegationEdgeCreate) SetDelegateID(v string) *DelegationEdgeCreate {
	_c.mutation.SetDelegateID(v)
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *DelegationEdgeCreate) SetScopeType(v delegationedge.ScopeType) *DelegationEdgeCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *DelegationEdgeCreate) SetScopeID(v string) *DelegationEdgeCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableScopeID(v *string) *DelegationEdgeCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *DelegationEdgeCreate) SetRole(v string) *DelegationEdgeCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *DelegationEdgeCreate) SetActive(v bool) *DelegationEdgeCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableActive(v *bool) *DelegationEdgeCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetGrandfathered sets the "grandfathered" field.
func (_c *DelegationEdgeCreate) SetGrandfathered(v bool) *DelegationEdgeCreate {
	_c.mutation.SetGrandfathered(v)
	return _c
}

// SetNillableGrandfathered sets the "grandfathered" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableGrandfathered(v *bool) *DelegationEdgeCreate {
	if v != nil {
		_c.SetGrandfathered(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *DelegationEdgeCreate) SetCreated(v time.Time) *DelegationEdgeCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableCreated(v *time.Time) *DelegationEdgeCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *DelegationEdgeCreate) SetUpdated(v time.Time) *DelegationEdgeCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableUpdated(v *time.Time) *DelegationEdgeCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DelegationEdgeCreate) SetID(v uuid.UUID) *DelegationEdgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DelegationEdgeCreate) SetNillableID(v *uuid.UUID) *DelegationEdgeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DelegationEdgeMutation object of the builder.
func (_c *DelegationEdgeCreate) Mutation() *DelegationEdgeMutation {
	return _c.mutation
}

// Save creates the DelegationEdge in the database.
func (_c *DelegationEdgeCreate) Save(ctx context.Context) (*DelegationEdge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DelegationEdgeCreate) SaveX(ctx context.Context) *DelegationEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationEdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationEdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DelegationEdgeCreate) defaults() {
	if _, ok := _c.mutation.ScopeID(); !ok {
		v := delegationedge.DefaultScopeID
		_c.mutation.SetScopeID(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := delegationedge.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.Grandfathered(); !ok {
		v := delegationedge.DefaultGrandfathered
		_c.mutation.SetGrandfathered(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := delegationedge.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := delegationedge.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := delegationedge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DelegationEdgeCreate) check() error {
	if _, ok := _c.mutation.DelegatorType(); !ok {
		return &ValidationError{Name: "delegator_type", err: errors.New(`ent: missing required field "DelegationEdge.delegator_type"`)}
	}
	if v, ok := _c.mutation.DelegatorType(); ok {
		if err := delegationedge.DelegatorTypeValidator(v); err != nil {
			return &ValidationError{Name: "delegator_type", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.delegator_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DelegatorID(); !ok {
		return &ValidationError{Name: "delegator_id", err: errors.New(`ent: missing required field "DelegationEdge.delegator_id"`)}
	}
	if v, ok := _c.mutation.DelegatorID(); ok {
		if err := delegationedge.DelegatorIDValidator(v); err != nil {
			return &ValidationError{Name: "delegator_id", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.delegator_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DelegateType(); !ok {
		return &ValidationError{Name: "delegate_type", err: errors.New(`ent: missing required field "DelegationEdge.delegate_type"`)}
	}
	if v, ok := _c.mutation.DelegateType(); ok {
		if err := delegationedge.DelegateTypeValidator(v); err != nil {
			return &ValidationError{Name: "delegate_type", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.delegate_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DelegateID(); !ok {
		return &ValidationError{Name: "delegate_id", err: errors.New(`ent: missing required field "DelegationEdge.delegate_id"`)}
	}
	if v, ok := _c.mutation.DelegateID(); ok {
		if err := delegationedge.DelegateIDValidator(v); err != nil {
			return &ValidationError{Name: "delegate_id", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.delegate_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "DelegationEdge.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := delegationedge.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "DelegationEdge.scope_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "DelegationEdge.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := delegationedge.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "DelegationEdge.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "DelegationEdge.active"`)}
	}
	if _, ok := _c.mutation.Grandfathered(); !ok {
		return &ValidationError{Name: "grandfathered", err: errors.New(`ent: missing required field "DelegationEdge.grandfathered"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "DelegationEdge.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "DelegationEdge.updated"`)}
	}
	return nil
}

func (_c *DelegationEdgeCreate) sqlSave(ctx context.Context) (*DelegationEdge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DelegationEdgeCreate) createSpec() (*DelegationEdge, *sqlgraph.CreateSpec) {
	var (
		_node = &DelegationEdge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(delegationedge.Table, sqlgraph.NewFieldSpec(delegationedge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DelegatorType(); ok {
		_spec.SetField(delegationedge.FieldDelegatorType, field.TypeEnum, value)
		_node.DelegatorType = value
	}
	if value, ok := _c.mutation.DelegatorID(); ok {
		_spec.SetField(delegationedge.FieldDelegatorID, field.TypeString, value)
		_node.DelegatorID = value
	}
	if value, ok := _c.mutation.DelegateType(); ok {
		_spec.SetField(delegationedge.FieldDelegateType, field.TypeEnum, value)
		_node.DelegateType = value
	}
	if value, ok := _c.mutation.DelegateID(); ok {
		_spec.SetField(delegationedge.FieldDelegateID, field.TypeString, value)
		_node.DelegateID = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(delegationedge.FieldScopeType, field.TypeEnum, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(delegationedge.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(delegationedge.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(delegationedge.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Grandfathered(); ok {
		_spec.SetField(delegationedge.FieldGrandfathered, field.TypeBool, value)
		_node.Grandfathered = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(delegationedge.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(delegationedge.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DelegationEdge.Create().
//		SetDelegatorType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DelegationEdgeUpsert) {
//			SetDelegatorType(v+v).
//		}).
//		Exec(ctx)
func (_c *DelegationEdgeCreate) OnConflict(opts ...sql.ConflictOption) *DelegationEdgeUpsertOne {
	_c.conflict = opts
	return &DelegationEdgeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DelegationEdgeCreate) OnConflictColumns(columns ...string) *DelegationEdgeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DelegationEdgeUpsertOne{
		create: _c,
	}
}

type (
	// DelegationEdgeUpsertOne is the builder for "upsert"-ing
	//  one DelegationEdge node.
	DelegationEdgeUpsertOne struct {
		create *DelegationEdgeCreate
	}

	// DelegationEdgeUpsert is the "OnConflict" setter.
	DelegationEdgeUpsert struct {
		*sql.UpdateSet
	}
)

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationEdgeUpsert) SetDelegatorType(v delegationedge.DelegatorType) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldDelegatorType, v)
	return u
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateDelegatorType() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldDelegatorType)
	return u
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationEdgeUpsert) SetDelegatorID(v string) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldDelegatorID, v)
	return u
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateDelegatorID() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldDelegatorID)
	return u
}

// SetDelegateType sets the "delegate_type" field.
func (u *DelegationEdgeUpsert) SetDelegateType(v delegationedge.DelegateType) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldDelegateType, v)
	return u
}

// UpdateDelegateType sets the "delegate_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateDelegateType() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldDelegateType)
	return u
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationEdgeUpsert) SetDelegateID(v string) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldDelegateID, v)
	return u
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateDelegateID() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldDelegateID)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *DelegationEdgeUpsert) SetScopeType(v delegationedge.ScopeType) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateScopeType() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldScopeType)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationEdgeUpsert) SetScopeID(v string) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateScopeID() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldScopeID)
	return u
}

// SetRole sets the "role" field.
func (u *DelegationEdgeUpsert) SetRole(v string) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateRole() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldRole)
	return u
}

// SetActive sets the "active" field.
func (u *DelegationEdgeUpsert) SetActive(v bool) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateActive() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldActive)
	return u
}

// SetGrandfathered sets the "grandfathered" field.
func (u *DelegationEdgeUpsert) SetGrandfathered(v bool) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldGrandfathered, v)
	return u
}

// UpdateGrandfathered sets the "grandfathered" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateGrandfathered() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldGrandfathered)
	return u
}

// SetUpdated sets the "updated" field.
func (u *DelegationEdgeUpsert) SetUpdated(v time.Time) *DelegationEdgeUpsert {
	u.Set(delegationedge.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationEdgeUpsert) UpdateUpdated() *DelegationEdgeUpsert {
	u.SetExcluded(delegationedge.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(delegationedge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DelegationEdgeUpsertOne) UpdateNewValues() *DelegationEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(delegationedge.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(delegationedge.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DelegationEdgeUpsertOne) Ignore() *DelegationEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DelegationEdgeUpsertOne) DoNothing() *DelegationEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DelegationEdgeCreate.OnConflict
// documentation for more info.
func (u *DelegationEdgeUpsertOne) Update(set func(*DelegationEdgeUpsert)) *DelegationEdgeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DelegationEdgeUpsert{UpdateSet: update})
	}))
	return u
}

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationEdgeUpsertOne) SetDelegatorType(v delegationedge.DelegatorType) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegatorType(v)
	})
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateDelegatorType() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegatorType()
	})
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationEdgeUpsertOne) SetDelegatorID(v string) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegatorID(v)
	})
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateDelegatorID() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegatorID()
	})
}

// SetDelegateType sets the "delegate_type" field.
func (u *DelegationEdgeUpsertOne) SetDelegateType(v delegationedge.DelegateType) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegateType(v)
	})
}

// UpdateDelegateType sets the "delegate_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateDelegateType() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegateType()
	})
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationEdgeUpsertOne) SetDelegateID(v string) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegateID(v)
	})
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateDelegateID() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegateID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *DelegationEdgeUpsertOne) SetScopeType(v delegationedge.ScopeType) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateScopeType() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationEdgeUpsertOne) SetScopeID(v string) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateScopeID() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateScopeID()
	})
}

// SetRole sets the "role" field.
func (u *DelegationEdgeUpsertOne) SetRole(v string) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateRole() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateRole()
	})
}

// SetActive sets the "active" field.
func (u *DelegationEdgeUpsertOne) SetActive(v bool) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateActive() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateActive()
	})
}

// SetGrandfathered sets the "grandfathered" field.
func (u *DelegationEdgeUpsertOne) SetGrandfathered(v bool) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetGrandfathered(v)
	})
}

// UpdateGrandfathered sets the "grandfathered" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateGrandfathered() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateGrandfathered()
	})
}

// SetUpdated sets the "updated" field.
func (u *DelegationEdgeUpsertOne) SetUpdated(v time.Time) *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationEdgeUpsertOne) UpdateUpdated() *DelegationEdgeUpsertOne {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *DelegationEdgeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DelegationEdgeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DelegationEdgeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DelegationEdgeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DelegationEdgeUpsertOne.ID is not supported by MySQL driver. Use DelegationEdgeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DelegationEdgeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DelegationEdgeCreateBulk is the builder for creating many DelegationEdge entities in bulk.
type DelegationEdgeCreateBulk struct {
	config
	err      error
	builders []*DelegationEdgeCreate
	conflict []sql.ConflictOption
}

// Save creates the DelegationEdge entities in the database.
func (_c *DelegationEdgeCreateBulk) Save(ctx context.Context) ([]*DelegationEdge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DelegationEdge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DelegationEdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DelegationEdgeCreateBulk) SaveX(ctx context.Context) []*DelegationEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationEdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationEdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DelegationEdge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DelegationEdgeUpsert) {
//			SetDelegatorType(v+v).
//		}).
//		Exec(ctx)
func (_c *DelegationEdgeCreateBulk) OnConflict(opts ...sql.ConflictOption) *DelegationEdgeUpsertBulk {
	_c.conflict = opts
	return &DelegationEdgeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DelegationEdgeCreateBulk) OnConflictColumns(columns ...string) *DelegationEdgeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DelegationEdgeUpsertBulk{
		create: _c,
	}
}

// DelegationEdgeUpsertBulk is the builder for "upsert"-ing
// a bulk of DelegationEdge nodes.
type DelegationEdgeUpsertBulk struct {
	create *DelegationEdgeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(delegationedge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DelegationEdgeUpsertBulk) UpdateNewValues() *DelegationEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(delegationedge.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(delegationedge.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DelegationEdge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DelegationEdgeUpsertBulk) Ignore() *DelegationEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DelegationEdgeUpsertBulk) DoNothing() *DelegationEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DelegationEdgeCreateBulk.OnConflict
// documentation for more info.
func (u *DelegationEdgeUpsertBulk) Update(set func(*DelegationEdgeUpsert)) *DelegationEdgeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DelegationEdgeUpsert{UpdateSet: update})
	}))
	return u
}

// SetDelegatorType sets the "delegator_type" field.
func (u *DelegationEdgeUpsertBulk) SetDelegatorType(v delegationedge.DelegatorType) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegatorType(v)
	})
}

// UpdateDelegatorType sets the "delegator_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateDelegatorType() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegatorType()
	})
}

// SetDelegatorID sets the "delegator_id" field.
func (u *DelegationEdgeUpsertBulk) SetDelegatorID(v string) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegatorID(v)
	})
}

// UpdateDelegatorID sets the "delegator_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateDelegatorID() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegatorID()
	})
}

// SetDelegateType sets the "delegate_type" field.
func (u *DelegationEdgeUpsertBulk) SetDelegateType(v delegationedge.DelegateType) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegateType(v)
	})
}

// UpdateDelegateType sets the "delegate_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateDelegateType() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegateType()
	})
}

// SetDelegateID sets the "delegate_id" field.
func (u *DelegationEdgeUpsertBulk) SetDelegateID(v string) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetDelegateID(v)
	})
}

// UpdateDelegateID sets the "delegate_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateDelegateID() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateDelegateID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *DelegationEdgeUpsertBulk) SetScopeType(v delegationedge.ScopeType) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateScopeType() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *DelegationEdgeUpsertBulk) SetScopeID(v string) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateScopeID() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateScopeID()
	})
}

// SetRole sets the "role" field.
func (u *DelegationEdgeUpsertBulk) SetRole(v string) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateRole() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateRole()
	})
}

// SetActive sets the "active" field.
func (u *DelegationEdgeUpsertBulk) SetActive(v bool) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateActive() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateActive()
	})
}

// SetGrandfathered sets the "grandfathered" field.
func (u *DelegationEdgeUpsertBulk) SetGrandfathered(v bool) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetGrandfathered(v)
	})
}

// UpdateGrandfathered sets the "grandfathered" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateGrandfathered() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateGrandfathered()
	})
}

// SetUpdated sets the "updated" field.
func (u *DelegationEdgeUpsertBulk) SetUpdated(v time.Time) *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *DelegationEdgeUpsertBulk) UpdateUpdated() *DelegationEdgeUpsertBulk {
	return u.Update(func(s *DelegationEdgeUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *DelegationEdgeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DelegationEdgeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DelegationEdgeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DelegationEdgeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
