// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/membershiplosscheck"
	"github.com/google/uuid"
)

// MembershipLossCheckCreate is the builder for creating a MembershipLossCheck entity.
type MembershipLossCheckCreate struct {
	config
	mutation *MembershipLossCheckMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *MembershipLossCheckCreate) SetUserID(v string) *MembershipLossCheckCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *MembershipLossCheckCreate) SetProjectID(v string) *MembershipLossCheckCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableProjectID(v *string) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *MembershipLossCheckCreate) SetTrigger(v membershiplosscheck.Trigger) *MembershipLossCheckCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetActorKind sets the "actor_kind" field.
func (_c *MembershipLossCheckCreate) SetActorKind(v string) *MembershipLossCheckCreate {
	_c.mutation.SetActorKind(v)
	return _c
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableActorKind(v *string) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetActorKind(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *MembershipLossCheckCreate) SetActorID(v string) *MembershipLossCheckCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableActorID(v *string) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetCorrelationID sets the "correlation_id" field.
func (_c *MembershipLossCheckCreate) SetCorrelationID(v string) *MembershipLossCheckCreate {
	_c.mutation.SetCorrelationID(v)
	return _c
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableCorrelationID(v *string) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetCorrelationID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MembershipLossCheckCreate) SetCreatedAt(v time.Time) *MembershipLossCheckCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableCreatedAt(v *time.Time) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *MembershipLossCheckCreate) SetAttempts(v int) *MembershipLossCheckCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableAttempts(v *int) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *MembershipLossCheckCreate) SetLastError(v string) *MembershipLossCheckCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableLastError(v *string) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLeaseUntil sets the "lease_until" field.
func (_c *MembershipLossCheckCreate) SetLeaseUntil(v time.Time) *MembershipLossCheckCreate {
	_c.mutation.SetLeaseUntil(v)
	return _c
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableLeaseUntil(v *time.Time) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetLeaseUntil(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MembershipLossCheckCreate) SetID(v uuid.UUID) *MembershipLossCheckCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MembershipLossCheckCreate) SetNillableID(v *uuid.UUID) *MembershipLossCheckCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MembershipLossCheckMutation object of the builder.
func (_c *MembershipLossCheckCreate) Mutation() *MembershipLossCheckMutation {
	return _c.mutation
}

// Save creates the MembershipLossCheck in the database.
func (_c *MembershipLossCheckCreate) Save(ctx context.Context) (*MembershipLossCheck, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MembershipLossCheckCreate) SaveX(ctx context.Context) *MembershipLossCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MembershipLossCheckCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MembershipLossCheckCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MembershipLossCheckCreate) defaults() {
	if _, ok := _c.mutation.ActorKind(); !ok {
		v := membershiplosscheck.DefaultActorKind
		_c.mutation.SetActorKind(v)
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		v := membershiplosscheck.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.CorrelationID(); !ok {
		v := membershiplosscheck.DefaultCorrelationID
		_c.mutation.SetCorrelationID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := membershiplosscheck.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := membershiplosscheck.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := membershiplosscheck.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := membershiplosscheck.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MembershipLossCheckCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MembershipLossCheck.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := membershiplosscheck.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MembershipLossCheck.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "MembershipLossCheck.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := membershiplosscheck.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "MembershipLossCheck.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorKind(); !ok {
		return &ValidationError{Name: "actor_kind", err: errors.New(`ent: missing required field "MembershipLossCheck.actor_kind"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "MembershipLossCheck.actor_id"`)}
	}
	if _, ok := _c.mutation.CorrelationID(); !ok {
		return &ValidationError{Name: "correlation_id", err: errors.New(`ent: missing required field "MembershipLossCheck.correlation_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MembershipLossCheck.created_at"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "MembershipLossCheck.attempts"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "MembershipLossCheck.last_error"`)}
	}
	return nil
}

func (_c *MembershipLossCheckCreate) sqlSave(ctx context.Context) (*MembershipLossCheck, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MembershipLossCheckCreate) createSpec() (*MembershipLossCheck, *sqlgraph.CreateSpec) {
	var (
		_node = &MembershipLossCheck{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(membershiplosscheck.Table, sqlgraph.NewFieldSpec(membershiplosscheck.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(membershiplosscheck.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(membershiplosscheck.FieldProjectID, field.TypeString, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(membershiplosscheck.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.ActorKind(); ok {
		_spec.SetField(membershiplosscheck.FieldActorKind, field.TypeString, value)
		_node.ActorKind = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(membershiplosscheck.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.CorrelationID(); ok {
		_spec.SetField(membershiplosscheck.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(membershiplosscheck.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(membershiplosscheck.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(membershiplosscheck.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.LeaseUntil(); ok {
		_spec.SetField(membershiplosscheck.FieldLeaseUntil, field.TypeTime, value)
		_node.LeaseUntil = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MembershipLossCheck.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MembershipLossCheckUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MembershipLossCheckCreate) OnConflict(opts ...sql.ConflictOption) *MembershipLossCheckUpsertOne {
	_c.conflict = opts
	return &MembershipLossCheckUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MembershipLossCheckCreate) OnConflictColumns(columns ...string) *MembershipLossCheckUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MembershipLossCheckUpsertOne{
		create: _c,
	}
}

type (
	// MembershipLossCheckUpsertOne is the builder for "upsert"-ing
	//  one MembershipLossCheck node.
	MembershipLossCheckUpsertOne struct {
		create *MembershipLossCheckCreate
	}

	// MembershipLossCheckUpsert is the "OnConflict" setter.
	MembershipLossCheckUpsert struct {
		*sql.UpdateSet
	}
)

// SetAttempts sets the "attempts" field.
func (u *MembershipLossCheckUpsert) SetAttempts(v int) *MembershipLossCheckUpsert {
	u.Set(membershiplosscheck.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MembershipLossCheckUpsert) UpdateAttempts() *MembershipLossCheckUpsert {
	u.SetExcluded(membershiplosscheck.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *MembershipLossCheckUpsert) AddAttempts(v int) *MembershipLossCheckUpsert {
	u.Add(membershiplosscheck.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *MembershipLossCheckUpsert) SetLastError(v string) *MembershipLossCheckUpsert {
	u.Set(membershiplosscheck.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MembershipLossCheckUpsert) UpdateLastError() *MembershipLossCheckUpsert {
	u.SetExcluded(membershiplosscheck.FieldLastError)
	return u
}

// SetLeaseUntil sets the "lease_until" field.
func (u *MembershipLossCheckUpsert) SetLeaseUntil(v time.Time) *MembershipLossCheckUpsert {
	u.Set(membershiplosscheck.FieldLeaseUntil, v)
	return u
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *MembershipLossCheckUpsert) UpdateLeaseUntil() *MembershipLossCheckUpsert {
	u.SetExcluded(membershiplosscheck.FieldLeaseUntil)
	return u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *MembershipLossCheckUpsert) ClearLeaseUntil() *MembershipLossCheckUpsert {
	u.SetNull(membershiplosscheck.FieldLeaseUntil)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(membershiplosscheck.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MembershipLossCheckUpsertOne) UpdateNewValues() *MembershipLossCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(membershiplosscheck.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(membershiplosscheck.FieldUserID)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(membershiplosscheck.FieldProjectID)
		}
		if _, exists := u.create.mutation.Trigger(); exists {
			s.SetIgnore(membershiplosscheck.FieldTrigger)
		}
		if _, exists := u.create.mutation.ActorKind(); exists {
			s.SetIgnore(membershiplosscheck.FieldActorKind)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(membershiplosscheck.FieldActorID)
		}
		if _, exists := u.create.mutation.CorrelationID(); exists {
			s.SetIgnore(membershiplosscheck.FieldCorrelationID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(membershiplosscheck.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MembershipLossCheckUpsertOne) Ignore() *MembershipLossCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MembershipLossCheckUpsertOne) DoNothing() *MembershipLossCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MembershipLossCheckCreate.OnConflict
// documentation for more info.
func (u *MembershipLossCheckUpsertOne) Update(set func(*MembershipLossCheckUpsert)) *MembershipLossCheckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MembershipLossCheckUpsert{UpdateSet: update})
	}))
	return u
}

// SetAttempts sets the "attempts" field.
func (u *MembershipLossCheckUpsertOne) SetAttempts(v int) *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *MembershipLossCheckUpsertOne) AddAttempts(v int) *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertOne) UpdateAttempts() *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *MembershipLossCheckUpsertOne) SetLastError(v string) *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertOne) UpdateLastError() *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateLastError()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *MembershipLossCheckUpsertOne) SetLeaseUntil(v time.Time) *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertOne) UpdateLeaseUntil() *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *MembershipLossCheckUpsertOne) ClearLeaseUntil() *MembershipLossCheckUpsertOne {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.ClearLeaseUntil()
	})
}

// Exec executes the query.
func (u *MembershipLossCheckUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MembershipLossCheckCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MembershipLossCheckUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MembershipLossCheckUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MembershipLossCheckUpsertOne.ID is not supported by MySQL driver. Use MembershipLossCheckUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MembershipLossCheckUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MembershipLossCheckCreateBulk is the builder for creating many MembershipLossCheck entities in bulk.
type MembershipLossCheckCreateBulk struct {
	config
	err      error
	builders []*MembershipLossCheckCreate
	conflict []sql.ConflictOption
}

// Save creates the MembershipLossCheck entities in the database.
func (_c *MembershipLossCheckCreateBulk) Save(ctx context.Context) ([]*MembershipLossCheck, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MembershipLossCheck, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MembershipLossCheckMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MembershipLossCheckCreateBulk) SaveX(ctx context.Context) []*MembershipLossCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MembershipLossCheckCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MembershipLossCheckCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MembershipLossCheck.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MembershipLossCheckUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MembershipLossCheckCreateBulk) OnConflict(opts ...sql.ConflictOption) *MembershipLossCheckUpsertBulk {
	_c.conflict = opts
	return &MembershipLossCheckUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MembershipLossCheckCreateBulk) OnConflictColumns(columns ...string) *MembershipLossCheckUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MembershipLossCheckUpsertBulk{
		create: _c,
	}
}

// MembershipLossCheckUpsertBulk is the builder for "upsert"-ing
// a bulk of MembershipLossCheck nodes.
type MembershipLossCheckUpsertBulk struct {
	create *MembershipLossCheckCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(membershiplosscheck.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MembershipLossCheckUpsertBulk) UpdateNewValues() *MembershipLossCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(membershiplosscheck.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(membershiplosscheck.FieldUserID)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(membershiplosscheck.FieldProjectID)
			}
			if _, exists := b.mutation.Trigger(); exists {
				s.SetIgnore(membershiplosscheck.FieldTrigger)
			}
			if _, exists := b.mutation.ActorKind(); exists {
				s.SetIgnore(membershiplosscheck.FieldActorKind)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(membershiplosscheck.FieldActorID)
			}
			if _, exists := b.mutation.CorrelationID(); exists {
				s.SetIgnore(membershiplosscheck.FieldCorrelationID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(membershiplosscheck.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MembershipLossCheck.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MembershipLossCheckUpsertBulk) Ignore() *MembershipLossCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MembershipLossCheckUpsertBulk) DoNothing() *MembershipLossCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MembershipLossCheckCreateBulk.OnConflict
// documentation for more info.
func (u *MembershipLossCheckUpsertBulk) Update(set func(*MembershipLossCheckUpsert)) *MembershipLossCheckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MembershipLossCheckUpsert{UpdateSet: update})
	}))
	return u
}

// SetAttempts sets the "attempts" field.
func (u *MembershipLossCheckUpsertBulk) SetAttempts(v int) *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *MembershipLossCheckUpsertBulk) AddAttempts(v int) *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertBulk) UpdateAttempts() *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *MembershipLossCheckUpsertBulk) SetLastError(v string) *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertBulk) UpdateLastError() *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateLastError()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *MembershipLossCheckUpsertBulk) SetLeaseUntil(v time.Time) *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *MembershipLossCheckUpsertBulk) UpdateLeaseUntil() *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *MembershipLossCheckUpsertBulk) ClearLeaseUntil() *MembershipLossCheckUpsertBulk {
	return u.Update(func(s *MembershipLossCheckUpsert) {
		s.ClearLeaseUntil()
	})
}

// Exec executes the query.
func (u *MembershipLossCheckUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MembershipLossCheckCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MembershipLossCheckCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MembershipLossCheckUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
