// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/mutationaudit"
	"github.com/google/uuid"
)

// MutationAuditCreate is the builder for creating a MutationAudit entity.
type MutationAuditCreate struct {
	config
	mutation *MutationAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTimestamp sets the "timestamp" field.
func (_c *MutationAuditCreate) SetTimestamp(v time.Time) *MutationAuditCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableTimestamp(v *time.Time) *MutationAuditCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetMutationType sets the "mutation_type" field.
func (_c *MutationAuditCreate) SetMutationType(v string) *MutationAuditCreate {
	_c.mutation.SetMutationType(v)
	return _c
}

// SetActorPrincipalKind sets the "actor_principal_kind" field.
func (_c *MutationAuditCreate) SetActorPrincipalKind(v string) *MutationAuditCreate {
	_c.mutation.SetActorPrincipalKind(v)
	return _c
}

// SetActorPrincipalID sets the "actor_principal_id" field.
func (_c *MutationAuditCreate) SetActorPrincipalID(v string) *MutationAuditCreate {
	_c.mutation.SetActorPrincipalID(v)
	return _c
}

// SetActorCredentialID sets the "actor_credential_id" field.
func (_c *MutationAuditCreate) SetActorCredentialID(v string) *MutationAuditCreate {
	_c.mutation.SetActorCredentialID(v)
	return _c
}

// SetNillableActorCredentialID sets the "actor_credential_id" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableActorCredentialID(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetActorCredentialID(*v)
	}
	return _c
}

// SetActorCredentialType sets the "actor_credential_type" field.
func (_c *MutationAuditCreate) SetActorCredentialType(v string) *MutationAuditCreate {
	_c.mutation.SetActorCredentialType(v)
	return _c
}

// SetNillableActorCredentialType sets the "actor_credential_type" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableActorCredentialType(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetActorCredentialType(*v)
	}
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *MutationAuditCreate) SetTargetType(v string) *MutationAuditCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *MutationAuditCreate) SetTargetID(v string) *MutationAuditCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetBeforeSummary sets the "before_summary" field.
func (_c *MutationAuditCreate) SetBeforeSummary(v string) *MutationAuditCreate {
	_c.mutation.SetBeforeSummary(v)
	return _c
}

// SetNillableBeforeSummary sets the "before_summary" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableBeforeSummary(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetBeforeSummary(*v)
	}
	return _c
}

// SetAfterSummary sets the "after_summary" field.
func (_c *MutationAuditCreate) SetAfterSummary(v string) *MutationAuditCreate {
	_c.mutation.SetAfterSummary(v)
	return _c
}

// SetNillableAfterSummary sets the "after_summary" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableAfterSummary(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetAfterSummary(*v)
	}
	return _c
}

// SetCanDelegateResult sets the "can_delegate_result" field.
func (_c *MutationAuditCreate) SetCanDelegateResult(v string) *MutationAuditCreate {
	_c.mutation.SetCanDelegateResult(v)
	return _c
}

// SetNillableCanDelegateResult sets the "can_delegate_result" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableCanDelegateResult(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetCanDelegateResult(*v)
	}
	return _c
}

// SetCanDelegateReason sets the "can_delegate_reason" field.
func (_c *MutationAuditCreate) SetCanDelegateReason(v string) *MutationAuditCreate {
	_c.mutation.SetCanDelegateReason(v)
	return _c
}

// SetNillableCanDelegateReason sets the "can_delegate_reason" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableCanDelegateReason(v *string) *MutationAuditCreate {
	if v != nil {
		_c.SetCanDelegateReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MutationAuditCreate) SetID(v uuid.UUID) *MutationAuditCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MutationAuditCreate) SetNillableID(v *uuid.UUID) *MutationAuditCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MutationAuditMutation object of the builder.
func (_c *MutationAuditCreate) Mutation() *MutationAuditMutation {
	return _c.mutation
}

// Save creates the MutationAudit in the database.
func (_c *MutationAuditCreate) Save(ctx context.Context) (*MutationAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MutationAuditCreate) SaveX(ctx context.Context) *MutationAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MutationAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MutationAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MutationAuditCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := mutationaudit.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mutationaudit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MutationAuditCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "MutationAudit.timestamp"`)}
	}
	if _, ok := _c.mutation.MutationType(); !ok {
		return &ValidationError{Name: "mutation_type", err: errors.New(`ent: missing required field "MutationAudit.mutation_type"`)}
	}
	if v, ok := _c.mutation.MutationType(); ok {
		if err := mutationaudit.MutationTypeValidator(v); err != nil {
			return &ValidationError{Name: "mutation_type", err: fmt.Errorf(`ent: validator failed for field "MutationAudit.mutation_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorPrincipalKind(); !ok {
		return &ValidationError{Name: "actor_principal_kind", err: errors.New(`ent: missing required field "MutationAudit.actor_principal_kind"`)}
	}
	if v, ok := _c.mutation.ActorPrincipalKind(); ok {
		if err := mutationaudit.ActorPrincipalKindValidator(v); err != nil {
			return &ValidationError{Name: "actor_principal_kind", err: fmt.Errorf(`ent: validator failed for field "MutationAudit.actor_principal_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorPrincipalID(); !ok {
		return &ValidationError{Name: "actor_principal_id", err: errors.New(`ent: missing required field "MutationAudit.actor_principal_id"`)}
	}
	if v, ok := _c.mutation.ActorPrincipalID(); ok {
		if err := mutationaudit.ActorPrincipalIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_principal_id", err: fmt.Errorf(`ent: validator failed for field "MutationAudit.actor_principal_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "MutationAudit.target_type"`)}
	}
	if v, ok := _c.mutation.TargetType(); ok {
		if err := mutationaudit.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "MutationAudit.target_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "MutationAudit.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := mutationaudit.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "MutationAudit.target_id": %w`, err)}
		}
	}
	return nil
}

func (_c *MutationAuditCreate) sqlSave(ctx context.Context) (*MutationAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MutationAuditCreate) createSpec() (*MutationAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &MutationAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mutationaudit.Table, sqlgraph.NewFieldSpec(mutationaudit.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(mutationaudit.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.MutationType(); ok {
		_spec.SetField(mutationaudit.FieldMutationType, field.TypeString, value)
		_node.MutationType = value
	}
	if value, ok := _c.mutation.ActorPrincipalKind(); ok {
		_spec.SetField(mutationaudit.FieldActorPrincipalKind, field.TypeString, value)
		_node.ActorPrincipalKind = value
	}
	if value, ok := _c.mutation.ActorPrincipalID(); ok {
		_spec.SetField(mutationaudit.FieldActorPrincipalID, field.TypeString, value)
		_node.ActorPrincipalID = value
	}
	if value, ok := _c.mutation.ActorCredentialID(); ok {
		_spec.SetField(mutationaudit.FieldActorCredentialID, field.TypeString, value)
		_node.ActorCredentialID = value
	}
	if value, ok := _c.mutation.ActorCredentialType(); ok {
		_spec.SetField(mutationaudit.FieldActorCredentialType, field.TypeString, value)
		_node.ActorCredentialType = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(mutationaudit.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(mutationaudit.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.BeforeSummary(); ok {
		_spec.SetField(mutationaudit.FieldBeforeSummary, field.TypeString, value)
		_node.BeforeSummary = value
	}
	if value, ok := _c.mutation.AfterSummary(); ok {
		_spec.SetField(mutationaudit.FieldAfterSummary, field.TypeString, value)
		_node.AfterSummary = value
	}
	if value, ok := _c.mutation.CanDelegateResult(); ok {
		_spec.SetField(mutationaudit.FieldCanDelegateResult, field.TypeString, value)
		_node.CanDelegateResult = value
	}
	if value, ok := _c.mutation.CanDelegateReason(); ok {
		_spec.SetField(mutationaudit.FieldCanDelegateReason, field.TypeString, value)
		_node.CanDelegateReason = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MutationAudit.Create().
//		SetTimestamp(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MutationAuditUpsert) {
//			SetTimestamp(v+v).
//		}).
//		Exec(ctx)
func (_c *MutationAuditCreate) OnConflict(opts ...sql.ConflictOption) *MutationAuditUpsertOne {
	_c.conflict = opts
	return &MutationAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MutationAuditCreate) OnConflictColumns(columns ...string) *MutationAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MutationAuditUpsertOne{
		create: _c,
	}
}

type (
	// MutationAuditUpsertOne is the builder for "upsert"-ing
	//  one MutationAudit node.
	MutationAuditUpsertOne struct {
		create *MutationAuditCreate
	}

	// MutationAuditUpsert is the "OnConflict" setter.
	MutationAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetMutationType sets the "mutation_type" field.
func (u *MutationAuditUpsert) SetMutationType(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldMutationType, v)
	return u
}

// UpdateMutationType sets the "mutation_type" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateMutationType() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldMutationType)
	return u
}

// SetActorPrincipalKind sets the "actor_principal_kind" field.
func (u *MutationAuditUpsert) SetActorPrincipalKind(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldActorPrincipalKind, v)
	return u
}

// UpdateActorPrincipalKind sets the "actor_principal_kind" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateActorPrincipalKind() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldActorPrincipalKind)
	return u
}

// SetActorPrincipalID sets the "actor_principal_id" field.
func (u *MutationAuditUpsert) SetActorPrincipalID(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldActorPrincipalID, v)
	return u
}

// UpdateActorPrincipalID sets the "actor_principal_id" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateActorPrincipalID() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldActorPrincipalID)
	return u
}

// SetActorCredentialID sets the "actor_credential_id" field.
func (u *MutationAuditUpsert) SetActorCredentialID(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldActorCredentialID, v)
	return u
}

// UpdateActorCredentialID sets the "actor_credential_id" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateActorCredentialID() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldActorCredentialID)
	return u
}

// ClearActorCredentialID clears the value of the "actor_credential_id" field.
func (u *MutationAuditUpsert) ClearActorCredentialID() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldActorCredentialID)
	return u
}

// SetActorCredentialType sets the "actor_credential_type" field.
func (u *MutationAuditUpsert) SetActorCredentialType(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldActorCredentialType, v)
	return u
}

// UpdateActorCredentialType sets the "actor_credential_type" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateActorCredentialType() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldActorCredentialType)
	return u
}

// ClearActorCredentialType clears the value of the "actor_credential_type" field.
func (u *MutationAuditUpsert) ClearActorCredentialType() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldActorCredentialType)
	return u
}

// SetTargetType sets the "target_type" field.
func (u *MutationAuditUpsert) SetTargetType(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldTargetType, v)
	return u
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateTargetType() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldTargetType)
	return u
}

// SetTargetID sets the "target_id" field.
func (u *MutationAuditUpsert) SetTargetID(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldTargetID, v)
	return u
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateTargetID() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldTargetID)
	return u
}

// SetBeforeSummary sets the "before_summary" field.
func (u *MutationAuditUpsert) SetBeforeSummary(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldBeforeSummary, v)
	return u
}

// UpdateBeforeSummary sets the "before_summary" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateBeforeSummary() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldBeforeSummary)
	return u
}

// ClearBeforeSummary clears the value of the "before_summary" field.
func (u *MutationAuditUpsert) ClearBeforeSummary() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldBeforeSummary)
	return u
}

// SetAfterSummary sets the "after_summary" field.
func (u *MutationAuditUpsert) SetAfterSummary(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldAfterSummary, v)
	return u
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateAfterSummary() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldAfterSummary)
	return u
}

// ClearAfterSummary clears the value of the "after_summary" field.
func (u *MutationAuditUpsert) ClearAfterSummary() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldAfterSummary)
	return u
}

// SetCanDelegateResult sets the "can_delegate_result" field.
func (u *MutationAuditUpsert) SetCanDelegateResult(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldCanDelegateResult, v)
	return u
}

// UpdateCanDelegateResult sets the "can_delegate_result" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateCanDelegateResult() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldCanDelegateResult)
	return u
}

// ClearCanDelegateResult clears the value of the "can_delegate_result" field.
func (u *MutationAuditUpsert) ClearCanDelegateResult() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldCanDelegateResult)
	return u
}

// SetCanDelegateReason sets the "can_delegate_reason" field.
func (u *MutationAuditUpsert) SetCanDelegateReason(v string) *MutationAuditUpsert {
	u.Set(mutationaudit.FieldCanDelegateReason, v)
	return u
}

// UpdateCanDelegateReason sets the "can_delegate_reason" field to the value that was provided on create.
func (u *MutationAuditUpsert) UpdateCanDelegateReason() *MutationAuditUpsert {
	u.SetExcluded(mutationaudit.FieldCanDelegateReason)
	return u
}

// ClearCanDelegateReason clears the value of the "can_delegate_reason" field.
func (u *MutationAuditUpsert) ClearCanDelegateReason() *MutationAuditUpsert {
	u.SetNull(mutationaudit.FieldCanDelegateReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mutationaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MutationAuditUpsertOne) UpdateNewValues() *MutationAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(mutationaudit.FieldID)
		}
		if _, exists := u.create.mutation.Timestamp(); exists {
			s.SetIgnore(mutationaudit.FieldTimestamp)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MutationAuditUpsertOne) Ignore() *MutationAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MutationAuditUpsertOne) DoNothing() *MutationAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MutationAuditCreate.OnConflict
// documentation for more info.
func (u *MutationAuditUpsertOne) Update(set func(*MutationAuditUpsert)) *MutationAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MutationAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetMutationType sets the "mutation_type" field.
func (u *MutationAuditUpsertOne) SetMutationType(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetMutationType(v)
	})
}

// UpdateMutationType sets the "mutation_type" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateMutationType() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateMutationType()
	})
}

// SetActorPrincipalKind sets the "actor_principal_kind" field.
func (u *MutationAuditUpsertOne) SetActorPrincipalKind(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorPrincipalKind(v)
	})
}

// UpdateActorPrincipalKind sets the "actor_principal_kind" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateActorPrincipalKind() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorPrincipalKind()
	})
}

// SetActorPrincipalID sets the "actor_principal_id" field.
func (u *MutationAuditUpsertOne) SetActorPrincipalID(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorPrincipalID(v)
	})
}

// UpdateActorPrincipalID sets the "actor_principal_id" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateActorPrincipalID() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorPrincipalID()
	})
}

// SetActorCredentialID sets the "actor_credential_id" field.
func (u *MutationAuditUpsertOne) SetActorCredentialID(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorCredentialID(v)
	})
}

// UpdateActorCredentialID sets the "actor_credential_id" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateActorCredentialID() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorCredentialID()
	})
}

// ClearActorCredentialID clears the value of the "actor_credential_id" field.
func (u *MutationAuditUpsertOne) ClearActorCredentialID() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearActorCredentialID()
	})
}

// SetActorCredentialType sets the "actor_credential_type" field.
func (u *MutationAuditUpsertOne) SetActorCredentialType(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorCredentialType(v)
	})
}

// UpdateActorCredentialType sets the "actor_credential_type" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateActorCredentialType() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorCredentialType()
	})
}

// ClearActorCredentialType clears the value of the "actor_credential_type" field.
func (u *MutationAuditUpsertOne) ClearActorCredentialType() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearActorCredentialType()
	})
}

// SetTargetType sets the "target_type" field.
func (u *MutationAuditUpsertOne) SetTargetType(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateTargetType() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateTargetType()
	})
}

// SetTargetID sets the "target_id" field.
func (u *MutationAuditUpsertOne) SetTargetID(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateTargetID() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateTargetID()
	})
}

// SetBeforeSummary sets the "before_summary" field.
func (u *MutationAuditUpsertOne) SetBeforeSummary(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetBeforeSummary(v)
	})
}

// UpdateBeforeSummary sets the "before_summary" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateBeforeSummary() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateBeforeSummary()
	})
}

// ClearBeforeSummary clears the value of the "before_summary" field.
func (u *MutationAuditUpsertOne) ClearBeforeSummary() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearBeforeSummary()
	})
}

// SetAfterSummary sets the "after_summary" field.
func (u *MutationAuditUpsertOne) SetAfterSummary(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetAfterSummary(v)
	})
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateAfterSummary() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateAfterSummary()
	})
}

// ClearAfterSummary clears the value of the "after_summary" field.
func (u *MutationAuditUpsertOne) ClearAfterSummary() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearAfterSummary()
	})
}

// SetCanDelegateResult sets the "can_delegate_result" field.
func (u *MutationAuditUpsertOne) SetCanDelegateResult(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetCanDelegateResult(v)
	})
}

// UpdateCanDelegateResult sets the "can_delegate_result" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateCanDelegateResult() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateCanDelegateResult()
	})
}

// ClearCanDelegateResult clears the value of the "can_delegate_result" field.
func (u *MutationAuditUpsertOne) ClearCanDelegateResult() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearCanDelegateResult()
	})
}

// SetCanDelegateReason sets the "can_delegate_reason" field.
func (u *MutationAuditUpsertOne) SetCanDelegateReason(v string) *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetCanDelegateReason(v)
	})
}

// UpdateCanDelegateReason sets the "can_delegate_reason" field to the value that was provided on create.
func (u *MutationAuditUpsertOne) UpdateCanDelegateReason() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateCanDelegateReason()
	})
}

// ClearCanDelegateReason clears the value of the "can_delegate_reason" field.
func (u *MutationAuditUpsertOne) ClearCanDelegateReason() *MutationAuditUpsertOne {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearCanDelegateReason()
	})
}

// Exec executes the query.
func (u *MutationAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MutationAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MutationAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MutationAuditUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MutationAuditUpsertOne.ID is not supported by MySQL driver. Use MutationAuditUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MutationAuditUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MutationAuditCreateBulk is the builder for creating many MutationAudit entities in bulk.
type MutationAuditCreateBulk struct {
	config
	err      error
	builders []*MutationAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the MutationAudit entities in the database.
func (_c *MutationAuditCreateBulk) Save(ctx context.Context) ([]*MutationAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MutationAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MutationAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MutationAuditCreateBulk) SaveX(ctx context.Context) []*MutationAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MutationAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MutationAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MutationAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MutationAuditUpsert) {
//			SetTimestamp(v+v).
//		}).
//		Exec(ctx)
func (_c *MutationAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *MutationAuditUpsertBulk {
	_c.conflict = opts
	return &MutationAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MutationAuditCreateBulk) OnConflictColumns(columns ...string) *MutationAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MutationAuditUpsertBulk{
		create: _c,
	}
}

// MutationAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of MutationAudit nodes.
type MutationAuditUpsertBulk struct {
	create *MutationAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mutationaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MutationAuditUpsertBulk) UpdateNewValues() *MutationAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(mutationaudit.FieldID)
			}
			if _, exists := b.mutation.Timestamp(); exists {
				s.SetIgnore(mutationaudit.FieldTimestamp)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MutationAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MutationAuditUpsertBulk) Ignore() *MutationAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MutationAuditUpsertBulk) DoNothing() *MutationAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MutationAuditCreateBulk.OnConflict
// documentation for more info.
func (u *MutationAuditUpsertBulk) Update(set func(*MutationAuditUpsert)) *MutationAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MutationAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetMutationType sets the "mutation_type" field.
func (u *MutationAuditUpsertBulk) SetMutationType(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetMutationType(v)
	})
}

// UpdateMutationType sets the "mutation_type" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateMutationType() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateMutationType()
	})
}

// SetActorPrincipalKind sets the "actor_principal_kind" field.
func (u *MutationAuditUpsertBulk) SetActorPrincipalKind(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorPrincipalKind(v)
	})
}

// UpdateActorPrincipalKind sets the "actor_principal_kind" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateActorPrincipalKind() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorPrincipalKind()
	})
}

// SetActorPrincipalID sets the "actor_principal_id" field.
func (u *MutationAuditUpsertBulk) SetActorPrincipalID(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorPrincipalID(v)
	})
}

// UpdateActorPrincipalID sets the "actor_principal_id" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateActorPrincipalID() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorPrincipalID()
	})
}

// SetActorCredentialID sets the "actor_credential_id" field.
func (u *MutationAuditUpsertBulk) SetActorCredentialID(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorCredentialID(v)
	})
}

// UpdateActorCredentialID sets the "actor_credential_id" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateActorCredentialID() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorCredentialID()
	})
}

// ClearActorCredentialID clears the value of the "actor_credential_id" field.
func (u *MutationAuditUpsertBulk) ClearActorCredentialID() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearActorCredentialID()
	})
}

// SetActorCredentialType sets the "actor_credential_type" field.
func (u *MutationAuditUpsertBulk) SetActorCredentialType(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetActorCredentialType(v)
	})
}

// UpdateActorCredentialType sets the "actor_credential_type" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateActorCredentialType() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateActorCredentialType()
	})
}

// ClearActorCredentialType clears the value of the "actor_credential_type" field.
func (u *MutationAuditUpsertBulk) ClearActorCredentialType() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearActorCredentialType()
	})
}

// SetTargetType sets the "target_type" field.
func (u *MutationAuditUpsertBulk) SetTargetType(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateTargetType() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateTargetType()
	})
}

// SetTargetID sets the "target_id" field.
func (u *MutationAuditUpsertBulk) SetTargetID(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateTargetID() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateTargetID()
	})
}

// SetBeforeSummary sets the "before_summary" field.
func (u *MutationAuditUpsertBulk) SetBeforeSummary(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetBeforeSummary(v)
	})
}

// UpdateBeforeSummary sets the "before_summary" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateBeforeSummary() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateBeforeSummary()
	})
}

// ClearBeforeSummary clears the value of the "before_summary" field.
func (u *MutationAuditUpsertBulk) ClearBeforeSummary() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearBeforeSummary()
	})
}

// SetAfterSummary sets the "after_summary" field.
func (u *MutationAuditUpsertBulk) SetAfterSummary(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetAfterSummary(v)
	})
}

// UpdateAfterSummary sets the "after_summary" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateAfterSummary() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateAfterSummary()
	})
}

// ClearAfterSummary clears the value of the "after_summary" field.
func (u *MutationAuditUpsertBulk) ClearAfterSummary() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearAfterSummary()
	})
}

// SetCanDelegateResult sets the "can_delegate_result" field.
func (u *MutationAuditUpsertBulk) SetCanDelegateResult(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetCanDelegateResult(v)
	})
}

// UpdateCanDelegateResult sets the "can_delegate_result" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateCanDelegateResult() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateCanDelegateResult()
	})
}

// ClearCanDelegateResult clears the value of the "can_delegate_result" field.
func (u *MutationAuditUpsertBulk) ClearCanDelegateResult() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearCanDelegateResult()
	})
}

// SetCanDelegateReason sets the "can_delegate_reason" field.
func (u *MutationAuditUpsertBulk) SetCanDelegateReason(v string) *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.SetCanDelegateReason(v)
	})
}

// UpdateCanDelegateReason sets the "can_delegate_reason" field to the value that was provided on create.
func (u *MutationAuditUpsertBulk) UpdateCanDelegateReason() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.UpdateCanDelegateReason()
	})
}

// ClearCanDelegateReason clears the value of the "can_delegate_reason" field.
func (u *MutationAuditUpsertBulk) ClearCanDelegateReason() *MutationAuditUpsertBulk {
	return u.Update(func(s *MutationAuditUpsert) {
		s.ClearCanDelegateReason()
	})
}

// Exec executes the query.
func (u *MutationAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MutationAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MutationAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MutationAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
