// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/notification"
	"github.com/google/uuid"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *NotificationCreate) SetSubscriptionID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *NotificationCreate) SetAgentID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *NotificationCreate) SetProjectID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetSubscriberType sets the "subscriber_type" field.
func (_c *NotificationCreate) SetSubscriberType(v string) *NotificationCreate {
	_c.mutation.SetSubscriberType(v)
	return _c
}

// SetSubscriberID sets the "subscriber_id" field.
func (_c *NotificationCreate) SetSubscriberID(v string) *NotificationCreate {
	_c.mutation.SetSubscriberID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationCreate) SetStatus(v string) *NotificationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *NotificationCreate) SetMessage(v string) *NotificationCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetDispatched sets the "dispatched" field.
func (_c *NotificationCreate) SetDispatched(v bool) *NotificationCreate {
	_c.mutation.SetDispatched(v)
	return _c
}

// SetNillableDispatched sets the "dispatched" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableDispatched(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetDispatched(*v)
	}
	return _c
}

// SetAcknowledged sets the "acknowledged" field.
func (_c *NotificationCreate) SetAcknowledged(v bool) *NotificationCreate {
	_c.mutation.SetAcknowledged(v)
	return _c
}

// SetNillableAcknowledged sets the "acknowledged" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableAcknowledged(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetAcknowledged(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *NotificationCreate) SetCreated(v time.Time) *NotificationCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreated(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationCreate) SetID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableID(v *uuid.UUID) *NotificationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.Dispatched(); !ok {
		v := notification.DefaultDispatched
		_c.mutation.SetDispatched(v)
	}
	if _, ok := _c.mutation.Acknowledged(); !ok {
		v := notification.DefaultAcknowledged
		_c.mutation.SetAcknowledged(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := notification.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notification.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "Notification.subscription_id"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Notification.agent_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Notification.project_id"`)}
	}
	if _, ok := _c.mutation.SubscriberType(); !ok {
		return &ValidationError{Name: "subscriber_type", err: errors.New(`ent: missing required field "Notification.subscriber_type"`)}
	}
	if v, ok := _c.mutation.SubscriberType(); ok {
		if err := notification.SubscriberTypeValidator(v); err != nil {
			return &ValidationError{Name: "subscriber_type", err: fmt.Errorf(`ent: validator failed for field "Notification.subscriber_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriberID(); !ok {
		return &ValidationError{Name: "subscriber_id", err: errors.New(`ent: missing required field "Notification.subscriber_id"`)}
	}
	if v, ok := _c.mutation.SubscriberID(); ok {
		if err := notification.SubscriberIDValidator(v); err != nil {
			return &ValidationError{Name: "subscriber_id", err: fmt.Errorf(`ent: validator failed for field "Notification.subscriber_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Notification.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Notification.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dispatched(); !ok {
		return &ValidationError{Name: "dispatched", err: errors.New(`ent: missing required field "Notification.dispatched"`)}
	}
	if _, ok := _c.mutation.Acknowledged(); !ok {
		return &ValidationError{Name: "acknowledged", err: errors.New(`ent: missing required field "Notification.acknowledged"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Notification.created"`)}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(notification.FieldSubscriptionID, field.TypeUUID, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(notification.FieldAgentID, field.TypeUUID, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(notification.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.SubscriberType(); ok {
		_spec.SetField(notification.FieldSubscriberType, field.TypeString, value)
		_node.SubscriberType = value
	}
	if value, ok := _c.mutation.SubscriberID(); ok {
		_spec.SetField(notification.FieldSubscriberID, field.TypeString, value)
		_node.SubscriberID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Dispatched(); ok {
		_spec.SetField(notification.FieldDispatched, field.TypeBool, value)
		_node.Dispatched = value
	}
	if value, ok := _c.mutation.Acknowledged(); ok {
		_spec.SetField(notification.FieldAcknowledged, field.TypeBool, value)
		_node.Acknowledged = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(notification.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
