// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/notificationsubscription"
	"github.com/google/uuid"
)

// NotificationSubscriptionCreate is the builder for creating a NotificationSubscription entity.
type NotificationSubscriptionCreate struct {
	config
	mutation *NotificationSubscriptionMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *NotificationSubscriptionCreate) SetScope(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableScope(v *string) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *NotificationSubscriptionCreate) SetAgentID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableAgentID(v *uuid.UUID) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetSubscriberType sets the "subscriber_type" field.
func (_c *NotificationSubscriptionCreate) SetSubscriberType(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetSubscriberType(v)
	return _c
}

// SetNillableSubscriberType sets the "subscriber_type" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableSubscriberType(v *string) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetSubscriberType(*v)
	}
	return _c
}

// SetSubscriberID sets the "subscriber_id" field.
func (_c *NotificationSubscriptionCreate) SetSubscriberID(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetSubscriberID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *NotificationSubscriptionCreate) SetProjectID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTriggerActivities sets the "trigger_activities" field.
func (_c *NotificationSubscriptionCreate) SetTriggerActivities(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetTriggerActivities(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationSubscriptionCreate) SetCreatedBy(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *NotificationSubscriptionCreate) SetCreated(v time.Time) *NotificationSubscriptionCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableCreated(v *time.Time) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationSubscriptionCreate) SetID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableID(v *uuid.UUID) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotificationSubscriptionMutation object of the builder.
func (_c *NotificationSubscriptionCreate) Mutation() *NotificationSubscriptionMutation {
	return _c.mutation
}

// Save creates the NotificationSubscription in the database.
func (_c *NotificationSubscriptionCreate) Save(ctx context.Context) (*NotificationSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationSubscriptionCreate) SaveX(ctx context.Context) *NotificationSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := notificationsubscription.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.SubscriberType(); !ok {
		v := notificationsubscription.DefaultSubscriberType
		_c.mutation.SetSubscriberType(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := notificationsubscription.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationsubscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationSubscriptionCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "NotificationSubscription.scope"`)}
	}
	if _, ok := _c.mutation.SubscriberType(); !ok {
		return &ValidationError{Name: "subscriber_type", err: errors.New(`ent: missing required field "NotificationSubscription.subscriber_type"`)}
	}
	if _, ok := _c.mutation.SubscriberID(); !ok {
		return &ValidationError{Name: "subscriber_id", err: errors.New(`ent: missing required field "NotificationSubscription.subscriber_id"`)}
	}
	if v, ok := _c.mutation.SubscriberID(); ok {
		if err := notificationsubscription.SubscriberIDValidator(v); err != nil {
			return &ValidationError{Name: "subscriber_id", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.subscriber_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "NotificationSubscription.project_id"`)}
	}
	if _, ok := _c.mutation.TriggerActivities(); !ok {
		return &ValidationError{Name: "trigger_activities", err: errors.New(`ent: missing required field "NotificationSubscription.trigger_activities"`)}
	}
	if v, ok := _c.mutation.TriggerActivities(); ok {
		if err := notificationsubscription.TriggerActivitiesValidator(v); err != nil {
			return &ValidationError{Name: "trigger_activities", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.trigger_activities": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "NotificationSubscription.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := notificationsubscription.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "NotificationSubscription.created"`)}
	}
	return nil
}

func (_c *NotificationSubscriptionCreate) sqlSave(ctx context.Context) (*NotificationSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationSubscriptionCreate) createSpec() (*NotificationSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationsubscription.Table, sqlgraph.NewFieldSpec(notificationsubscription.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(notificationsubscription.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(notificationsubscription.FieldAgentID, field.TypeUUID, value)
		_node.AgentID = &value
	}
	if value, ok := _c.mutation.SubscriberType(); ok {
		_spec.SetField(notificationsubscription.FieldSubscriberType, field.TypeString, value)
		_node.SubscriberType = value
	}
	if value, ok := _c.mutation.SubscriberID(); ok {
		_spec.SetField(notificationsubscription.FieldSubscriberID, field.TypeString, value)
		_node.SubscriberID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(notificationsubscription.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.TriggerActivities(); ok {
		_spec.SetField(notificationsubscription.FieldTriggerActivities, field.TypeString, value)
		_node.TriggerActivities = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notificationsubscription.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(notificationsubscription.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// NotificationSubscriptionCreateBulk is the builder for creating many NotificationSubscription entities in bulk.
type NotificationSubscriptionCreateBulk struct {
	config
	err      error
	builders []*NotificationSubscriptionCreate
}

// Save creates the NotificationSubscription entities in the database.
func (_c *NotificationSubscriptionCreateBulk) Save(ctx context.Context) ([]*NotificationSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationSubscriptionCreateBulk) SaveX(ctx context.Context) []*NotificationSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
