// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/rolebinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/roledefinition"
	"github.com/google/uuid"
)

// RoleBinding is the model entity for the RoleBinding schema.
type RoleBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RoleDefinitionID holds the value of the "role_definition_id" field.
	RoleDefinitionID *uuid.UUID `json:"role_definition_id,omitempty"`
	// PrincipalType holds the value of the "principal_type" field.
	PrincipalType rolebinding.PrincipalType `json:"principal_type,omitempty"`
	// PrincipalID holds the value of the "principal_id" field.
	PrincipalID string `json:"principal_id,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType rolebinding.ScopeType `json:"scope_type,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// NotBefore holds the value of the "not_before" field.
	NotBefore *time.Time `json:"not_before,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoleBindingQuery when eager-loading is set.
	Edges        RoleBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoleBindingEdges holds the relations/edges for other nodes in the graph.
type RoleBindingEdges struct {
	// RoleDefinition holds the value of the role_definition edge.
	RoleDefinition *RoleDefinition `json:"role_definition,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleDefinitionOrErr returns the RoleDefinition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoleBindingEdges) RoleDefinitionOrErr() (*RoleDefinition, error) {
	if e.RoleDefinition != nil {
		return e.RoleDefinition, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: roledefinition.Label}
	}
	return nil, &NotLoadedError{edge: "role_definition"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoleBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolebinding.FieldRoleDefinitionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rolebinding.FieldPrincipalType, rolebinding.FieldPrincipalID, rolebinding.FieldScopeType, rolebinding.FieldScopeID, rolebinding.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case rolebinding.FieldNotBefore, rolebinding.FieldExpiresAt, rolebinding.FieldCreated:
			values[i] = new(sql.NullTime)
		case rolebinding.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoleBinding fields.
func (_m *RoleBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolebinding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rolebinding.FieldRoleDefinitionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field role_definition_id", values[i])
			} else if value.Valid {
				_m.RoleDefinitionID = new(uuid.UUID)
				*_m.RoleDefinitionID = *value.S.(*uuid.UUID)
			}
		case rolebinding.FieldPrincipalType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field principal_type", values[i])
			} else if value.Valid {
				_m.PrincipalType = rolebinding.PrincipalType(value.String)
			}
		case rolebinding.FieldPrincipalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value.Valid {
				_m.PrincipalID = value.String
			}
		case rolebinding.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = rolebinding.ScopeType(value.String)
			}
		case rolebinding.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case rolebinding.FieldNotBefore:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_before", values[i])
			} else if value.Valid {
				_m.NotBefore = new(time.Time)
				*_m.NotBefore = value.Time
			}
		case rolebinding.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case rolebinding.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case rolebinding.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoleBinding.
// This includes values selected through modifiers, order, etc.
func (_m *RoleBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoleDefinition queries the "role_definition" edge of the RoleBinding entity.
func (_m *RoleBinding) QueryRoleDefinition() *RoleDefinitionQuery {
	return NewRoleBindingClient(_m.config).QueryRoleDefinition(_m)
}

// Update returns a builder for updating this RoleBinding.
// Note that you need to call RoleBinding.Unwrap() before calling this method if this RoleBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoleBinding) Update() *RoleBindingUpdateOne {
	return NewRoleBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoleBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoleBinding) Unwrap() *RoleBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoleBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoleBinding) String() string {
	var builder strings.Builder
	builder.WriteString("RoleBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.RoleDefinitionID; v != nil {
		builder.WriteString("role_definition_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("principal_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalType))
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(_m.PrincipalID)
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScopeType))
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	if v := _m.NotBefore; v != nil {
		builder.WriteString("not_before=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RoleBindings is a parsable slice of RoleBinding.
type RoleBindings []*RoleBinding
