// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/scheduledevent"
	"github.com/google/uuid"
)

// ScheduledEventCreate is the builder for creating a ScheduledEvent entity.
type ScheduledEventCreate struct {
	config
	mutation *ScheduledEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInitiatorPrincipalKind sets the "initiator_principal_kind" field.
func (_c *ScheduledEventCreate) SetInitiatorPrincipalKind(v string) *ScheduledEventCreate {
	_c.mutation.SetInitiatorPrincipalKind(v)
	return _c
}

// SetNillableInitiatorPrincipalKind sets the "initiator_principal_kind" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableInitiatorPrincipalKind(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetInitiatorPrincipalKind(*v)
	}
	return _c
}

// SetInitiatorPrincipalID sets the "initiator_principal_id" field.
func (_c *ScheduledEventCreate) SetInitiatorPrincipalID(v string) *ScheduledEventCreate {
	_c.mutation.SetInitiatorPrincipalID(v)
	return _c
}

// SetNillableInitiatorPrincipalID sets the "initiator_principal_id" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableInitiatorPrincipalID(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetInitiatorPrincipalID(*v)
	}
	return _c
}

// SetInitiatorCredentialKind sets the "initiator_credential_kind" field.
func (_c *ScheduledEventCreate) SetInitiatorCredentialKind(v string) *ScheduledEventCreate {
	_c.mutation.SetInitiatorCredentialKind(v)
	return _c
}

// SetNillableInitiatorCredentialKind sets the "initiator_credential_kind" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableInitiatorCredentialKind(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetInitiatorCredentialKind(*v)
	}
	return _c
}

// SetInitiatorCredentialID sets the "initiator_credential_id" field.
func (_c *ScheduledEventCreate) SetInitiatorCredentialID(v string) *ScheduledEventCreate {
	_c.mutation.SetInitiatorCredentialID(v)
	return _c
}

// SetNillableInitiatorCredentialID sets the "initiator_credential_id" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableInitiatorCredentialID(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetInitiatorCredentialID(*v)
	}
	return _c
}

// SetInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field.
func (_c *ScheduledEventCreate) SetInitiatorCredentialSnapshot(v string) *ScheduledEventCreate {
	_c.mutation.SetInitiatorCredentialSnapshot(v)
	return _c
}

// SetNillableInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableInitiatorCredentialSnapshot(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetInitiatorCredentialSnapshot(*v)
	}
	return _c
}

// SetAttributionVersion sets the "attribution_version" field.
func (_c *ScheduledEventCreate) SetAttributionVersion(v int) *ScheduledEventCreate {
	_c.mutation.SetAttributionVersion(v)
	return _c
}

// SetNillableAttributionVersion sets the "attribution_version" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAttributionVersion(v *int) *ScheduledEventCreate {
	if v != nil {
		_c.SetAttributionVersion(*v)
	}
	return _c
}

// SetAuthorizationRevision sets the "authorization_revision" field.
func (_c *ScheduledEventCreate) SetAuthorizationRevision(v int) *ScheduledEventCreate {
	_c.mutation.SetAuthorizationRevision(v)
	return _c
}

// SetNillableAuthorizationRevision sets the "authorization_revision" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorizationRevision(v *int) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorizationRevision(*v)
	}
	return _c
}

// SetAuthorityCeilingKind sets the "authority_ceiling_kind" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingKind(v string) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingKind(v)
	return _c
}

// SetNillableAuthorityCeilingKind sets the "authority_ceiling_kind" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingKind(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingKind(*v)
	}
	return _c
}

// SetAuthorityCeilingVersion sets the "authority_ceiling_version" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingVersion(v int32) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingVersion(v)
	return _c
}

// SetNillableAuthorityCeilingVersion sets the "authority_ceiling_version" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingVersion(v *int32) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingVersion(*v)
	}
	return _c
}

// SetAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingPermissionIds(v string) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingPermissionIds(v)
	return _c
}

// SetNillableAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingPermissionIds(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingPermissionIds(*v)
	}
	return _c
}

// SetAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingBoundaryKind(v string) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingBoundaryKind(v)
	return _c
}

// SetNillableAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingBoundaryKind(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingBoundaryKind(*v)
	}
	return _c
}

// SetAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingBoundaryProjectID(v string) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingBoundaryProjectID(v)
	return _c
}

// SetNillableAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingBoundaryProjectID(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingBoundaryProjectID(*v)
	}
	return _c
}

// SetAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field.
func (_c *ScheduledEventCreate) SetAuthorityCeilingSourceExpiresAt(v time.Time) *ScheduledEventCreate {
	_c.mutation.SetAuthorityCeilingSourceExpiresAt(v)
	return _c
}

// SetNillableAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableAuthorityCeilingSourceExpiresAt(v *time.Time) *ScheduledEventCreate {
	if v != nil {
		_c.SetAuthorityCeilingSourceExpiresAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *ScheduledEventCreate) SetProjectID(v uuid.UUID) *ScheduledEventCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *ScheduledEventCreate) SetEventType(v string) *ScheduledEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetFireAt sets the "fire_at" field.
func (_c *ScheduledEventCreate) SetFireAt(v time.Time) *ScheduledEventCreate {
	_c.mutation.SetFireAt(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *ScheduledEventCreate) SetPayload(v string) *ScheduledEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScheduledEventCreate) SetStatus(v string) *ScheduledEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableStatus(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ScheduledEventCreate) SetCreatedBy(v string) *ScheduledEventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableCreatedBy(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetFiredAt sets the "fired_at" field.
func (_c *ScheduledEventCreate) SetFiredAt(v time.Time) *ScheduledEventCreate {
	_c.mutation.SetFiredAt(v)
	return _c
}

// SetNillableFiredAt sets the "fired_at" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableFiredAt(v *time.Time) *ScheduledEventCreate {
	if v != nil {
		_c.SetFiredAt(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *ScheduledEventCreate) SetError(v string) *ScheduledEventCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableError(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetScheduleID sets the "schedule_id" field.
func (_c *ScheduledEventCreate) SetScheduleID(v string) *ScheduledEventCreate {
	_c.mutation.SetScheduleID(v)
	return _c
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableScheduleID(v *string) *ScheduledEventCreate {
	if v != nil {
		_c.SetScheduleID(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *ScheduledEventCreate) SetCreated(v time.Time) *ScheduledEventCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableCreated(v *time.Time) *ScheduledEventCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduledEventCreate) SetID(v uuid.UUID) *ScheduledEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ScheduledEventCreate) SetNillableID(v *uuid.UUID) *ScheduledEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ScheduledEventMutation object of the builder.
func (_c *ScheduledEventCreate) Mutation() *ScheduledEventMutation {
	return _c.mutation
}

// Save creates the ScheduledEvent in the database.
func (_c *ScheduledEventCreate) Save(ctx context.Context) (*ScheduledEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduledEventCreate) SaveX(ctx context.Context) *ScheduledEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduledEventCreate) defaults() {
	if _, ok := _c.mutation.AuthorityCeilingKind(); !ok {
		v := scheduledevent.DefaultAuthorityCeilingKind
		_c.mutation.SetAuthorityCeilingKind(v)
	}
	if _, ok := _c.mutation.AuthorityCeilingVersion(); !ok {
		v := scheduledevent.DefaultAuthorityCeilingVersion
		_c.mutation.SetAuthorityCeilingVersion(v)
	}
	if _, ok := _c.mutation.AuthorityCeilingBoundaryKind(); !ok {
		v := scheduledevent.DefaultAuthorityCeilingBoundaryKind
		_c.mutation.SetAuthorityCeilingBoundaryKind(v)
	}
	if _, ok := _c.mutation.AuthorityCeilingBoundaryProjectID(); !ok {
		v := scheduledevent.DefaultAuthorityCeilingBoundaryProjectID
		_c.mutation.SetAuthorityCeilingBoundaryProjectID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := scheduledevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := scheduledevent.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := scheduledevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduledEventCreate) check() error {
	if _, ok := _c.mutation.AuthorityCeilingKind(); !ok {
		return &ValidationError{Name: "authority_ceiling_kind", err: errors.New(`ent: missing required field "ScheduledEvent.authority_ceiling_kind"`)}
	}
	if _, ok := _c.mutation.AuthorityCeilingVersion(); !ok {
		return &ValidationError{Name: "authority_ceiling_version", err: errors.New(`ent: missing required field "ScheduledEvent.authority_ceiling_version"`)}
	}
	if _, ok := _c.mutation.AuthorityCeilingBoundaryKind(); !ok {
		return &ValidationError{Name: "authority_ceiling_boundary_kind", err: errors.New(`ent: missing required field "ScheduledEvent.authority_ceiling_boundary_kind"`)}
	}
	if _, ok := _c.mutation.AuthorityCeilingBoundaryProjectID(); !ok {
		return &ValidationError{Name: "authority_ceiling_boundary_project_id", err: errors.New(`ent: missing required field "ScheduledEvent.authority_ceiling_boundary_project_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ScheduledEvent.project_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "ScheduledEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := scheduledevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FireAt(); !ok {
		return &ValidationError{Name: "fire_at", err: errors.New(`ent: missing required field "ScheduledEvent.fire_at"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "ScheduledEvent.payload"`)}
	}
	if v, ok := _c.mutation.Payload(); ok {
		if err := scheduledevent.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.payload": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ScheduledEvent.status"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "ScheduledEvent.created"`)}
	}
	return nil
}

func (_c *ScheduledEventCreate) sqlSave(ctx context.Context) (*ScheduledEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduledEventCreate) createSpec() (*ScheduledEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduledEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scheduledevent.Table, sqlgraph.NewFieldSpec(scheduledevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.InitiatorPrincipalKind(); ok {
		_spec.SetField(scheduledevent.FieldInitiatorPrincipalKind, field.TypeString, value)
		_node.InitiatorPrincipalKind = &value
	}
	if value, ok := _c.mutation.InitiatorPrincipalID(); ok {
		_spec.SetField(scheduledevent.FieldInitiatorPrincipalID, field.TypeString, value)
		_node.InitiatorPrincipalID = &value
	}
	if value, ok := _c.mutation.InitiatorCredentialKind(); ok {
		_spec.SetField(scheduledevent.FieldInitiatorCredentialKind, field.TypeString, value)
		_node.InitiatorCredentialKind = &value
	}
	if value, ok := _c.mutation.InitiatorCredentialID(); ok {
		_spec.SetField(scheduledevent.FieldInitiatorCredentialID, field.TypeString, value)
		_node.InitiatorCredentialID = &value
	}
	if value, ok := _c.mutation.InitiatorCredentialSnapshot(); ok {
		_spec.SetField(scheduledevent.FieldInitiatorCredentialSnapshot, field.TypeString, value)
		_node.InitiatorCredentialSnapshot = &value
	}
	if value, ok := _c.mutation.AttributionVersion(); ok {
		_spec.SetField(scheduledevent.FieldAttributionVersion, field.TypeInt, value)
		_node.AttributionVersion = &value
	}
	if value, ok := _c.mutation.AuthorizationRevision(); ok {
		_spec.SetField(scheduledevent.FieldAuthorizationRevision, field.TypeInt, value)
		_node.AuthorizationRevision = &value
	}
	if value, ok := _c.mutation.AuthorityCeilingKind(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingKind, field.TypeString, value)
		_node.AuthorityCeilingKind = value
	}
	if value, ok := _c.mutation.AuthorityCeilingVersion(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingVersion, field.TypeInt32, value)
		_node.AuthorityCeilingVersion = value
	}
	if value, ok := _c.mutation.AuthorityCeilingPermissionIds(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingPermissionIds, field.TypeString, value)
		_node.AuthorityCeilingPermissionIds = &value
	}
	if value, ok := _c.mutation.AuthorityCeilingBoundaryKind(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingBoundaryKind, field.TypeString, value)
		_node.AuthorityCeilingBoundaryKind = value
	}
	if value, ok := _c.mutation.AuthorityCeilingBoundaryProjectID(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingBoundaryProjectID, field.TypeString, value)
		_node.AuthorityCeilingBoundaryProjectID = value
	}
	if value, ok := _c.mutation.AuthorityCeilingSourceExpiresAt(); ok {
		_spec.SetField(scheduledevent.FieldAuthorityCeilingSourceExpiresAt, field.TypeTime, value)
		_node.AuthorityCeilingSourceExpiresAt = &value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(scheduledevent.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(scheduledevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.FireAt(); ok {
		_spec.SetField(scheduledevent.FieldFireAt, field.TypeTime, value)
		_node.FireAt = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(scheduledevent.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(scheduledevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(scheduledevent.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.FiredAt(); ok {
		_spec.SetField(scheduledevent.FieldFiredAt, field.TypeTime, value)
		_node.FiredAt = &value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(scheduledevent.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.ScheduleID(); ok {
		_spec.SetField(scheduledevent.FieldScheduleID, field.TypeString, value)
		_node.ScheduleID = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(scheduledevent.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScheduledEvent.Create().
//		SetInitiatorPrincipalKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduledEventUpsert) {
//			SetInitiatorPrincipalKind(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduledEventCreate) OnConflict(opts ...sql.ConflictOption) *ScheduledEventUpsertOne {
	_c.conflict = opts
	return &ScheduledEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduledEventCreate) OnConflictColumns(columns ...string) *ScheduledEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduledEventUpsertOne{
		create: _c,
	}
}

type (
	// ScheduledEventUpsertOne is the builder for "upsert"-ing
	//  one ScheduledEvent node.
	ScheduledEventUpsertOne struct {
		create *ScheduledEventCreate
	}

	// ScheduledEventUpsert is the "OnConflict" setter.
	ScheduledEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetInitiatorPrincipalKind sets the "initiator_principal_kind" field.
func (u *ScheduledEventUpsert) SetInitiatorPrincipalKind(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldInitiatorPrincipalKind, v)
	return u
}

// UpdateInitiatorPrincipalKind sets the "initiator_principal_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateInitiatorPrincipalKind() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldInitiatorPrincipalKind)
	return u
}

// ClearInitiatorPrincipalKind clears the value of the "initiator_principal_kind" field.
func (u *ScheduledEventUpsert) ClearInitiatorPrincipalKind() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldInitiatorPrincipalKind)
	return u
}

// SetInitiatorPrincipalID sets the "initiator_principal_id" field.
func (u *ScheduledEventUpsert) SetInitiatorPrincipalID(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldInitiatorPrincipalID, v)
	return u
}

// UpdateInitiatorPrincipalID sets the "initiator_principal_id" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateInitiatorPrincipalID() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldInitiatorPrincipalID)
	return u
}

// ClearInitiatorPrincipalID clears the value of the "initiator_principal_id" field.
func (u *ScheduledEventUpsert) ClearInitiatorPrincipalID() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldInitiatorPrincipalID)
	return u
}

// SetInitiatorCredentialKind sets the "initiator_credential_kind" field.
func (u *ScheduledEventUpsert) SetInitiatorCredentialKind(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldInitiatorCredentialKind, v)
	return u
}

// UpdateInitiatorCredentialKind sets the "initiator_credential_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateInitiatorCredentialKind() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldInitiatorCredentialKind)
	return u
}

// ClearInitiatorCredentialKind clears the value of the "initiator_credential_kind" field.
func (u *ScheduledEventUpsert) ClearInitiatorCredentialKind() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldInitiatorCredentialKind)
	return u
}

// SetInitiatorCredentialID sets the "initiator_credential_id" field.
func (u *ScheduledEventUpsert) SetInitiatorCredentialID(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldInitiatorCredentialID, v)
	return u
}

// UpdateInitiatorCredentialID sets the "initiator_credential_id" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateInitiatorCredentialID() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldInitiatorCredentialID)
	return u
}

// ClearInitiatorCredentialID clears the value of the "initiator_credential_id" field.
func (u *ScheduledEventUpsert) ClearInitiatorCredentialID() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldInitiatorCredentialID)
	return u
}

// SetInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsert) SetInitiatorCredentialSnapshot(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldInitiatorCredentialSnapshot, v)
	return u
}

// UpdateInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateInitiatorCredentialSnapshot() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldInitiatorCredentialSnapshot)
	return u
}

// ClearInitiatorCredentialSnapshot clears the value of the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsert) ClearInitiatorCredentialSnapshot() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldInitiatorCredentialSnapshot)
	return u
}

// SetAttributionVersion sets the "attribution_version" field.
func (u *ScheduledEventUpsert) SetAttributionVersion(v int) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAttributionVersion, v)
	return u
}

// UpdateAttributionVersion sets the "attribution_version" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAttributionVersion() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAttributionVersion)
	return u
}

// AddAttributionVersion adds v to the "attribution_version" field.
func (u *ScheduledEventUpsert) AddAttributionVersion(v int) *ScheduledEventUpsert {
	u.Add(scheduledevent.FieldAttributionVersion, v)
	return u
}

// ClearAttributionVersion clears the value of the "attribution_version" field.
func (u *ScheduledEventUpsert) ClearAttributionVersion() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldAttributionVersion)
	return u
}

// SetAuthorizationRevision sets the "authorization_revision" field.
func (u *ScheduledEventUpsert) SetAuthorizationRevision(v int) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorizationRevision, v)
	return u
}

// UpdateAuthorizationRevision sets the "authorization_revision" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorizationRevision() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorizationRevision)
	return u
}

// AddAuthorizationRevision adds v to the "authorization_revision" field.
func (u *ScheduledEventUpsert) AddAuthorizationRevision(v int) *ScheduledEventUpsert {
	u.Add(scheduledevent.FieldAuthorizationRevision, v)
	return u
}

// ClearAuthorizationRevision clears the value of the "authorization_revision" field.
func (u *ScheduledEventUpsert) ClearAuthorizationRevision() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldAuthorizationRevision)
	return u
}

// SetAuthorityCeilingKind sets the "authority_ceiling_kind" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingKind(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingKind, v)
	return u
}

// UpdateAuthorityCeilingKind sets the "authority_ceiling_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingKind() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingKind)
	return u
}

// SetAuthorityCeilingVersion sets the "authority_ceiling_version" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingVersion(v int32) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingVersion, v)
	return u
}

// UpdateAuthorityCeilingVersion sets the "authority_ceiling_version" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingVersion() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingVersion)
	return u
}

// AddAuthorityCeilingVersion adds v to the "authority_ceiling_version" field.
func (u *ScheduledEventUpsert) AddAuthorityCeilingVersion(v int32) *ScheduledEventUpsert {
	u.Add(scheduledevent.FieldAuthorityCeilingVersion, v)
	return u
}

// SetAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingPermissionIds(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingPermissionIds, v)
	return u
}

// UpdateAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingPermissionIds() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingPermissionIds)
	return u
}

// ClearAuthorityCeilingPermissionIds clears the value of the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsert) ClearAuthorityCeilingPermissionIds() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldAuthorityCeilingPermissionIds)
	return u
}

// SetAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingBoundaryKind(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingBoundaryKind, v)
	return u
}

// UpdateAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingBoundaryKind() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingBoundaryKind)
	return u
}

// SetAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingBoundaryProjectID(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingBoundaryProjectID, v)
	return u
}

// UpdateAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingBoundaryProjectID() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingBoundaryProjectID)
	return u
}

// SetAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsert) SetAuthorityCeilingSourceExpiresAt(v time.Time) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldAuthorityCeilingSourceExpiresAt, v)
	return u
}

// UpdateAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldAuthorityCeilingSourceExpiresAt)
	return u
}

// ClearAuthorityCeilingSourceExpiresAt clears the value of the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsert) ClearAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldAuthorityCeilingSourceExpiresAt)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ScheduledEventUpsert) SetProjectID(v uuid.UUID) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateProjectID() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldProjectID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *ScheduledEventUpsert) SetEventType(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateEventType() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldEventType)
	return u
}

// SetFireAt sets the "fire_at" field.
func (u *ScheduledEventUpsert) SetFireAt(v time.Time) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldFireAt, v)
	return u
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateFireAt() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldFireAt)
	return u
}

// SetPayload sets the "payload" field.
func (u *ScheduledEventUpsert) SetPayload(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdatePayload() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldPayload)
	return u
}

// SetStatus sets the "status" field.
func (u *ScheduledEventUpsert) SetStatus(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateStatus() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ScheduledEventUpsert) SetCreatedBy(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateCreatedBy() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ScheduledEventUpsert) ClearCreatedBy() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldCreatedBy)
	return u
}

// SetFiredAt sets the "fired_at" field.
func (u *ScheduledEventUpsert) SetFiredAt(v time.Time) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldFiredAt, v)
	return u
}

// UpdateFiredAt sets the "fired_at" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateFiredAt() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldFiredAt)
	return u
}

// ClearFiredAt clears the value of the "fired_at" field.
func (u *ScheduledEventUpsert) ClearFiredAt() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldFiredAt)
	return u
}

// SetError sets the "error" field.
func (u *ScheduledEventUpsert) SetError(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateError() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *ScheduledEventUpsert) ClearError() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldError)
	return u
}

// SetScheduleID sets the "schedule_id" field.
func (u *ScheduledEventUpsert) SetScheduleID(v string) *ScheduledEventUpsert {
	u.Set(scheduledevent.FieldScheduleID, v)
	return u
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *ScheduledEventUpsert) UpdateScheduleID() *ScheduledEventUpsert {
	u.SetExcluded(scheduledevent.FieldScheduleID)
	return u
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (u *ScheduledEventUpsert) ClearScheduleID() *ScheduledEventUpsert {
	u.SetNull(scheduledevent.FieldScheduleID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scheduledevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduledEventUpsertOne) UpdateNewValues() *ScheduledEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(scheduledevent.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(scheduledevent.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScheduledEventUpsertOne) Ignore() *ScheduledEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduledEventUpsertOne) DoNothing() *ScheduledEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduledEventCreate.OnConflict
// documentation for more info.
func (u *ScheduledEventUpsertOne) Update(set func(*ScheduledEventUpsert)) *ScheduledEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduledEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetInitiatorPrincipalKind sets the "initiator_principal_kind" field.
func (u *ScheduledEventUpsertOne) SetInitiatorPrincipalKind(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorPrincipalKind(v)
	})
}

// UpdateInitiatorPrincipalKind sets the "initiator_principal_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateInitiatorPrincipalKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorPrincipalKind()
	})
}

// ClearInitiatorPrincipalKind clears the value of the "initiator_principal_kind" field.
func (u *ScheduledEventUpsertOne) ClearInitiatorPrincipalKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorPrincipalKind()
	})
}

// SetInitiatorPrincipalID sets the "initiator_principal_id" field.
func (u *ScheduledEventUpsertOne) SetInitiatorPrincipalID(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorPrincipalID(v)
	})
}

// UpdateInitiatorPrincipalID sets the "initiator_principal_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateInitiatorPrincipalID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorPrincipalID()
	})
}

// ClearInitiatorPrincipalID clears the value of the "initiator_principal_id" field.
func (u *ScheduledEventUpsertOne) ClearInitiatorPrincipalID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorPrincipalID()
	})
}

// SetInitiatorCredentialKind sets the "initiator_credential_kind" field.
func (u *ScheduledEventUpsertOne) SetInitiatorCredentialKind(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialKind(v)
	})
}

// UpdateInitiatorCredentialKind sets the "initiator_credential_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateInitiatorCredentialKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialKind()
	})
}

// ClearInitiatorCredentialKind clears the value of the "initiator_credential_kind" field.
func (u *ScheduledEventUpsertOne) ClearInitiatorCredentialKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialKind()
	})
}

// SetInitiatorCredentialID sets the "initiator_credential_id" field.
func (u *ScheduledEventUpsertOne) SetInitiatorCredentialID(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialID(v)
	})
}

// UpdateInitiatorCredentialID sets the "initiator_credential_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateInitiatorCredentialID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialID()
	})
}

// ClearInitiatorCredentialID clears the value of the "initiator_credential_id" field.
func (u *ScheduledEventUpsertOne) ClearInitiatorCredentialID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialID()
	})
}

// SetInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsertOne) SetInitiatorCredentialSnapshot(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialSnapshot(v)
	})
}

// UpdateInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateInitiatorCredentialSnapshot() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialSnapshot()
	})
}

// ClearInitiatorCredentialSnapshot clears the value of the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsertOne) ClearInitiatorCredentialSnapshot() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialSnapshot()
	})
}

// SetAttributionVersion sets the "attribution_version" field.
func (u *ScheduledEventUpsertOne) SetAttributionVersion(v int) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAttributionVersion(v)
	})
}

// AddAttributionVersion adds v to the "attribution_version" field.
func (u *ScheduledEventUpsertOne) AddAttributionVersion(v int) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAttributionVersion(v)
	})
}

// UpdateAttributionVersion sets the "attribution_version" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAttributionVersion() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAttributionVersion()
	})
}

// ClearAttributionVersion clears the value of the "attribution_version" field.
func (u *ScheduledEventUpsertOne) ClearAttributionVersion() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAttributionVersion()
	})
}

// SetAuthorizationRevision sets the "authorization_revision" field.
func (u *ScheduledEventUpsertOne) SetAuthorizationRevision(v int) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorizationRevision(v)
	})
}

// AddAuthorizationRevision adds v to the "authorization_revision" field.
func (u *ScheduledEventUpsertOne) AddAuthorizationRevision(v int) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAuthorizationRevision(v)
	})
}

// UpdateAuthorizationRevision sets the "authorization_revision" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorizationRevision() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorizationRevision()
	})
}

// ClearAuthorizationRevision clears the value of the "authorization_revision" field.
func (u *ScheduledEventUpsertOne) ClearAuthorizationRevision() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorizationRevision()
	})
}

// SetAuthorityCeilingKind sets the "authority_ceiling_kind" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingKind(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingKind(v)
	})
}

// UpdateAuthorityCeilingKind sets the "authority_ceiling_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingKind()
	})
}

// SetAuthorityCeilingVersion sets the "authority_ceiling_version" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingVersion(v int32) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingVersion(v)
	})
}

// AddAuthorityCeilingVersion adds v to the "authority_ceiling_version" field.
func (u *ScheduledEventUpsertOne) AddAuthorityCeilingVersion(v int32) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAuthorityCeilingVersion(v)
	})
}

// UpdateAuthorityCeilingVersion sets the "authority_ceiling_version" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingVersion() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingVersion()
	})
}

// SetAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingPermissionIds(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingPermissionIds(v)
	})
}

// UpdateAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingPermissionIds() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingPermissionIds()
	})
}

// ClearAuthorityCeilingPermissionIds clears the value of the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsertOne) ClearAuthorityCeilingPermissionIds() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorityCeilingPermissionIds()
	})
}

// SetAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingBoundaryKind(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingBoundaryKind(v)
	})
}

// UpdateAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingBoundaryKind() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingBoundaryKind()
	})
}

// SetAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingBoundaryProjectID(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingBoundaryProjectID(v)
	})
}

// UpdateAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingBoundaryProjectID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingBoundaryProjectID()
	})
}

// SetAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsertOne) SetAuthorityCeilingSourceExpiresAt(v time.Time) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingSourceExpiresAt(v)
	})
}

// UpdateAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingSourceExpiresAt()
	})
}

// ClearAuthorityCeilingSourceExpiresAt clears the value of the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsertOne) ClearAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorityCeilingSourceExpiresAt()
	})
}

// SetProjectID sets the "project_id" field.
func (u *ScheduledEventUpsertOne) SetProjectID(v uuid.UUID) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateProjectID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateProjectID()
	})
}

// SetEventType sets the "event_type" field.
func (u *ScheduledEventUpsertOne) SetEventType(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateEventType() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateEventType()
	})
}

// SetFireAt sets the "fire_at" field.
func (u *ScheduledEventUpsertOne) SetFireAt(v time.Time) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetFireAt(v)
	})
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateFireAt() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateFireAt()
	})
}

// SetPayload sets the "payload" field.
func (u *ScheduledEventUpsertOne) SetPayload(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdatePayload() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdatePayload()
	})
}

// SetStatus sets the "status" field.
func (u *ScheduledEventUpsertOne) SetStatus(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateStatus() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ScheduledEventUpsertOne) SetCreatedBy(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateCreatedBy() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ScheduledEventUpsertOne) ClearCreatedBy() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetFiredAt sets the "fired_at" field.
func (u *ScheduledEventUpsertOne) SetFiredAt(v time.Time) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetFiredAt(v)
	})
}

// UpdateFiredAt sets the "fired_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateFiredAt() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateFiredAt()
	})
}

// ClearFiredAt clears the value of the "fired_at" field.
func (u *ScheduledEventUpsertOne) ClearFiredAt() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearFiredAt()
	})
}

// SetError sets the "error" field.
func (u *ScheduledEventUpsertOne) SetError(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateError() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ScheduledEventUpsertOne) ClearError() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearError()
	})
}

// SetScheduleID sets the "schedule_id" field.
func (u *ScheduledEventUpsertOne) SetScheduleID(v string) *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetScheduleID(v)
	})
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertOne) UpdateScheduleID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateScheduleID()
	})
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (u *ScheduledEventUpsertOne) ClearScheduleID() *ScheduledEventUpsertOne {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearScheduleID()
	})
}

// Exec executes the query.
func (u *ScheduledEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduledEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduledEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScheduledEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ScheduledEventUpsertOne.ID is not supported by MySQL driver. Use ScheduledEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScheduledEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScheduledEventCreateBulk is the builder for creating many ScheduledEvent entities in bulk.
type ScheduledEventCreateBulk struct {
	config
	err      error
	builders []*ScheduledEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ScheduledEvent entities in the database.
func (_c *ScheduledEventCreateBulk) Save(ctx context.Context) ([]*ScheduledEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduledEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduledEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduledEventCreateBulk) SaveX(ctx context.Context) []*ScheduledEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScheduledEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduledEventUpsert) {
//			SetInitiatorPrincipalKind(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduledEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScheduledEventUpsertBulk {
	_c.conflict = opts
	return &ScheduledEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduledEventCreateBulk) OnConflictColumns(columns ...string) *ScheduledEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduledEventUpsertBulk{
		create: _c,
	}
}

// ScheduledEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ScheduledEvent nodes.
type ScheduledEventUpsertBulk struct {
	create *ScheduledEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scheduledevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduledEventUpsertBulk) UpdateNewValues() *ScheduledEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(scheduledevent.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(scheduledevent.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScheduledEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScheduledEventUpsertBulk) Ignore() *ScheduledEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduledEventUpsertBulk) DoNothing() *ScheduledEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduledEventCreateBulk.OnConflict
// documentation for more info.
func (u *ScheduledEventUpsertBulk) Update(set func(*ScheduledEventUpsert)) *ScheduledEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduledEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetInitiatorPrincipalKind sets the "initiator_principal_kind" field.
func (u *ScheduledEventUpsertBulk) SetInitiatorPrincipalKind(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorPrincipalKind(v)
	})
}

// UpdateInitiatorPrincipalKind sets the "initiator_principal_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateInitiatorPrincipalKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorPrincipalKind()
	})
}

// ClearInitiatorPrincipalKind clears the value of the "initiator_principal_kind" field.
func (u *ScheduledEventUpsertBulk) ClearInitiatorPrincipalKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorPrincipalKind()
	})
}

// SetInitiatorPrincipalID sets the "initiator_principal_id" field.
func (u *ScheduledEventUpsertBulk) SetInitiatorPrincipalID(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorPrincipalID(v)
	})
}

// UpdateInitiatorPrincipalID sets the "initiator_principal_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateInitiatorPrincipalID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorPrincipalID()
	})
}

// ClearInitiatorPrincipalID clears the value of the "initiator_principal_id" field.
func (u *ScheduledEventUpsertBulk) ClearInitiatorPrincipalID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorPrincipalID()
	})
}

// SetInitiatorCredentialKind sets the "initiator_credential_kind" field.
func (u *ScheduledEventUpsertBulk) SetInitiatorCredentialKind(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialKind(v)
	})
}

// UpdateInitiatorCredentialKind sets the "initiator_credential_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateInitiatorCredentialKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialKind()
	})
}

// ClearInitiatorCredentialKind clears the value of the "initiator_credential_kind" field.
func (u *ScheduledEventUpsertBulk) ClearInitiatorCredentialKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialKind()
	})
}

// SetInitiatorCredentialID sets the "initiator_credential_id" field.
func (u *ScheduledEventUpsertBulk) SetInitiatorCredentialID(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialID(v)
	})
}

// UpdateInitiatorCredentialID sets the "initiator_credential_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateInitiatorCredentialID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialID()
	})
}

// ClearInitiatorCredentialID clears the value of the "initiator_credential_id" field.
func (u *ScheduledEventUpsertBulk) ClearInitiatorCredentialID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialID()
	})
}

// SetInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsertBulk) SetInitiatorCredentialSnapshot(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetInitiatorCredentialSnapshot(v)
	})
}

// UpdateInitiatorCredentialSnapshot sets the "initiator_credential_snapshot" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateInitiatorCredentialSnapshot() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateInitiatorCredentialSnapshot()
	})
}

// ClearInitiatorCredentialSnapshot clears the value of the "initiator_credential_snapshot" field.
func (u *ScheduledEventUpsertBulk) ClearInitiatorCredentialSnapshot() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearInitiatorCredentialSnapshot()
	})
}

// SetAttributionVersion sets the "attribution_version" field.
func (u *ScheduledEventUpsertBulk) SetAttributionVersion(v int) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAttributionVersion(v)
	})
}

// AddAttributionVersion adds v to the "attribution_version" field.
func (u *ScheduledEventUpsertBulk) AddAttributionVersion(v int) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAttributionVersion(v)
	})
}

// UpdateAttributionVersion sets the "attribution_version" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAttributionVersion() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAttributionVersion()
	})
}

// ClearAttributionVersion clears the value of the "attribution_version" field.
func (u *ScheduledEventUpsertBulk) ClearAttributionVersion() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAttributionVersion()
	})
}

// SetAuthorizationRevision sets the "authorization_revision" field.
func (u *ScheduledEventUpsertBulk) SetAuthorizationRevision(v int) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorizationRevision(v)
	})
}

// AddAuthorizationRevision adds v to the "authorization_revision" field.
func (u *ScheduledEventUpsertBulk) AddAuthorizationRevision(v int) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAuthorizationRevision(v)
	})
}

// UpdateAuthorizationRevision sets the "authorization_revision" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorizationRevision() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorizationRevision()
	})
}

// ClearAuthorizationRevision clears the value of the "authorization_revision" field.
func (u *ScheduledEventUpsertBulk) ClearAuthorizationRevision() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorizationRevision()
	})
}

// SetAuthorityCeilingKind sets the "authority_ceiling_kind" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingKind(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingKind(v)
	})
}

// UpdateAuthorityCeilingKind sets the "authority_ceiling_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingKind()
	})
}

// SetAuthorityCeilingVersion sets the "authority_ceiling_version" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingVersion(v int32) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingVersion(v)
	})
}

// AddAuthorityCeilingVersion adds v to the "authority_ceiling_version" field.
func (u *ScheduledEventUpsertBulk) AddAuthorityCeilingVersion(v int32) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.AddAuthorityCeilingVersion(v)
	})
}

// UpdateAuthorityCeilingVersion sets the "authority_ceiling_version" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingVersion() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingVersion()
	})
}

// SetAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingPermissionIds(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingPermissionIds(v)
	})
}

// UpdateAuthorityCeilingPermissionIds sets the "authority_ceiling_permission_ids" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingPermissionIds() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingPermissionIds()
	})
}

// ClearAuthorityCeilingPermissionIds clears the value of the "authority_ceiling_permission_ids" field.
func (u *ScheduledEventUpsertBulk) ClearAuthorityCeilingPermissionIds() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorityCeilingPermissionIds()
	})
}

// SetAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingBoundaryKind(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingBoundaryKind(v)
	})
}

// UpdateAuthorityCeilingBoundaryKind sets the "authority_ceiling_boundary_kind" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingBoundaryKind() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingBoundaryKind()
	})
}

// SetAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingBoundaryProjectID(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingBoundaryProjectID(v)
	})
}

// UpdateAuthorityCeilingBoundaryProjectID sets the "authority_ceiling_boundary_project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingBoundaryProjectID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingBoundaryProjectID()
	})
}

// SetAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsertBulk) SetAuthorityCeilingSourceExpiresAt(v time.Time) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetAuthorityCeilingSourceExpiresAt(v)
	})
}

// UpdateAuthorityCeilingSourceExpiresAt sets the "authority_ceiling_source_expires_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateAuthorityCeilingSourceExpiresAt()
	})
}

// ClearAuthorityCeilingSourceExpiresAt clears the value of the "authority_ceiling_source_expires_at" field.
func (u *ScheduledEventUpsertBulk) ClearAuthorityCeilingSourceExpiresAt() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearAuthorityCeilingSourceExpiresAt()
	})
}

// SetProjectID sets the "project_id" field.
func (u *ScheduledEventUpsertBulk) SetProjectID(v uuid.UUID) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateProjectID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateProjectID()
	})
}

// SetEventType sets the "event_type" field.
func (u *ScheduledEventUpsertBulk) SetEventType(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateEventType() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateEventType()
	})
}

// SetFireAt sets the "fire_at" field.
func (u *ScheduledEventUpsertBulk) SetFireAt(v time.Time) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetFireAt(v)
	})
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateFireAt() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateFireAt()
	})
}

// SetPayload sets the "payload" field.
func (u *ScheduledEventUpsertBulk) SetPayload(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdatePayload() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdatePayload()
	})
}

// SetStatus sets the "status" field.
func (u *ScheduledEventUpsertBulk) SetStatus(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateStatus() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ScheduledEventUpsertBulk) SetCreatedBy(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateCreatedBy() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ScheduledEventUpsertBulk) ClearCreatedBy() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetFiredAt sets the "fired_at" field.
func (u *ScheduledEventUpsertBulk) SetFiredAt(v time.Time) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetFiredAt(v)
	})
}

// UpdateFiredAt sets the "fired_at" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateFiredAt() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateFiredAt()
	})
}

// ClearFiredAt clears the value of the "fired_at" field.
func (u *ScheduledEventUpsertBulk) ClearFiredAt() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearFiredAt()
	})
}

// SetError sets the "error" field.
func (u *ScheduledEventUpsertBulk) SetError(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateError() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ScheduledEventUpsertBulk) ClearError() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearError()
	})
}

// SetScheduleID sets the "schedule_id" field.
func (u *ScheduledEventUpsertBulk) SetScheduleID(v string) *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.SetScheduleID(v)
	})
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *ScheduledEventUpsertBulk) UpdateScheduleID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.UpdateScheduleID()
	})
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (u *ScheduledEventUpsertBulk) ClearScheduleID() *ScheduledEventUpsertBulk {
	return u.Update(func(s *ScheduledEventUpsert) {
		s.ClearScheduleID()
	})
}

// Exec executes the query.
func (u *ScheduledEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScheduledEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduledEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduledEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
