// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/secret"
	"github.com/google/uuid"
)

// SecretCreate is the builder for creating a Secret entity.
type SecretCreate struct {
	config
	mutation *SecretMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *SecretCreate) SetKey(v string) *SecretCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEncryptedValue sets the "encrypted_value" field.
func (_c *SecretCreate) SetEncryptedValue(v string) *SecretCreate {
	_c.mutation.SetEncryptedValue(v)
	return _c
}

// SetSecretRef sets the "secret_ref" field.
func (_c *SecretCreate) SetSecretRef(v string) *SecretCreate {
	_c.mutation.SetSecretRef(v)
	return _c
}

// SetNillableSecretRef sets the "secret_ref" field if the given value is not nil.
func (_c *SecretCreate) SetNillableSecretRef(v *string) *SecretCreate {
	if v != nil {
		_c.SetSecretRef(*v)
	}
	return _c
}

// SetSecretType sets the "secret_type" field.
func (_c *SecretCreate) SetSecretType(v secret.SecretType) *SecretCreate {
	_c.mutation.SetSecretType(v)
	return _c
}

// SetNillableSecretType sets the "secret_type" field if the given value is not nil.
func (_c *SecretCreate) SetNillableSecretType(v *secret.SecretType) *SecretCreate {
	if v != nil {
		_c.SetSecretType(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *SecretCreate) SetTarget(v string) *SecretCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *SecretCreate) SetNillableTarget(v *string) *SecretCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *SecretCreate) SetScope(v string) *SecretCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *SecretCreate) SetScopeID(v string) *SecretCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SecretCreate) SetDescription(v string) *SecretCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SecretCreate) SetNillableDescription(v *string) *SecretCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetInjectionMode sets the "injection_mode" field.
func (_c *SecretCreate) SetInjectionMode(v secret.InjectionMode) *SecretCreate {
	_c.mutation.SetInjectionMode(v)
	return _c
}

// SetNillableInjectionMode sets the "injection_mode" field if the given value is not nil.
func (_c *SecretCreate) SetNillableInjectionMode(v *secret.InjectionMode) *SecretCreate {
	if v != nil {
		_c.SetInjectionMode(*v)
	}
	return _c
}

// SetAllowProgeny sets the "allow_progeny" field.
func (_c *SecretCreate) SetAllowProgeny(v bool) *SecretCreate {
	_c.mutation.SetAllowProgeny(v)
	return _c
}

// SetNillableAllowProgeny sets the "allow_progeny" field if the given value is not nil.
func (_c *SecretCreate) SetNillableAllowProgeny(v *bool) *SecretCreate {
	if v != nil {
		_c.SetAllowProgeny(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *SecretCreate) SetVersion(v int) *SecretCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SecretCreate) SetNillableVersion(v *int) *SecretCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SecretCreate) SetCreatedBy(v string) *SecretCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreatedBy(v *string) *SecretCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SecretCreate) SetUpdatedBy(v string) *SecretCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdatedBy(v *string) *SecretCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *SecretCreate) SetCreated(v time.Time) *SecretCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreated(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *SecretCreate) SetUpdated(v time.Time) *SecretCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdated(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SecretCreate) SetID(v uuid.UUID) *SecretCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SecretCreate) SetNillableID(v *uuid.UUID) *SecretCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SecretMutation object of the builder.
func (_c *SecretCreate) Mutation() *SecretMutation {
	return _c.mutation
}

// Save creates the Secret in the database.
func (_c *SecretCreate) Save(ctx context.Context) (*Secret, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecretCreate) SaveX(ctx context.Context) *Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecretCreate) defaults() {
	if _, ok := _c.mutation.SecretType(); !ok {
		v := secret.DefaultSecretType
		_c.mutation.SetSecretType(v)
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		v := secret.DefaultInjectionMode
		_c.mutation.SetInjectionMode(v)
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		v := secret.DefaultAllowProgeny
		_c.mutation.SetAllowProgeny(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := secret.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := secret.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := secret.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := secret.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecretCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Secret.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := secret.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Secret.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedValue(); !ok {
		return &ValidationError{Name: "encrypted_value", err: errors.New(`ent: missing required field "Secret.encrypted_value"`)}
	}
	if _, ok := _c.mutation.SecretType(); !ok {
		return &ValidationError{Name: "secret_type", err: errors.New(`ent: missing required field "Secret.secret_type"`)}
	}
	if v, ok := _c.mutation.SecretType(); ok {
		if err := secret.SecretTypeValidator(v); err != nil {
			return &ValidationError{Name: "secret_type", err: fmt.Errorf(`ent: validator failed for field "Secret.secret_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Secret.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := secret.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Secret.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "Secret.scope_id"`)}
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		return &ValidationError{Name: "injection_mode", err: errors.New(`ent: missing required field "Secret.injection_mode"`)}
	}
	if v, ok := _c.mutation.InjectionMode(); ok {
		if err := secret.InjectionModeValidator(v); err != nil {
			return &ValidationError{Name: "injection_mode", err: fmt.Errorf(`ent: validator failed for field "Secret.injection_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		return &ValidationError{Name: "allow_progeny", err: errors.New(`ent: missing required field "Secret.allow_progeny"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Secret.version"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Secret.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Secret.updated"`)}
	}
	return nil
}

func (_c *SecretCreate) sqlSave(ctx context.Context) (*Secret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecretCreate) createSpec() (*Secret, *sqlgraph.CreateSpec) {
	var (
		_node = &Secret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(secret.Table, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(secret.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.EncryptedValue(); ok {
		_spec.SetField(secret.FieldEncryptedValue, field.TypeString, value)
		_node.EncryptedValue = value
	}
	if value, ok := _c.mutation.SecretRef(); ok {
		_spec.SetField(secret.FieldSecretRef, field.TypeString, value)
		_node.SecretRef = value
	}
	if value, ok := _c.mutation.SecretType(); ok {
		_spec.SetField(secret.FieldSecretType, field.TypeEnum, value)
		_node.SecretType = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(secret.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(secret.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(secret.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(secret.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.InjectionMode(); ok {
		_spec.SetField(secret.FieldInjectionMode, field.TypeEnum, value)
		_node.InjectionMode = value
	}
	if value, ok := _c.mutation.AllowProgeny(); ok {
		_spec.SetField(secret.FieldAllowProgeny, field.TypeBool, value)
		_node.AllowProgeny = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(secret.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(secret.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(secret.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(secret.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(secret.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// SecretCreateBulk is the builder for creating many Secret entities in bulk.
type SecretCreateBulk struct {
	config
	err      error
	builders []*SecretCreate
}

// Save creates the Secret entities in the database.
func (_c *SecretCreateBulk) Save(ctx context.Context) ([]*Secret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Secret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecretCreateBulk) SaveX(ctx context.Context) []*Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
