// Code generated by ent, DO NOT EDIT.

package conversationparticipant

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the conversationparticipant type in the database.
	Label = "conversation_participant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldPrincipalKind holds the string denoting the principal_kind field in the database.
	FieldPrincipalKind = "principal_kind"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// FieldLeftAt holds the string denoting the left_at field in the database.
	FieldLeftAt = "left_at"
	// Table holds the table name of the conversationparticipant in the database.
	Table = "conversation_participants"
)

// Columns holds all SQL columns for conversationparticipant fields.
var Columns = []string{
	FieldID,
	FieldConversationID,
	FieldPrincipalKind,
	FieldPrincipalID,
	FieldRole,
	FieldJoinedAt,
	FieldLeftAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrincipalIDValidator is a validator for the "principal_id" field. It is called by the builders before save.
	PrincipalIDValidator func(string) error
	// DefaultJoinedAt holds the default value on creation for the "joined_at" field.
	DefaultJoinedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PrincipalKind defines the type for the "principal_kind" enum field.
type PrincipalKind string

// PrincipalKind values.
const (
	PrincipalKindUser  PrincipalKind = "user"
	PrincipalKindAgent PrincipalKind = "agent"
)

func (pk PrincipalKind) String() string {
	return string(pk)
}

// PrincipalKindValidator is a validator for the "principal_kind" field enum values. It is called by the builders before save.
func PrincipalKindValidator(pk PrincipalKind) error {
	switch pk {
	case PrincipalKindUser, PrincipalKindAgent:
		return nil
	default:
		return fmt.Errorf("conversationparticipant: invalid enum value for principal_kind field: %q", pk)
	}
}

// Role defines the type for the "role" enum field.
type Role string

// RoleMember is the default value of the Role enum.
const DefaultRole = RoleMember

// Role values.
const (
	RoleMember   Role = "member"
	RoleObserver Role = "observer"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleMember, RoleObserver:
		return nil
	default:
		return fmt.Errorf("conversationparticipant: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the ConversationParticipant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByPrincipalKind orders the results by the principal_kind field.
func ByPrincipalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalKind, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByLeftAt orders the results by the left_at field.
func ByLeftAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeftAt, opts...).ToFunc()
}
