// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authzop

// hubOperations lists the catalog operations for hub administration, configuration and quotas.
var hubOperations = []OperationSpec{
	// =====================================================================
	// Domain: hub — hub administration (HIGH-RISK)
	// =====================================================================
	{
		ID:          "hub.authreset",
		Domain:      "hub",
		Description: "Reset all agent authentication credentials (emergency action)",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/agents/reset-auth-all", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.auth_reset.execute",
		Effects:          []SecurityEffect{EffectRevokeAuthority},
		DelegationKind:   DelegationNone,
		Governance: &GovernancePolicy{
			Kind:        GovernancePeerSuperior,
			Description: "Mass auth reset is a drastic authority revocation requiring hub admin governance",
		},
		AuthorityEval: AuthorityEvalNone,
		AuditObligation: &AuditObligation{
			EventType:     "hub.authreset",
			ContextFields: []string{"actor_id"},
			BeforeFields:  []string{"agent_count"},
			Atomic:        true,
		},
		DenialCodes: []DenialCode{DenialForbidden},
		TestRefs: []TestRef{
			{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"},
			{Package: "pkg/hub", Function: "TestAdminResetAuthAll_TokenRefused"},
			{Package: "pkg/hub", Function: "TestAdminResetAuthAll_SessionPassesGuard"},
			{Package: "pkg/hub", Function: "TestAdminResetAuthAll_DevCredentialPassesGuard"},
		},
		Bearer: SessionOnly(ReasonSessionRecovery),
	},

	{
		ID:          "hub.authreset.reissue",
		Domain:      "hub",
		Description: "Re-issue an agent's role scopes from its delegator's current authority (dispatched from POST .../agents/{id}/reset-auth when reissue_scopes is set; hub super-admin only)",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointInternalDispatch, Pattern: "handleAgentResetAuth:reissue-scopes"},
		},
		Principals:            []PrincipalKind{PrincipalUser},
		Credentials:           []CredentialKind{CredentialSessionJWT},
		ResourceResolver:      "hub-scoped",
		BasePermission:        "hub.auth_reset.execute",
		Effects:               []SecurityEffect{EffectChangeAuthority, EffectRevokeAuthority, EffectMintCredential},
		DelegationKind:        DelegationConditionalIncrease,
		DelegationDescription: "The re-issued role and scopes are checked with CanDelegate against the delegator's live grant (never the operator's), and the role is never raised",
		Governance: &GovernancePolicy{
			Kind:        GovernancePeerSuperior,
			Description: "Re-recording an agent's delegated authority and revoking its credentials is a hub super-admin action",
		},
		AuthorityEval: AuthorityEvalBeforeAndAfter,
		AuditObligation: &AuditObligation{
			EventType:     "agent_scopes_reissued",
			ContextFields: []string{"actor_id"},
			BeforeFields:  []string{"role_before", "edge_replaced"},
			AfterFields:   []string{"role_after", "edge_new", "scopes_added", "scopes_removed", "credentials_revoked"},
			Atomic:        true,
		},
		DenialCodes: []DenialCode{DenialForbidden},
		TestRefs: []TestRef{
			{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"},
			{Package: "pkg/hub", Function: "TestScopeReissue_OperatorRefusals"},
			{Package: "pkg/hub", Function: "TestScopeReissue_UserDelegatorFailClosed"},
			{Package: "pkg/hub", Function: "TestScopeReissue_UserDelegatorLookupFault"},
			{Package: "pkg/hub", Function: "TestScopeReissue_SessionRootedEqualsCreateToday"},
			{Package: "pkg/hub", Function: "TestScopeReissue_SessionRootedEqualsCreateTodayAfterChange"},
		},
		Bearer: SessionOnly(ReasonGovernancePending),
	},
	{
		ID:          "hub.authreset.reissueall",
		Domain:      "hub",
		Description: "Re-issue every agent's role scopes from its delegator's current authority (dispatched from POST /api/v1/admin/agents/reset-auth-all when reissue_scopes is set; dry run by default; hub super-admin only)",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointInternalDispatch, Pattern: "handleAdminResetAuthAll:reissue-scopes"},
		},
		Principals:            []PrincipalKind{PrincipalUser},
		Credentials:           []CredentialKind{CredentialSessionJWT},
		ResourceResolver:      "hub-scoped",
		BasePermission:        "hub.auth_reset.execute",
		Effects:               []SecurityEffect{EffectChangeAuthority, EffectRevokeAuthority, EffectMintCredential},
		DelegationKind:        DelegationConditionalIncrease,
		DelegationDescription: "Each agent's re-issued role and scopes are checked with CanDelegate against its own delegator's live grant (never the operator's), and no role is raised",
		Governance: &GovernancePolicy{
			Kind:        GovernancePeerSuperior,
			Description: "A hub-wide re-issue of delegated authority is a hub super-admin action; each agent is re-issued and audited on its own",
		},
		AuthorityEval: AuthorityEvalBeforeAndAfter,
		AuditObligation: &AuditObligation{
			EventType:              "agent_scopes_reissue_batch",
			ContextFields:          []string{"actor_id"},
			BeforeFields:           []string{"total"},
			AfterFields:            []string{"dry_run", "succeeded", "noop", "refused", "push_failed"},
			Atomic:                 false,
			NonAtomicJustification: "Each agent's re-issue commits with its own agent_scopes_reissued row in one transaction; the batch row is a summary written after the run with a fresh context, and the response reports batch_audit_recorded=false if it could not be written",
		},
		DenialCodes: []DenialCode{DenialForbidden},
		TestRefs: []TestRef{
			{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"},
			{Package: "pkg/hub", Function: "TestScopeReissueBulk_OperatorRefusals"},
		},
		Bearer: SessionOnly(ReasonGovernancePending),
	},

	// =====================================================================
	// Domain: hub — hub admin reads and configuration
	// =====================================================================
	{
		ID:          "hub.config.read",
		Domain:      "hub",
		Description: "Read server configuration and schema",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config/schema", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.config.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestHubConfigToken_ProjectBoundaryDenied"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.config.update",
		Domain:      "hub",
		Description: "Update server configuration sections. The route guard checks hub.config.read, so a token needs hub_config:read and hub_config:update, and writes configuration keys only",
		EntryPoints: []EntryPoint{
			// handleAdminServerConfig (admin_settings.go) accepts PUT,
			// PATCH, and POST on the bare server-config resource.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config", Method: "PATCH"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config", Method: "POST"},
			// handleAdminServerConfigSectionReset (admin_settings.go) is a
			// second, DELETE-only entry point on the same permission
			// (route_metadata.go: admin.serverConfig.sections.byId) that
			// resets one managed section to its bootstrap material.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/server-config/sections/{id}", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.config.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestServerConfigUpdate_AuthorityKeysRefuseTokens"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.messaging.update",
		Domain:      "hub",
		Description: "Read and update messaging configuration switches",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/messaging", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/messaging", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.messaging.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.profiling.update",
		Domain:      "hub",
		Description: "Read and update the profiling switches (session only)",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/profiling", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/profiling", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.config.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestAdminProfiling_TokenRefused"}},
		Bearer:           SessionOnly(ReasonHostOperations),
	},
	{
		ID:          "hub.experiments.update",
		Domain:      "hub",
		Description: "Read and update hub-wide experiment overrides",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/experiments", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/experiments", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/experiments", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.experiments.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.conduitgrantkeys.rotate",
		Domain:      "hub",
		Description: "Rotate the conduit grant signing key (kids and timestamps only in the response)",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/conduit/grant-keys/rotate", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.conduit_grant_keys.execute",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestAdminConduitGrantKeyRotate"}},
		Bearer:           SessionOnly(ReasonCredentialManagement),
	},
	{
		ID:          "hub.maintenance.execute",
		Domain:      "hub",
		Description: "Execute maintenance operations including migrations and restarts",
		EntryPoints: []EntryPoint{
			// handleAdminMaintenanceOps (admin_maintenance.go): bare
			// "/operations" and "/operations/{id}" are GET-only (list and
			// get); execution is "/operations/{id}/run", POST-only.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/operations", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/operations/{id}", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/operations/{id}/run", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/restart", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/check-updates", Method: "POST"},
			// handleAdminMaintenanceMigrations (admin_maintenance.go) only
			// accepts "/migrations/{id}/run", not a bare "/migrations/{id}".
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/migrations/{id}/run", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/update-available", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance/update-available", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.maintenance.execute",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "hub.adminmode.update",
		Domain:      "hub",
		Description: "Toggle admin/maintenance mode",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/maintenance", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.admin_mode.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "hub.allowlist.update",
		Domain:      "hub",
		Description: "Manage the platform email allow list",
		EntryPoints: []EntryPoint{
			// handleAdminAllowList (admin_allow_list.go) accepts GET and
			// POST (add), not PUT. handleAdminAllowListByEmail is
			// DELETE-only; there is no PUT on the by-email route.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/allow-list", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/allow-list", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/allow-list/{email}", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.allow_list.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		// conflict: email already on the list, user not in invited status,
		// or (DELETE) the user's role bindings changed concurrently.
		// last_owner: the DELETE entry point applies the same
		// last-project-owner guard and binding cascade as user.admin.delete.
		DenialCodes: []DenialCode{DenialForbidden, DenialLastOwner, DenialConflict},
		TestRefs:    []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "hub.health.read",
		Domain:      "hub",
		Description: "Read platform health summary and GCP quota status",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/health/summary", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/gcp-quota", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.health.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.diagnostics.read",
		Domain:      "hub",
		Description: "Read diagnostic logs, the diagnostic log stream and messaging divergence data. The log stream re-checks a token credential on every heartbeat and ends once the token stops validating or loses hub.diagnostics.read",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/diagnostics/logs", Method: "GET"},
			// The live handler (handleDiagnosticsLogsStream,
			// pkg/hub/handlers_diagnostics.go) sets
			// "Content-Type: text/event-stream" and streams incrementally;
			// it is an SSE entry point, not a plain HTTP route. Pinned by
			// TestDiagnosticsLogsStreamCatalogMatchesRoute
			// (authzop/drift_test.go).
			{Kind: EntryPointSSE, Pattern: "/api/v1/admin/diagnostics/logs/stream", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/messaging/divergence", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.diagnostics.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestDiagnosticsLogStream_EndsWhenTokenStopsValidating"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.scheduler.read",
		Domain:      "hub",
		Description: "Read scheduler status and configuration",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/scheduler", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.scheduler.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.projectdefaults.read",
		Domain:      "hub",
		Description: "Read project default settings",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/project-defaults", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.project_defaults.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.lifecyclehooks.read",
		Domain:      "hub",
		Description: "Read lifecycle hook definitions",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/lifecycle-hooks", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/lifecycle-hooks/{id}", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.lifecycle_hooks.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.projectdefaults.update",
		Domain:      "hub",
		Description: "Update project default settings. The route guard checks hub.project_defaults.read, so a token needs hub_project_defaults:read and hub_project_defaults:update, and writes configuration keys only",
		EntryPoints: []EntryPoint{
			// handleAdminProjectDefaults (admin_project_defaults.go)
			// accepts PUT, PATCH and POST.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/project-defaults", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/project-defaults", Method: "PATCH"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/project-defaults", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.project_defaults.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestProjectDefaultsUpdate_EveryKeyClassifiedForTokens"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.lifecyclehooks.update",
		Domain:      "hub",
		Description: "Create, update, delete and activate hub lifecycle hooks and hub pre-start hooks. The admin lifecycle-hook route guard checks hub.lifecycle_hooks.read, so a token writing there needs hub_lifecycle_hooks:read and hub_lifecycle_hooks:update",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/lifecycle-hooks", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/lifecycle-hooks/{id}", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/lifecycle-hooks/{id}", Method: "DELETE"},
			// handleHubPreStartHooks and handleHubPreStartHookByID
			// (hub_pre_start_hook_handlers.go) authorize every write
			// through requireHubAdmin.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/pre-start-hooks", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/pre-start-hooks/{id}", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/pre-start-hooks/{id}/activate", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/pre-start-hooks/{id}", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.lifecycle_hooks.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.settings.update",
		Domain:      "hub",
		Description: "Set the user-defined hub injected skills; system entries are preserved",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/hub/settings/injected-skills", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.settings.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.validate.execute",
		Domain:      "hub",
		Description: "Validate resource definitions against schema",
		EntryPoints: []EntryPoint{
			// handleAdminValidateResources (admin_validate.go) is GET-only.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/validate-resources", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.validate.execute",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.integrations.read",
		Domain:      "hub",
		Description: "Read integration configurations, the available-integrations list, integration health and integration update status",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/available", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/health", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/update/{id}", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.integrations.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.integrations.update",
		Domain:      "hub",
		Description: "Update an integration's settings and restart an integration. The route guard checks hub.integrations.read, so a token needs hub_integrations:read and hub_integrations:update. A config update that sets secrets or any settings key outside the configuration set requires an interactive session",
		EntryPoints: []EntryPoint{
			// handleAdminIntegrationByName (handlers_integrations.go)
			// checks hub.integrations.update for every write.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/config", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/restart", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.integrations.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestIntegrationConfigUpdate_SecretsSessionOnlyForTokens"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.integrations.install",
		Domain:      "hub",
		Description: "Install an integration and start an integration update; both build and install code on the hub host, so an interactive session only",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/install", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/{name}/update", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.integrations.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestIntegrationInstall_SessionOnlyForTokens"}},
		Bearer:           SessionOnly(ReasonHostOperations),
	},
	{
		ID:          "hub.teamsmanifest.read",
		Domain:      "hub",
		Description: "Read Teams integration manifest",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/integrations/teams/manifest", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.teams_manifest.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.metrics.read",
		Domain:      "hub",
		Description: "Read metrics dashboard data",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/metrics/{name}", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/metrics-dashboard", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.metrics.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestMetricsDashboard_RequiresMetricsSelector"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},

	// =====================================================================
	// Domain: hub — GitHub App integration (D4 route guard conversion)
	// =====================================================================
	{
		ID:          "hub.githubapp.read",
		Domain:      "hub",
		Description: "Read GitHub App configuration and installations",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations/{id}", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.github_app.read",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.githubapp.update",
		Domain:      "hub",
		Description: "Create, update and delete GitHub App installations, discover installations and sync permissions",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations/{id}", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations/{id}", Method: "DELETE"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/installations/discover", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app/sync-permissions", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT, CredentialScopedUAT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.github_app.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDispositionMatrix_CatalogEntryPoints"}},
		Bearer:           AdmitOn(BearerTargetHubInstance, BearerBoundaryHub),
	},
	{
		ID:          "hub.githubapp.config.update",
		Domain:      "hub",
		Description: "Update the GitHub App configuration, which sets the hub's app credentials; an interactive session only",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/github-app", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "hub.github_app.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestGitHubAppConfigUpdate_SessionOnlyForTokens"}},
		Bearer:           SessionOnly(ReasonCredentialManagement),
	},

	// =====================================================================
	// Domain: quota — quota/limits management
	// =====================================================================
	{
		ID:          "quota.read",
		Domain:      "quota",
		Description: "Read limit definitions, entitlements, and usage",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits/{id}", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/entitlements/{id}", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/usage", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/usage/{limit}", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "quota.read",
		Effects:          []SecurityEffect{EffectReadOne, EffectListScoped},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "quota.create",
		Domain:      "quota",
		Description: "Create limit definitions and entitlement bindings",
		EntryPoints: []EntryPoint{
			// handleAdminEntitlementByID (handlers_quota.go) is GET/PUT/
			// DELETE only; creation is nested under its parent limit
			// (handleLimitEntitlements), not the flat entitlements route.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits", Method: "POST"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits/{id}/entitlements", Method: "POST"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "quota.create",
		Effects:          []SecurityEffect{EffectCreateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "quota.update",
		Domain:      "quota",
		Description: "Update limit definitions and entitlement bindings",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits/{id}", Method: "PUT"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/entitlements/{id}", Method: "PUT"},
			// ptone/scion#2061 P2, ptone/scion#2177: writing a per-broker
			// setting (design.md §5.3/§5.4) requires the key's declared
			// permission; maxAgents (pkg/hub/brokersettings) declares
			// quota.update, same as every other quota admin write.
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/runtime-brokers/{id}/settings", Method: "PUT"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "quota.update",
		Effects:          []SecurityEffect{EffectUpdateResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		DenialCodes:      []DenialCode{DenialForbidden},
		TestRefs:         []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "quota.delete",
		Domain:      "quota",
		Description: "Delete limit definitions and entitlement bindings",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/limits/{id}", Method: "DELETE"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/admin/entitlements/{id}", Method: "DELETE"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "hub-scoped",
		BasePermission:   "quota.delete",
		Effects:          []SecurityEffect{EffectDeleteResource},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		AuditObligation: &AuditObligation{
			EventType:     "quota.delete",
			ContextFields: []string{"actor_id"},
			BeforeFields:  []string{"limit_id", "limit_name"},
			Atomic:        true,
		},
		DenialCodes: []DenialCode{DenialForbidden},
		TestRefs:    []TestRef{{Package: "pkg/hub/authzop", Function: "TestCatalogValidation"}},
	},
	{
		ID:          "hub.policies.removed",
		Domain:      "hub",
		Description: "Removed policy API; every method and sub-path answers 410 Gone and points callers to role bindings",
		EntryPoints: []EntryPoint{
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/policies", Method: "GET"},
			{Kind: EntryPointHTTPRoute, Pattern: "/api/v1/policies/{id}", Method: "GET"},
		},
		Principals:       []PrincipalKind{PrincipalUser},
		Credentials:      []CredentialKind{CredentialSessionJWT},
		ResourceResolver: "none",
		Effects:          []SecurityEffect{EffectReadOne},
		DelegationKind:   DelegationNone,
		AuthorityEval:    AuthorityEvalNone,
		TestRefs:         []TestRef{{Package: "pkg/hub", Function: "TestBearerDisposition_EveryRoutePatternCovered"}},
		Exemptions: []Exemption{{
			Kind:   ExemptionAuthenticationOnly,
			Reason: "The handler answers 410 Gone for every caller and reads or changes nothing; no resource permission applies",
			Scope:  "removed policy API",
			Waives: []WaivedObligation{WaiveBasePermission, WaiveDenialCodes},
		}},
		Bearer: NonUser(),
	},
}
