// Code generated by ent, DO NOT EDIT.

package brokertargetinventory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLTE(FieldID, id))
}

// BrokerID applies equality check predicate on the "broker_id" field. It's identical to BrokerIDEQ.
func BrokerID(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldBrokerID, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldTarget, v))
}

// LastCompleteInventoryAt applies equality check predicate on the "last_complete_inventory_at" field. It's identical to LastCompleteInventoryAtEQ.
func LastCompleteInventoryAt(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldLastCompleteInventoryAt, v))
}

// BrokerIDEQ applies the EQ predicate on the "broker_id" field.
func BrokerIDEQ(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldBrokerID, v))
}

// BrokerIDNEQ applies the NEQ predicate on the "broker_id" field.
func BrokerIDNEQ(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNEQ(FieldBrokerID, v))
}

// BrokerIDIn applies the In predicate on the "broker_id" field.
func BrokerIDIn(vs ...string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldIn(FieldBrokerID, vs...))
}

// BrokerIDNotIn applies the NotIn predicate on the "broker_id" field.
func BrokerIDNotIn(vs ...string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNotIn(FieldBrokerID, vs...))
}

// BrokerIDGT applies the GT predicate on the "broker_id" field.
func BrokerIDGT(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGT(FieldBrokerID, v))
}

// BrokerIDGTE applies the GTE predicate on the "broker_id" field.
func BrokerIDGTE(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGTE(FieldBrokerID, v))
}

// BrokerIDLT applies the LT predicate on the "broker_id" field.
func BrokerIDLT(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLT(FieldBrokerID, v))
}

// BrokerIDLTE applies the LTE predicate on the "broker_id" field.
func BrokerIDLTE(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLTE(FieldBrokerID, v))
}

// BrokerIDContains applies the Contains predicate on the "broker_id" field.
func BrokerIDContains(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldContains(FieldBrokerID, v))
}

// BrokerIDHasPrefix applies the HasPrefix predicate on the "broker_id" field.
func BrokerIDHasPrefix(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldHasPrefix(FieldBrokerID, v))
}

// BrokerIDHasSuffix applies the HasSuffix predicate on the "broker_id" field.
func BrokerIDHasSuffix(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldHasSuffix(FieldBrokerID, v))
}

// BrokerIDEqualFold applies the EqualFold predicate on the "broker_id" field.
func BrokerIDEqualFold(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEqualFold(FieldBrokerID, v))
}

// BrokerIDContainsFold applies the ContainsFold predicate on the "broker_id" field.
func BrokerIDContainsFold(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldContainsFold(FieldBrokerID, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldContainsFold(FieldTarget, v))
}

// LastCompleteInventoryAtEQ applies the EQ predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtEQ(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldEQ(FieldLastCompleteInventoryAt, v))
}

// LastCompleteInventoryAtNEQ applies the NEQ predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtNEQ(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNEQ(FieldLastCompleteInventoryAt, v))
}

// LastCompleteInventoryAtIn applies the In predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtIn(vs ...time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldIn(FieldLastCompleteInventoryAt, vs...))
}

// LastCompleteInventoryAtNotIn applies the NotIn predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtNotIn(vs ...time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldNotIn(FieldLastCompleteInventoryAt, vs...))
}

// LastCompleteInventoryAtGT applies the GT predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtGT(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGT(FieldLastCompleteInventoryAt, v))
}

// LastCompleteInventoryAtGTE applies the GTE predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtGTE(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldGTE(FieldLastCompleteInventoryAt, v))
}

// LastCompleteInventoryAtLT applies the LT predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtLT(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLT(FieldLastCompleteInventoryAt, v))
}

// LastCompleteInventoryAtLTE applies the LTE predicate on the "last_complete_inventory_at" field.
func LastCompleteInventoryAtLTE(v time.Time) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.FieldLTE(FieldLastCompleteInventoryAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BrokerTargetInventory) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BrokerTargetInventory) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BrokerTargetInventory) predicate.BrokerTargetInventory {
	return predicate.BrokerTargetInventory(sql.NotPredicates(p))
}
